<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unprefix</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgU3RyaW5nIHByZWZpeCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcHJl
Zml4IiwgU3RyaW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdl
dE9yRGVmYXVsdChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAg
ICBUcmFuc2Zvcm1lck1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIs
IFRyYW5zZm9ybWVyTW9kZS5jbGFzcyk7CgogICAgaWYgKHByZWZpeCAhPSBudWxsKSBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBUcmFuc2Zvcm1lci50cmFuc2Zvcm0obGlzdCwgbmV3
IFVucHJlZml4ZXIobW9kZSwgcHJlZml4LCByZWN1cnNlKSksIGZhbHNlKTsKfSBmaW5hbGx5IHsK
ICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
