<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgQ2hhcnNldCBjaGFyc2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRl
bmNvZGluZyIsIENoYXJzZXQuY2xhc3MpOwogICAgT2JqZWN0Q29udmVydE1vZGUgbW9kZSA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIE9iamVjdENvbnZlcnRNb2RlLmNsYXNzKTsK
CiAgICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJz
b3IsICIkY29udGVudCIsIE9iamVjdEhlbHBlci5jb252ZXJ0KG5ldyBJRGF0YUhqc29uUGFyc2Vy
KCkuZW1pdChkb2N1bWVudCwgY2hhcnNldCksIGNoYXJzZXQsIG1vZGUpLCBmYWxzZSk7CiAgICB9
Cn0gY2F0Y2ggKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgp
Owp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
