<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkdXJhdGlvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGR1cmF0aW9uIik7CiAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUi
KTsKICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0
dGVybi5pbnB1dCIpOwogIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhj
dXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsKICBTdHJpbmcgZGF0ZXRpbWVQYXR0ZXJuID0gSURh
dGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUucGF0dGVybiIpOwoKICBkdXJhdGlv
biA9IGZvcm1hdChkdXJhdGlvbiwgaW5QYXR0ZXJuLCBvdXRQYXR0ZXJuLCBkYXRldGltZSwgZGF0
ZXRpbWVQYXR0ZXJuKTsKCiAgaWYgKGR1cmF0aW9uICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vy
c29yLCAiJGR1cmF0aW9uIiwgZHVyYXRpb24pOwp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95
KCk7Cn0=</value>
</Values>
