<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkdXJhdGlvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGR1cmF0aW9uIik7CiAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUi
KTsKICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0
dGVybi5pbnB1dCIpOwogIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhj
dXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsKICAKICBkdXJhdGlvbiA9IGZvcm1hdChkdXJhdGlv
biwgaW5QYXR0ZXJuLCBvdXRQYXR0ZXJuLCBkYXRldGltZSk7CgogIGlmIChkdXJhdGlvbiAhPSBu
dWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkdXJhdGlvbiIsIGR1cmF0aW9uKTsKfSBmaW5h
bGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
