<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkaXJlY3RvcnkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkaXJlY3RvcnkiKTsK
ICBTdHJpbmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4i
KTsKICBTdHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsK
ICBib29sZWFuIHJlY3Vyc2UgPSBCb29sZWFuLnBhcnNlQm9vbGVhbihJRGF0YVV0aWwuZ2V0U3Ry
aW5nKGN1cnNvciwgIiRyZWN1cnNlPyIpKTsKCiAgYm9vbGVhbiByZWdleCA9IChtb2RlID09IG51
bGwgfHwgbW9kZS5lcXVhbHNJZ25vcmVDYXNlKCJyZWdleCIpKTsKCiAgTGlzdGVyIGxpc3RlciA9
IG5ldyBMaXN0ZXIoZGlyZWN0b3J5LCBwYXR0ZXJuLCByZWdleCwgcmVjdXJzZSk7CgogIElEYXRh
VXRpbC5wdXQoY3Vyc29yLCAiJGRpcmVjdG9yaWVzIiwgbGlzdGVyLmRpcmVjdG9yaWVzKCkpOwog
IElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGZpbGVzIiwgbGlzdGVyLmZpbGVzKCkpOwp9IGZpbmFs
bHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
