<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
VGhyZWFkW10gdGhyZWFkcyA9IFRocmVhZEhlbHBlci5saXN0KCk7DQogICAgaWYgKHRocmVhZHMg
IT0gbnVsbCkgew0KICAgICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiR0aHJlYWRzIiwgVGhy
ZWFkSGVscGVyLnRvSURhdGFBcnJheSh0aHJlYWRzKSk7DQogICAgICAgIElEYXRhVXRpbC5wdXQo
Y3Vyc29yLCAiJHRocmVhZHMubGVuZ3RoIiwgSW50ZWdlckhlbHBlci5lbWl0KHRocmVhZHMubGVu
Z3RoKSk7DQogICAgfSBlbHNlIHsNCiAgICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkdGhy
ZWFkcy5sZW5ndGgiLCAiMCIpOw0KICAgIH0NCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ry
b3koKTsNCn0=</value>
</Values>
