<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
VGhyZWFkW10gdGhyZWFkcyA9IFRocmVhZEhlbHBlci5saXN0KCk7DQogICAgaWYgKHRocmVhZHMg
IT0gbnVsbCkgew0KICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHRocmVhZHMiLCBU
aHJlYWRIZWxwZXIudG9JRGF0YUFycmF5KHRocmVhZHMpKTsNCiAgICAgICAgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiR0aHJlYWRzLmxlbmd0aCIsIHRocmVhZHMubGVuZ3RoLCBTdHJpbmcuY2xh
c3MpOw0KICAgIH0gZWxzZSB7DQogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkdGhy
ZWFkcy5sZW5ndGgiLCAiMCIpOw0KICAgIH0NCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ry
b3koKTsNCn0=</value>
</Values>
