<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBwYXJlbnQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRpbnRlcmZhY2UiKTsKICBT
dHJpbmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4iKTsK
ICBTdHJpbmcgdHlwZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHR5cGUiKTsKICBi
b29sZWFuIHJlY3Vyc2UgPSBCb29sZWFuLnBhcnNlQm9vbGVhbihJRGF0YVV0aWwuZ2V0U3RyaW5n
KGN1cnNvciwgIiRyZWN1cnNlPyIpKTsKICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRub2RlcyIs
IGxpc3QocGFyZW50LCBwYXR0ZXJuLCB0eXBlLCByZWN1cnNlKSk7Cn0gZmluYWxseSB7CiAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
