<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHBhcmVudCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGludGVyZmFjZSIp
Ow0KICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0
dGVybiIpOw0KICAgIFN0cmluZyB0eXBlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
dHlwZSIpOw0KICAgIGJvb2xlYW4gcmVjdXJzZSA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFV
dGlsLmdldFN0cmluZyhjdXJzb3IsICIkcmVjdXJzZT8iKSk7DQoNCiAgICBTb3J0ZWRTZXQ8U3Ry
aW5nPiBzZXQgPSBOb2RlSGVscGVyLmxpc3QocGFyZW50LCBwYXR0ZXJuLCB0eXBlLCByZWN1cnNl
KTsNCg0KICAgIGlmIChzZXQgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkbm9kZXMi
LCBzZXQudG9BcnJheShuZXcgU3RyaW5nW3NldC5zaXplKCldKSk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
