<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gZmlsZXMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGVzIiwgU3RyaW5nW10u
Y2xhc3MpOwoKICAgIExpc3Q8VGhyb3dhYmxlPiBleGNlcHRpb25zID0gbmV3IEFycmF5TGlzdDxU
aHJvd2FibGU+KCk7CgogICAgZm9yIChTdHJpbmcgZmlsZSA6IGZpbGVzKSB7CiAgICAgICAgdHJ5
IHsKICAgICAgICAgICAgRmlsZUhlbHBlci5yZW1vdmUoZmlsZSk7CiAgICAgICAgfSBjYXRjaChJ
T0V4Y2VwdGlvbiBleCkgewogICAgICAgICAgICBleGNlcHRpb25zLmFkZChleCk7CiAgICAgICAg
fQogICAgfQoKICAgIGlmIChleGNlcHRpb25zLnNpemUoKSA+IDApIEV4Y2VwdGlvbkhlbHBlci5y
YWlzZShleGNlcHRpb25zKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
