<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decompress</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIE9iamVj
dCBnemlwID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudC5nemlwIik7CiAgU3RyaW5n
IGVuY29kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZW5jb2RpbmciKTsKICBT
dHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsKCiAgaWYg
KGd6aXAgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY29udGVudCIsIGRlY29tcHJl
c3MoZ3ppcCwgZW5jb2RpbmcsIG1vZGUpKTsKfSBjYXRjaChqYXZhLmlvLklPRXhjZXB0aW9uIGV4
KSB7CiAgdHVuZHJhLmV4Y2VwdGlvbi5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRl
c3Ryb3koKTsKfQ==</value>
</Values>
