<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">index</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtdLmNs
YXNzKTsKICAgIGludCBpbmRleFN0YXJ0ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNv
ciwgIiRpbmRleC5zdGFydCIsIEludGVnZXIuY2xhc3MsIDApOwogICAgaW50IGluZGV4U3RlcCA9
IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkaW5kZXguc3RlcCIsIEludGVnZXIu
Y2xhc3MsIDEpOwoKICAgIGlmIChsaXN0ICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAi
JGluZGV4ZXMiLCBBcnJheUhlbHBlci5pbmRleChsaXN0LCBpbmRleFN0YXJ0LCBpbmRleFN0ZXAp
KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
