<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purge</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBTdHJpbmcuY2xhc3Mp
OwogICAgU3RyaW5nIGR1cmF0aW9uID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJhdGlv
biIsIFN0cmluZy5jbGFzcyk7CiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkZHVyYXRpb24ucGF0dGVybiIsIFN0cmluZy5jbGFzcyk7CiAgICBGaWxlbmFtZUZp
bHRlclR5cGUgZmlsdGVyVHlwZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsdGVyLnR5
cGUiLCBGaWxlbmFtZUZpbHRlclR5cGUuY2xhc3MpOwoKICAgIGxvbmcgY291bnQgPSBGaWxlSGVs
cGVyLnB1cmdlKGZpbGUsIGZpbHRlclR5cGUsIER1cmF0aW9uSGVscGVyLnBhcnNlKGR1cmF0aW9u
LCBwYXR0ZXJuKSk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRjb3VudCIsIGNvdW50
LCBTdHJpbmcuY2xhc3MpOwp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRpb25I
ZWxwZXIucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
