<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purge</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBmaWxlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlIiwgRmlsZS5jbGFzcyk7CiAg
ICBTdHJpbmcgZHVyYXRpb24gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGR1cmF0aW9uIiwg
U3RyaW5nLmNsYXNzKTsKICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkdXJhdGlvbi5wYXR0ZXJuIiwgU3RyaW5nLmNsYXNzKTsKICAgIEZpbGVuYW1lRmlsdGVy
VHlwZSBmaWx0ZXJUeXBlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWx0ZXIudHlwZSIs
IEZpbGVuYW1lRmlsdGVyVHlwZS5jbGFzcyk7CgogICAgbG9uZyBjb3VudCA9IEZpbGVIZWxwZXIu
cHVyZ2UoZmlsZSwgZmlsdGVyVHlwZSwgRHVyYXRpb25IZWxwZXIucGFyc2UoZHVyYXRpb24sIHBh
dHRlcm4pKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGNvdW50IiwgY291bnQsIFN0
cmluZy5jbGFzcyk7Cn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBl
ci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
