<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">touch</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
RmlsZSBmaWxlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlIiwgRmlsZS5jbGFzcyk7
CiAgICBib29sZWFuIGNyZWF0ZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIk
ZmlsZS5jcmVhdGU/IiwgQm9vbGVhbi5jbGFzcywgdHJ1ZSk7CiAgICBDYWxlbmRhciB1cGRhdGVk
ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlLnVwZGF0ZWQiLCBDYWxlbmRhci5jbGFz
cyk7CiAgICAKICAgIEZpbGVIZWxwZXIudG91Y2goZmlsZSwgY3JlYXRlLCB1cGRhdGVkKTsNCn0g
Y2F0Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0K
fSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
