<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoY3Vyc29yLCAiJGxpc3QiKTsN
CiAgICBTdHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNv
ZGluZyIpOw0KICAgIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
bW9kZSIpOw0KDQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY29udGVudCIsIGVtaXQobGlz
dCwgbW9kZSwgZW5jb2RpbmcpKTsNCn0gY2F0Y2ggKGphdmEuaW8uSU9FeGNlcHRpb24gZXgpIHsN
CiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3Iu
ZGVzdHJveSgpOw0KfQ0K</value>
</Values>
