<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoY3Vyc29yLCAiJGxpc3QiKTsN
CiAgICBTdHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNv
ZGluZyIpOw0KICAgIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
bW9kZSIpOw0KCiAgICBpZiAobGlzdCAhPSBudWxsKSB7CiAgICAgICAgSURhdGFNYXAgbWFwID0g
bmV3IElEYXRhTWFwKCk7CiAgICAgICAgbWFwLnB1dCgicmVjb3JkV2l0aE5vSUQiLCBsaXN0KTsK
CiAgICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY29udGVudCIsIE9iamVjdEhlbHBlci5j
b252ZXJ0KElEYXRhSFRNTFBhcnNlci5nZXRJbnN0YW5jZSgpLmVtaXQobWFwLCBlbmNvZGluZyks
IGVuY29kaW5nLCBtb2RlKSk7DQogICAgfQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBleCkgew0KICAg
IEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0
cm95KCk7DQp9</value>
</Values>
