<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnB1dCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7
CiAgICBib29sZWFuIHJlY3Vyc2UgPSBCb29sZWFuSGVscGVyLnBhcnNlKElEYXRhVXRpbC5nZXRT
dHJpbmcoY3Vyc29yLCAiJHJlY3Vyc2U/IikpOwoKICAgIGlmIChpbnB1dCAhPSBudWxsKSB7CiAg
ICAgICAgSURhdGFbXSBvdXRwdXQgPSBJRGF0YUhlbHBlci5zcXVlZXplKGlucHV0LCByZWN1cnNl
KTsKICAgICAgICBpZiAob3V0cHV0ID09IG51bGwpIG91dHB1dCA9IG5ldyBJRGF0YVswXTsKICAg
ICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRsaXN0Iiwgb3V0cHV0KTsKICAgIH0KfSBmaW5h
bGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
