<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnB1dCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIElEYXRhW10u
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBpZiAoaW5wdXQg
IT0gbnVsbCkgewogICAgICAgIElEYXRhW10gb3V0cHV0ID0gVHJhbnNmb3JtZXIudHJhbnNmb3Jt
KGlucHV0LCBuZXcgU3F1ZWV6ZXIocmVjdXJzZSkpOwogICAgICAgIGlmIChvdXRwdXQgPT0gbnVs
bCkgb3V0cHV0ID0gbmV3IElEYXRhWzBdOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
ICIkbGlzdCIsIG91dHB1dCk7CiAgICB9Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3ko
KTsNCn0=</value>
</Values>
