<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnB1dCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIElEYXRhW10u
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBpZiAoaW5wdXQg
IT0gbnVsbCkgewogICAgICAgIElEYXRhW10gb3V0cHV0ID0gSURhdGFIZWxwZXIuc3F1ZWV6ZShp
bnB1dCwgcmVjdXJzZSk7CiAgICAgICAgaWYgKG91dHB1dCA9PSBudWxsKSBvdXRwdXQgPSBuZXcg
SURhdGFbMF07CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRsaXN0Iiwgb3V0cHV0
KTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
