<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">put</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgTWFw
IG1hcCA9IChNYXApSURhdGFVdGlsLmdldChjdXJzb3IsICIkbWFwIik7CiAgICBPYmplY3Qga2V5
ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIka2V5Iik7CiAgICBPYmplY3QgdmFsdWUgPSBJRGF0
YVV0aWwuZ2V0KGN1cnNvciwgIiR2YWx1ZSIpOwogICAgU3RyaW5nIG1vZGUgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKGN1cnNvciwgIiRtb2RlIik7CgogICAgaWYgKG1hcCAhPSBudWxsICYmIGtleSAh
PSBudWxsKSB7CiAgICAgICAgaWYgKG1vZGUgPT0gbnVsbCB8fCBtb2RlLmVxdWFscygiYWx3YXlz
IikpIHsKICAgICAgICAgICAgTWFwSGVscGVyLnB1dChtYXAsIGtleSwgdmFsdWUpOwogICAgICAg
IH0gZWxzZSB7CiAgICAgICAgICAgIE9iamVjdCBleGlzdGluZ1ZhbHVlID0gQ29uY3VycmVudE1h
cEhlbHBlci5wdXRJZkFic2VudCgoQ29uY3VycmVudE1hcCltYXAsIGtleSwgdmFsdWUpOwogICAg
ICAgICAgICBpZiAoZXhpc3RpbmdWYWx1ZSAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwg
IiR2YWx1ZS5leGlzdGluZyIsIGV4aXN0aW5nVmFsdWUpOwogICAgICAgIH0KICAgIH0KfSBmaW5h
bGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
