<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIFN0cmluZ1td
LmNsYXNzKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJz
b3IsICIkcGlwZWxpbmUiLCBJRGF0YS5jbGFzcywgcGlwZWxpbmUpOw0KICAgIFN0cmluZyBkZWZh
dWx0VmFsdWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRlZmF1bHQiLCBTdHJpbmcuY2xh
c3MpOw0KICAgIEVudW1TZXQ8U3Vic3RpdHV0aW9uVHlwZT4gbW9kZSA9IFN1YnN0aXR1dGlvblR5
cGUubm9ybWFsaXplKElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFz
cykpOwoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBTdWJzdGl0dXRpb25I
ZWxwZXIuc3Vic3RpdHV0ZShsaXN0LCBkZWZhdWx0VmFsdWUsIG1vZGUsIHNjb3BlKSk7DQp9IGZp
bmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
