<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIFN0cmluZ1td
LmNsYXNzKTsNCiAgICBTdHJpbmcgZGVmYXVsdFZhbHVlID0gSURhdGFIZWxwZXIuZmlyc3QoY3Vy
c29yLCBTdHJpbmcuY2xhc3MsICIkc3Vic3RpdHV0aW9uLmRlZmF1bHQiLCAiJGRlZmF1bHQiKTsN
CiAgICBTdWJzdGl0dXRpb25UeXBlIG1vZGUgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIFN1
YnN0aXR1dGlvblR5cGUuY2xhc3MsICIkc3Vic3RpdHV0aW9uLm1vZGUiLCAiJG1vZGUiKTsKICAg
IElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRwaXBlbGlu
ZSIsIElEYXRhLmNsYXNzLCBwaXBlbGluZSk7Cg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
ICIkbGlzdCIsIFN1YnN0aXR1dGlvbkhlbHBlci5zdWJzdGl0dXRlKGxpc3QsIFN0cmluZy5jbGFz
cywgZGVmYXVsdFZhbHVlLCBtb2RlLCBzY29wZSkpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3Iu
ZGVzdHJveSgpOw0KfQ==</value>
</Values>
