<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGlu
ZSIpOw0KICAgIFN0cmluZyBkZWZhdWx0VmFsdWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNv
ciwgIiRkZWZhdWx0Iik7DQogICAgRW51bVNldDxTdWJzdGl0dXRpb25UeXBlPiBtb2RlID0gU3Vi
c3RpdHV0aW9uVHlwZS5ub3JtYWxpemUoSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9k
ZSIpKTsKDQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkbGlzdCIsIFN1YnN0aXR1dGlvbkhl
bHBlci5zdWJzdGl0dXRlKGxpc3QsIGRlZmF1bHRWYWx1ZSwgc2NvcGUgPT0gbnVsbCA/IHBpcGVs
aW5lIDogc2NvcGUsIG1vZGUpKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0=</value>
</Values>
