<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGJvb2wgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIiRib29sZWFuIik7DQogICAgU3Ry
aW5nIHRydWVWYWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHZhbHVlLnRydWUi
KTsNCiAgICBTdHJpbmcgZmFsc2VWYWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAi
JHZhbHVlLmZhbHNlIik7DQoNCiAgICBpZiAoYm9vbCAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1
cnNvciwgIiRzdHJpbmciLCBCb29sZWFuSGVscGVyLmVtaXQoQm9vbGVhbkhlbHBlci5wYXJzZShi
b29sLnRvU3RyaW5nKCkpLCB0cnVlVmFsdWUsIGZhbHNlVmFsdWUpKTsNCn0gZmluYWxseSB7DQog
ICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
