<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGJvb2wgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGJvb2xlYW4iKTsNCiAgICBT
dHJpbmcgdHJ1ZVZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiR2YWx1ZS50cnVlIiwg
U3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgZmFsc2VWYWx1ZSA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkdmFsdWUuZmFsc2UiLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgaWYgKGJvb2wgIT0g
bnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzdHJpbmciLCBCb29sZWFuSGVscGVyLmVt
aXQoQm9vbGVhbkhlbHBlci5wYXJzZShib29sLnRvU3RyaW5nKCkpLCB0cnVlVmFsdWUsIGZhbHNl
VmFsdWUpKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
