<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unequal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZXhwZWN0ZWQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGV4cGVjdGVkIiwgSURh
dGEuY2xhc3MpOw0KICAgIElEYXRhIGFjdHVhbCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
YWN0dWFsIiwgSURhdGEuY2xhc3MpOw0KICAgIFN0cmluZyBtZXNzYWdlID0gSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgIiRtZXNzYWdlIiwgU3RyaW5nLmNsYXNzKTsNCg0gICAgYm9vbGVhbiBzdHJp
Y3QgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJHN0cmljdD8iLCBCb29sZWFu
LmNsYXNzLCBmYWxzZSk7CgogICAgdW5lcXVhbChleHBlY3RlZCwgYWN0dWFsLCBtZXNzYWdlLCBz
dHJpY3QpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
