<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIENoYXJzZXQgY2hhcnNldCA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNv
ciwgQ2hhcnNldC5jbGFzcywgIiRjb250ZW50LmVuY29kaW5nIiwgIiRlbmNvZGluZyIpOw0KICAg
IE9iamVjdENvbnZlcnRNb2RlIG1vZGUgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIE9iamVj
dENvbnZlcnRNb2RlLmNsYXNzLCAiJGNvbnRlbnQubW9kZSIsICIkbW9kZSIpOwogICAgaWYgKGRv
Y3VtZW50ICE9IG51bGwpIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGNvbnRl
bnQiLCBPYmplY3RIZWxwZXIuY29udmVydChuZXcgSURhdGFIVE1MUGFyc2VyKCkuZW1pdChkb2N1
bWVudCwgY2hhcnNldCksIGNoYXJzZXQsIG1vZGUpLCBmYWxzZSk7DQogICAgfQp9IGNhdGNoIChJ
T0V4Y2VwdGlvbiBleCkgew0KICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFs
bHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
