<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unsuffix</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgU3RyaW5nIHN1ZmZpeCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3Vm
Zml4IiwgU3RyaW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdl
dE9yRGVmYXVsdChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAg
ICBUcmFuc2Zvcm1lck1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIs
IFRyYW5zZm9ybWVyTW9kZS5jbGFzcyk7CgogICAgaWYgKHN1ZmZpeCAhPSBudWxsKSBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBJRGF0YUhlbHBlci51bnN1ZmZpeChsaXN0LCBzdWZm
aXgsIG1vZGUsIHJlY3Vyc2UpLCBmYWxzZSk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJv
eSgpOwp9</value>
</Values>
