<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiply</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkdXJhdGlvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGR1cmF0aW9uIik7CiAg
U3RyaW5nIGluUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4u
aW5wdXQiKTsKICBTdHJpbmcgb3V0UGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJHBhdHRlcm4ub3V0cHV0Iik7CiAgU3RyaW5nIGRhdGV0aW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUiKTsKICBTdHJpbmcgZGF0ZXRpbWVQYXR0ZXJuID0gSURh
dGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUucGF0dGVybiIpOwogIFN0cmluZyBm
YWN0b3IgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRmYWN0b3IiKTsKCiAgZHVyYXRp
b24gPSBtdWx0aXBseShkdXJhdGlvbiwgZmFjdG9yLCBkYXRldGltZSwgaW5QYXR0ZXJuLCBvdXRQ
YXR0ZXJuLCBkYXRldGltZVBhdHRlcm4pOwoKICBpZiAoZHVyYXRpb24gIT0gbnVsbCkgSURhdGFV
dGlsLnB1dChjdXJzb3IsICIkZHVyYXRpb24iLCBkdXJhdGlvbik7Cn0gZmluYWxseSB7CiAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
