<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiply</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGR1cmF0aW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZHVyYXRpb24i
KTsNCiAgICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
cGF0dGVybi5pbnB1dCIpOw0KICAgIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsNCiAgICBTdHJpbmcgZGF0ZXRpbWUgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkYXRldGltZSIpOw0KICAgIFN0cmluZyBkYXRl
dGltZVBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkYXRldGltZS5wYXR0
ZXJuIik7DQogICAgU3RyaW5nIGZhY3RvciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAi
JGZhY3RvciIpOw0KDQogICAgZHVyYXRpb24gPSBEdXJhdGlvbkhlbHBlci5lbWl0KER1cmF0aW9u
SGVscGVyLm11bHRpcGx5KER1cmF0aW9uSGVscGVyLnBhcnNlKGR1cmF0aW9uLCBpblBhdHRlcm4p
LCBEZWNpbWFsSGVscGVyLnBhcnNlKGZhY3RvciksIGRhdGV0aW1lLCBkYXRldGltZVBhdHRlcm4p
KTsNCg0KICAgIGlmIChkdXJhdGlvbiAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRk
dXJhdGlvbiIsIGR1cmF0aW9uKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0=</value>
</Values>
