<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgaW5wdXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsNCg0KICAgIGlmIChpbnB1
dCAhPSBudWxsKSB7CiAgICAgICAgSURhdGEgb3V0cHV0ID0gSURhdGFIZWxwZXIuc3F1ZWV6ZShp
bnB1dCwgcmVjdXJzZSk7CiAgICAgICAgaWYgKG91dHB1dCA9PSBudWxsKSBvdXRwdXQgPSBJRGF0
YUZhY3RvcnkuY3JlYXRlKCk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1
bWVudCIsIG91dHB1dCk7DQogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
