<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIElE
YXRhIGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOw0K
ICBib29sZWFuIHJlY3Vyc2UgPSBCb29sZWFuSGVscGVyLnBhcnNlKElEYXRhVXRpbC5nZXRTdHJp
bmcoY3Vyc29yLCAiJHJlY3Vyc2U/IikpOw0KDQogIGlmIChkb2N1bWVudCAhPSBudWxsKSB7DQog
ICAgZG9jdW1lbnQgPSBzcXVlZXplKGRvY3VtZW50LCByZWN1cnNlKTsNCiAgICBpZiAoZG9jdW1l
bnQgPT0gbnVsbCkgZG9jdW1lbnQgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQogICAgSURhdGFV
dGlsLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBkb2N1bWVudCk7DQogIH0NCn0gZmluYWxseSB7
DQogIGN1cnNvci5kZXN0cm95KCk7DQp9DQo=</value>
</Values>
