<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIGJv
b2xlYW4gcmVjdXJzZSA9IEJvb2xlYW4ucGFyc2VCb29sZWFuKElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJHJlY3Vyc2U/IikpOwoKICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgewogICAgZG9j
dW1lbnQgPSBzcXVlZXplKGRvY3VtZW50LCByZWN1cnNlKTsKICAgIGlmIChkb2N1bWVudCA9PSBu
dWxsKSBkb2N1bWVudCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKICAgIElEYXRhVXRpbC5wdXQo
Y3Vyc29yLCAiJGRvY3VtZW50IiwgZG9jdW1lbnQpOwogIH0KfSBmaW5hbGx5IHsKICBjdXJzb3Iu
ZGVzdHJveSgpOwp9</value>
</Values>
