<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIFN0cmluZyBzZXBhcmF0b3JDaGFyYWN0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRzZXBhcmF0b3IiKTsNCiAgICBTdHJpbmcgZGVmYXVsdENoYXJhY3RlciA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRlZmF1bHQiKTsKICAgIGJvb2xlYW4gaW5jbHVkZU51
bGxzID0gQm9vbGVhbkhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRu
dWxscz8iKSk7Cg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcmVzdWx0IiwgQXJyYXlI
ZWxwZXIuam9pbihsaXN0LCBzZXBhcmF0b3JDaGFyYWN0ZXIsIGRlZmF1bHRDaGFyYWN0ZXIsIGlu
Y2x1ZGVOdWxscyksIGZhbHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0=</value>
</Values>
