<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIFN0cmluZyBzZXBhcmF0b3JDaGFyYWN0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRzZXBhcmF0b3IiKTsNCiAgICBTdHJpbmcgZGVmYXVsdENoYXJhY3RlciA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRlZmF1bHQiKTsKICAgIGJvb2xlYW4gaW5jbHVkZU51
bGxzID0gQm9vbGVhbkhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRu
dWxscz8iKSk7Cg0KICAgIFN0cmluZyByZXN1bHQgPSBBcnJheUhlbHBlci5qb2luKGxpc3QsIHNl
cGFyYXRvckNoYXJhY3RlciwgaW5jbHVkZU51bGxzKTsKICAgIGlmIChyZXN1bHQgPT0gbnVsbCkg
cmVzdWx0ID0gZGVmYXVsdENoYXJhY3RlcjsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAi
JHJlc3VsdCIsIHJlc3VsdCwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJv
eSgpOw0KfQ==</value>
</Values>
