<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBTdHJpbmcgc2VwYXJhdG9yQ2hhcmFjdGVyID0gSURhdGFIZWxwZXIuZ2V0
KGN1cnNvciwgIiRzZXBhcmF0b3IiLCBTdHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyBkZWZhdWx0
Q2hhcmFjdGVyID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkZWZhdWx0IiwgU3RyaW5nLmNs
YXNzKTsKICAgIFNhbml0aXphdGlvbiBzYW5pdGl6YXRpb24gPSBJRGF0YUhlbHBlci5nZXQoY3Vy
c29yLCAiJHNhbml0aXphdGlvbiIsIFNhbml0aXphdGlvbi5jbGFzcyk7Cg0KICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkcmVzdWx0IiwgQXJyYXlIZWxwZXIuam9pbihsaXN0LCBzZXBhcmF0
b3JDaGFyYWN0ZXIsIGRlZmF1bHRDaGFyYWN0ZXIsIHNhbml0aXphdGlvbiksIGZhbHNlKTsNCn0g
ZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
