<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">divide</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gZGl2aWRlbmRzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkaXZpZGVuZHMiLCBT
dHJpbmdbXS5jbGFzcyk7CiAgICBCaWdJbnRlZ2VyIGRpdmlzb3IgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJGRpdmlzb3IiLCBCaWdJbnRlZ2VyLmNsYXNzKTsKCiAgICBCaWdJbnRlZ2VyW10g
cmVzdWx0cyA9IEJpZ0ludGVnZXJIZWxwZXIuZGl2aWRlKEJpZ0ludGVnZXJIZWxwZXIubm9ybWFs
aXplKGRpdmlkZW5kcyksIGRpdmlzb3IpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIk
cmVzdWx0cyIsIEJpZ0ludGVnZXJIZWxwZXIuZW1pdChyZXN1bHRzKSwgZmFsc2UpOwp9IGZpbmFs
bHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
