<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">capitalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURh
dGEuY2xhc3MpOwogICAgU3RyaW5nIGNhcGl0YWxpemUgPSBJRGF0YUhlbHBlci5maXJzdChjdXJz
b3IsIFN0cmluZy5jbGFzcywgIiRjYXBpdGFsaXplIiwgIiRtb2RlIik7DQogICAgYm9vbGVhbiBm
aXJzdFdvcmRPbmx5ID0gY2FwaXRhbGl6ZSA9PSBudWxsID8gZmFsc2UgOiBjYXBpdGFsaXplLmVx
dWFsc0lnbm9yZUNhc2UoImZpcnN0IHdvcmQiKTsKCiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkg
ewogICAgICAgIFN0cmluZyBpbnB1dCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5n
IiwgU3RyaW5nLmNsYXNzKTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmlu
ZyIsIFN0cmluZ0hlbHBlci5jYXBpdGFsaXplKGlucHV0LCBmaXJzdFdvcmRPbmx5KSwgZmFsc2Up
Ow0KICAgIH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRyZXN1bHRz
IiwgSURhdGFIZWxwZXIuY2FwaXRhbGl6ZShvcGVyYW5kcywgZmlyc3RXb3JkT25seSwgVHJhbnNm
b3JtZXJNb2RlLlZBTFVFUywgdHJ1ZSksIGZhbHNlKTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBj
dXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
