<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnB1dCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7
DQogICAgYm9vbGVhbiByZWN1cnNlID0gQm9vbGVhbkhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0
U3RyaW5nKGN1cnNvciwgIiRyZWN1cnNlPyIpKTsNCgogICAgaWYgKGlucHV0ICE9IG51bGwpIHsK
ICAgICAgICBJRGF0YVtdIG91dHB1dCA9IElEYXRhSGVscGVyLmNvbXBhY3QoaW5wdXQsIHJlY3Vy
c2UpOwogICAgICAgIGlmIChvdXRwdXQgPT0gbnVsbCkgb3V0cHV0ID0gbmV3IElEYXRhWzBdOwog
ICAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGxpc3QiLCBvdXRwdXQpOwogICAgfQp9IGZp
bmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
