<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnB1dCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIElEYXRhW10u
Y2xhc3MpOw0KICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChj
dXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7DQoKICAgIGlmIChpbnB1
dCAhPSBudWxsKSB7CiAgICAgICAgSURhdGFbXSBvdXRwdXQgPSBJRGF0YUhlbHBlci5jb21wYWN0
KGlucHV0LCByZWN1cnNlKTsKICAgICAgICBpZiAob3V0cHV0ID09IG51bGwpIG91dHB1dCA9IG5l
dyBJRGF0YVswXTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBvdXRw
dXQpOwogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
