<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">subtract</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHggPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGR1cmF0aW9uLngiLCBTdHJpbmcu
Y2xhc3MpOw0KICAgIFN0cmluZyB5ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJhdGlv
bi55IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgIiRwYXR0ZXJuLmlucHV0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcg
b3V0UGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiLCBT
dHJpbmcuY2xhc3MpOw0KDQogICAgU3RyaW5nIHJlc3VsdCA9IER1cmF0aW9uSGVscGVyLmVtaXQo
RHVyYXRpb25IZWxwZXIuc3VidHJhY3QoRHVyYXRpb25IZWxwZXIucGFyc2UoeCwgaW5QYXR0ZXJu
KSwgRHVyYXRpb25IZWxwZXIucGFyc2UoeSwgaW5QYXR0ZXJuKSksIG91dFBhdHRlcm4pOw0KDQog
ICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkdXJhdGlvbiIsIHJlc3VsdCwgZmFsc2UpOw0K
fSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
