<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiply</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gdmFsdWVzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiR2YWx1ZXMiLCBTdHJpbmdb
XS5jbGFzcyk7CiAgICBJRGF0YSBvcGVyYW5kcyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
b3BlcmFuZHMiLCBJRGF0YS5jbGFzcyk7CgogICAgQmlnSW50ZWdlcltdIHJlc3VsdHMgPSBCaWdJ
bnRlZ2VySGVscGVyLm11bHRpcGx5KEJpZ0ludGVnZXJIZWxwZXIubm9ybWFsaXplKHZhbHVlcyks
IEJpZ0ludGVnZXJIZWxwZXIubm9ybWFsaXplKElEYXRhSGVscGVyLmdldExlYXZlcyhvcGVyYW5k
cykpKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHJlc3VsdHMiLCBCaWdJbnRlZ2Vy
SGVscGVyLmVtaXQocmVzdWx0cyksIGZhbHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0
cm95KCk7Cn0=</value>
</Values>
