<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQ29u
Y3VycmVudE1hcCBtYXAgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG1hcCIsIENvbmN1cnJl
bnRNYXAuY2xhc3MpOwogICAgT2JqZWN0IGtleSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
a2V5Iik7CiAgICBPYmplY3Qgb2xkVmFsdWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHZh
bHVlLm9sZCIpOwogICAgT2JqZWN0IG5ld1ZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwg
IiR2YWx1ZS5uZXciKTsKCiAgICBpZiAob2xkVmFsdWUgPT0gbnVsbCkgewogICAgICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkdmFsdWUucmVwbGFjZWQ/IiwgQ29uY3VycmVudE1hcEhlbHBl
ci5yZXBsYWNlKG1hcCwga2V5LCBuZXdWYWx1ZSkgIT0gbnVsbCwgU3RyaW5nLmNsYXNzKTsKICAg
IH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiR2YWx1ZS5yZXBsYWNl
ZD8iLCBDb25jdXJyZW50TWFwSGVscGVyLnJlcGxhY2UobWFwLCBrZXksIG9sZFZhbHVlLCBuZXdW
YWx1ZSksIFN0cmluZy5jbGFzcyk7CiAgICB9Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJv
eSgpOwp9</value>
</Values>
