<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sort</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
W10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7CiAgSURh
dGFbXSBjcml0ZXJpYSA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRjcml0ZXJp
YSIpOwoKICAvLyBzaWxlbnRseSBzdXBwb3J0ICRrZXksICRrZXlzIGFuZCAkYXNjZW5kaW5nPyBm
b3IgYmFja3dhcmRzIGNvbXBhdGliaWxpdHkKICBTdHJpbmdbXSBrZXlzID0gSURhdGFVdGlsLmdl
dFN0cmluZ0FycmF5KGN1cnNvciwgIiRrZXlzIik7CiAgU3RyaW5nIGtleSA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoY3Vyc29yLCAiJGtleSIpOwogIFN0cmluZyBzQXNjZW5kaW5nID0gSURhdGFVdGls
LmdldFN0cmluZyhjdXJzb3IsICIkYXNjZW5kaW5nPyIpOwogIGJvb2xlYW4gYXNjZW5kaW5nID0g
dHJ1ZTsKICBpZiAoc0FzY2VuZGluZyAhPSBudWxsKSBhc2NlbmRpbmcgPSB0dW5kcmEuYm9vbC5w
YXJzZShzQXNjZW5kaW5nKTsKCiAgaWYgKGxpc3QgIT0gbnVsbCkgewogICAgaWYgKGNyaXRlcmlh
ID09IG51bGwpIHsKICAgICAgaWYgKGtleXMgPT0gbnVsbCkgewogICAgICAgIElEYXRhVXRpbC5w
dXQoY3Vyc29yLCAiJGxpc3QiLCBzb3J0KGxpc3QsIGtleSwgYXNjZW5kaW5nKSk7CiAgICAgIH0g
ZWxzZSB7CiAgICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkbGlzdCIsIHNvcnQobGlzdCwg
a2V5cywgYXNjZW5kaW5nKSk7CiAgICAgIH0KICAgIH0gZWxzZSB7CiAgICAgIElEYXRhVXRpbC5w
dXQoY3Vyc29yLCAiJGxpc3QiLCBzb3J0KGxpc3QsIGNyaXRlcmlhKSk7CiAgICB9CiAgfQp9IGZp
bmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
