<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">first</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOwoNCiAgICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgew0KICAgICAgICBJRGF0YUN1
cnNvciBkb2N1bWVudEN1cnNvciA9IGRvY3VtZW50LmdldEN1cnNvcigpOw0KICAgICAgICBpZiAo
ZG9jdW1lbnRDdXJzb3IuZmlyc3QoKSkgew0KICAgICAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1
cnNvciwgIiRrZXkiLCBkb2N1bWVudEN1cnNvci5nZXRLZXkoKSk7DQogICAgICAgICAgICBJRGF0
YUhlbHBlci5wdXQoY3Vyc29yLCAiJHZhbHVlIiwgZG9jdW1lbnRDdXJzb3IuZ2V0VmFsdWUoKSk7
DQogICAgICAgIH0NCiAgICAgICAgZG9jdW1lbnRDdXJzb3IuZGVzdHJveSgpOw0KICAgIH0NCn0g
ZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
