<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">first</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIGlm
IChkb2N1bWVudCAhPSBudWxsKSB7CiAgICBJRGF0YUN1cnNvciBkYyA9IGRvY3VtZW50LmdldEN1
cnNvcigpOwogICAgaWYgKGRjLmZpcnN0KCkpIHsKICAgICAgU3RyaW5nIGtleSA9IGRjLmdldEtl
eSgpOwogICAgICBPYmplY3QgdmFsdWUgPSBkYy5nZXRWYWx1ZSgpOwogICAgICBJRGF0YVV0aWwu
cHV0KGN1cnNvciwgIiRrZXkiLCBrZXkpOwogICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiR2
YWx1ZSIsIHZhbHVlKTsKICAgIH0KICAgIGRjLmRlc3Ryb3koKTsKICB9Cn0gZmluYWxseSB7CiAg
Y3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
