<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGlucHV0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkaW5wdXQiKTsNCiAgICBPYmpl
Y3Qgb3V0cHV0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkb3V0cHV0Iik7DQogICAgYm9vbGVh
biBjbG9zZSA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3Is
ICIkY2xvc2U/IiksIHRydWUpOw0KICAgIElucHV0T3V0cHV0SGVscGVyLmNvcHkoSW5wdXRTdHJl
YW1IZWxwZXIubm9ybWFsaXplKGlucHV0KSwgKE91dHB1dFN0cmVhbSlvdXRwdXQsIGNsb3NlKTsN
Cn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgp
Ow0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
