<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">legalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVs
dChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7DQogICAgVHJhbnNm
b3JtZXJNb2RlIG1vZGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG1vZGUiLCBUcmFuc2Zv
cm1lck1vZGUuY2xhc3MpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQi
LCBUcmFuc2Zvcm1lci50cmFuc2Zvcm0oZG9jdW1lbnQsIG5ldyBMZWdhbGl6ZXIobW9kZSwgcmVj
dXJzZSkpLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
