<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ensure</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gJHNlcnZpY2VzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzZXJ2aWNlcyIs
IFN0cmluZ1tdLmNsYXNzKTsNCiAgICBTdHJpbmcgJGNhdGNoID0gSURhdGFIZWxwZXIuZ2V0KGN1
cnNvciwgIiRjYXRjaCIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nICRmaW5hbGx5ID0gSURh
dGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaW5hbGx5IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBJRGF0
YSBzY29wZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcGlwZWxpbmUiLCBJRGF0YS5jbGFz
cyk7DQogICAgYm9vbGVhbiBzY29wZWQgPSBzY29wZSAhPSBudWxsOw0KDQogICAgc2NvcGUgPSBl
bnN1cmUoJHNlcnZpY2VzLCBzY29wZWQgPyBzY29wZSA6IHBpcGVsaW5lLCAkY2F0Y2gsICRmaW5h
bGx5KTsNCg0KICAgIGlmIChzY29wZWQpIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcGlwZWxp
bmUiLCBzY29wZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
