<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ensure</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gJHNlcnZpY2VzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRz
ZXJ2aWNlcyIpOw0KICAgIFN0cmluZyAkY2F0Y2ggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNv
ciwgIiRjYXRjaCIpOw0KICAgIFN0cmluZyAkZmluYWxseSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJGZpbmFsbHkiKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhVXRpbC5nZXRJRGF0
YShjdXJzb3IsICIkcGlwZWxpbmUiKTsNCiAgICBib29sZWFuIHNjb3BlZCA9IHNjb3BlICE9IG51
bGw7DQoNCiAgICBzY29wZSA9IGVuc3VyZSgkc2VydmljZXMsIHNjb3BlZCA/IHNjb3BlIDogcGlw
ZWxpbmUsICRjYXRjaCwgJGZpbmFsbHkpOw0KDQogICAgaWYgKHNjb3BlZCkgSURhdGFVdGlsLnB1
dChjdXJzb3IsICIkcGlwZWxpbmUiLCBzY29wZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5k
ZXN0cm95KCk7DQp9</value>
</Values>
