<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHBh
dHRlcm4iLCBTdHJpbmcuY2xhc3MpOwogICAgYm9vbGVhbiBsaXRlcmFsUGF0dGVybiA9IElEYXRh
SGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xlYW4u
Y2xhc3MsIGZhbHNlKTsKICAgIFN0cmluZyByZXBsYWNlbWVudCA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkcmVwbGFjZW1lbnQiLCBTdHJpbmcuY2xhc3MpOwogICAgYm9vbGVhbiBsaXRlcmFs
UmVwbGFjZW1lbnQgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJHJlcGxhY2Vt
ZW50LmxpdGVyYWw/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwogICAgYm9vbGVhbiBmaXJzdE9j
Y3VycmVuY2UgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJG9jY3VycmVuY2Uu
Zmlyc3Q/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURh
dGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3Ms
IGZhbHNlKTsKICAgIFRyYW5zZm9ybWVyTW9kZSBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRtb2RlIiwgVHJhbnNmb3JtZXJNb2RlLmNsYXNzKTsKCiAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGFIZWxwZXIucmVwbGFjZShkb2N1bWVudCwgcGF0dGVy
biwgbGl0ZXJhbFBhdHRlcm4sIHJlcGxhY2VtZW50LCBsaXRlcmFsUmVwbGFjZW1lbnQsIGZpcnN0
T2NjdXJyZW5jZSwgbW9kZSwgcmVjdXJzZSksIGZhbHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNv
ci5kZXN0cm95KCk7Cn0=</value>
</Values>
