<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compress</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIE9i
amVjdCBpbnB1dCA9IElEYXRhVXRpbC5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsNCiAgU3RyaW5n
IGNoYXJzZXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNvZGluZyIpOw0KICBT
dHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsNCiAgDQog
IE9iamVjdCBvdXRwdXQgPSBPYmplY3RIZWxwZXIuY29udmVydChHemlwSGVscGVyLmNvbXByZXNz
KFN0cmVhbUhlbHBlci5ub3JtYWxpemUoaW5wdXQsIGNoYXJzZXQpKSwgY2hhcnNldCwgbW9kZSk7
DQogIA0KICBpZiAob3V0cHV0ICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNvbnRl
bnQuZ3ppcCIsIG91dHB1dCk7DQp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7DQogIEV4Y2VwdGlv
bkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==
</value>
</Values>
