<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compress</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGlucHV0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudCIpOw0KICAgIFN0
cmluZyBjaGFyc2V0ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZW5jb2RpbmciKTsN
CiAgICBTdHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsN
Cg0KICAgIE9iamVjdCBvdXRwdXQgPSBPYmplY3RIZWxwZXIuY29udmVydChHemlwSGVscGVyLmNv
bXByZXNzKFN0cmVhbUhlbHBlci5ub3JtYWxpemUoaW5wdXQsIGNoYXJzZXQpKSwgY2hhcnNldCwg
bW9kZSk7DQoNCiAgICBpZiAob3V0cHV0ICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAi
JGNvbnRlbnQuZ3ppcCIsIG91dHB1dCk7DQp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7DQogICAg
RXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ry
b3koKTsNCn0=</value>
</Values>
