<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">maximum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gZGF0ZXRpbWVzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZXMi
LCBTdHJpbmdbXS5jbGFzcyk7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgU3RyaW5nIGRhdGV0aW1l
ID0gRGF0ZVRpbWVIZWxwZXIuZW1pdChEYXRlVGltZUhlbHBlci5tYXhpbXVtKERhdGVUaW1lSGVs
cGVyLnBhcnNlKGRhdGV0aW1lcywgcGF0dGVybikpLCBwYXR0ZXJuKTsNCg0KICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkZGF0ZXRpbWUiLCBkYXRldGltZSwgZmFsc2UpOw0KfSBmaW5hbGx5
IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
