<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">maximum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gZGF0ZXRpbWVzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRk
YXRldGltZXMiKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vy
c29yLCAiJHBhdHRlcm4iKTsNCg0KICAgIFN0cmluZyBkYXRldGltZSA9IERhdGVUaW1lSGVscGVy
LmVtaXQoRGF0ZVRpbWVIZWxwZXIubWF4aW11bShEYXRlVGltZUhlbHBlci5wYXJzZShkYXRldGlt
ZXMsIHBhdHRlcm4pKSwgcGF0dGVybik7DQoNCiAgICBpZiAoZGF0ZXRpbWUgIT0gbnVsbCkgSURh
dGFVdGlsLnB1dChjdXJzb3IsICIkZGF0ZXRpbWUiLCBkYXRldGltZSk7DQp9IGZpbmFsbHkgew0K
ICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
