<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unequal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGFbXSBleHBlY3RlZCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZXhwZWN0ZWQiLCBJRGF0
YVtdLmNsYXNzKTsKICAgIElEYXRhW10gYWN0dWFsID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwg
IiRhY3R1YWwiLCBJRGF0YVtdLmNsYXNzKTsKICAgIFN0cmluZyBtZXNzYWdlID0gSURhdGFIZWxw
ZXIuZ2V0KGN1cnNvciwgIiRtZXNzYWdlIiwgU3RyaW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gc3Ry
aWN0ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRzdHJpY3Q/IiwgQm9vbGVh
bi5jbGFzcywgZmFsc2UpOwoKICAgIHVuZXF1YWwoZXhwZWN0ZWQsIGFjdHVhbCwgbWVzc2FnZSwg
c3RyaWN0KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
