<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gZGlyZWN0b3JpZXMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRpcmVjdG9yaWVz
IiwgU3RyaW5nW10uY2xhc3MpOwogICAgYm9vbGVhbiBkZWxldGVTZWxmID0gSURhdGFIZWxwZXIu
Z2V0T3JEZWZhdWx0KGN1cnNvciwgIiRkZWxldGU/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwog
ICAgYm9vbGVhbiByYWlzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcmFp
c2U/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwoKICAgIExpc3Q8VGhyb3dhYmxlPiBleGNlcHRp
b25zID0gbmV3IEFycmF5TGlzdDxUaHJvd2FibGU+KCk7CgogICAgZm9yIChTdHJpbmcgZGlyZWN0
b3J5IDogZGlyZWN0b3JpZXMpIHsKICAgICAgICB0cnkgewogICAgICAgICAgICBEaXJlY3RvcnlI
ZWxwZXIuY29tcGFjdChGaWxlSGVscGVyLmNvbnN0cnVjdChkaXJlY3RvcnkpLCBkZWxldGVTZWxm
KTsKICAgICAgICB9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAgICAgICAgICAgIGV4Y2VwdGlv
bnMuYWRkKGV4KTsKICAgICAgICB9CiAgICB9CgogICAgaWYgKHJhaXNlICYmIGV4Y2VwdGlvbnMu
c2l6ZSgpID4gMCkgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4Y2VwdGlvbnMpOwp9IGZpbmFsbHkg
ewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
