<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkYXRldGltZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRhdGV0aW1lIik7CiAg
U3RyaW5nIHBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7
CiAgU3RyaW5nW10gcGF0dGVybnMgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nQXJyYXkoY3Vyc29yLCAi
JHBhdHRlcm5zIik7CgogIGlmIChkYXRldGltZSAhPSBudWxsKSB7CiAgICBqYXZhLnV0aWwuQ2Fs
ZW5kYXIgY2FsZW5kYXIgPSBudWxsOwogICAgaWYgKHBhdHRlcm5zID09IG51bGwpIHsKICAgICAg
Y2FsZW5kYXIgPSBwYXJzZShkYXRldGltZSwgcGF0dGVybik7CiAgICB9IGVsc2UgewogICAgICBj
YWxlbmRhciA9IHBhcnNlKGRhdGV0aW1lLCBwYXR0ZXJucyk7CiAgICB9CiAgICBJRGF0YVV0aWwu
cHV0KGN1cnNvciwgIiRkYXRldGltZS5vYmplY3QiLCBjYWxlbmRhci5nZXRUaW1lKCkpOwogIH0K
fSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
