<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">condense</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgaW5wdXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsNCg0KICAgIGlmIChpbnB1
dCAhPSBudWxsKSB7CiAgICAgICAgSURhdGEgb3V0cHV0ID0gSURhdGFIZWxwZXIuY29uZGVuc2Uo
aW5wdXQsIHJlY3Vyc2UpOwogICAgICAgIGlmIChvdXRwdXQgPT0gbnVsbCkgb3V0cHV0ID0gSURh
dGFGYWN0b3J5LmNyZWF0ZSgpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9j
dW1lbnQiLCBvdXRwdXQpOw0KICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgp
Ow0KfQ==</value>
</Values>
