<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlucHV0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcu
Y2xhc3MpOw0KICAgIFN0cmluZyB0cnVlVmFsdWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAi
JHZhbHVlLnRydWUiLCBTdHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyBmYWxzZVZhbHVlID0gSURh
dGFIZWxwZXIuZ2V0KGN1cnNvciwgIiR2YWx1ZS5mYWxzZSIsIFN0cmluZy5jbGFzcyk7DQoNCiAg
ICBpZiAoaW5wdXQgIT0gbnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRib29sZWFuIiwg
Qm9vbGVhbkhlbHBlci5wYXJzZShpbnB1dCwgdHJ1ZVZhbHVlLCBmYWxzZVZhbHVlKSk7DQp9IGZp
bmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
