<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGluU3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJp
bmcuY2xhc3MpOw0KICAgIFN0cmluZyBpblRydWVWYWx1ZSA9IElEYXRhSGVscGVyLmdldChjdXJz
b3IsICIkdmFsdWUudHJ1ZS5pbnB1dCIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGluRmFs
c2VWYWx1ZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkdmFsdWUuZmFsc2UuaW5wdXQiLCBT
dHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyBvdXRUcnVlVmFsdWUgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHZhbHVlLnRydWUub3V0cHV0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcg
b3V0RmFsc2VWYWx1ZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkdmFsdWUuZmFsc2Uub3V0
cHV0IiwgU3RyaW5nLmNsYXNzKTsNCg0KICAgIGlmIChpblN0cmluZyAhPSBudWxsKSBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAgIiRzdHJpbmciLCBCb29sZWFuSGVscGVyLmZvcm1hdChpblN0cmlu
ZywgaW5UcnVlVmFsdWUsIGluRmFsc2VWYWx1ZSwgb3V0VHJ1ZVZhbHVlLCBvdXRGYWxzZVZhbHVl
KSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
