<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc3RyaW5nIik7
DQogICAgU3RyaW5nIGluVHJ1ZVZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
dmFsdWUudHJ1ZS5pbnB1dCIpOw0KICAgIFN0cmluZyBpbkZhbHNlVmFsdWUgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKGN1cnNvciwgIiR2YWx1ZS5mYWxzZS5pbnB1dCIpOw0KICAgIFN0cmluZyBvdXRU
cnVlVmFsdWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiR2YWx1ZS50cnVlLm91dHB1
dCIpOw0KICAgIFN0cmluZyBvdXRGYWxzZVZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJz
b3IsICIkdmFsdWUuZmFsc2Uub3V0cHV0Iik7DQoNCiAgICBpZiAoaW5TdHJpbmcgIT0gbnVsbCkg
SURhdGFVdGlsLnB1dChjdXJzb3IsICAiJHN0cmluZyIsIEJvb2xlYW5IZWxwZXIuZm9ybWF0KGlu
U3RyaW5nLCBpblRydWVWYWx1ZSwgaW5GYWxzZVZhbHVlLCBvdXRUcnVlVmFsdWUsIG91dEZhbHNl
VmFsdWUpKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
