<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQp0cnkgew0KICAgIFN0
cmluZyBpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHN0cmluZyIpOw0K
ICAgIFN0cmluZyBpblRydWVWYWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHZh
bHVlLnRydWUuaW5wdXQiKTsNCiAgICBTdHJpbmcgaW5GYWxzZVZhbHVlID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjdXJzb3IsICIkdmFsdWUuZmFsc2UuaW5wdXQiKTsNCiAgICBTdHJpbmcgb3V0VHJ1
ZVZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkdmFsdWUudHJ1ZS5vdXRwdXQi
KTsNCiAgICBTdHJpbmcgb3V0RmFsc2VWYWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJHZhbHVlLmZhbHNlLm91dHB1dCIpOw0KICAgIA0KICAgIGlmIChpblN0cmluZyAhPSBudWxs
KSBJRGF0YVV0aWwucHV0KGN1cnNvciwgICIkc3RyaW5nIiwgQm9vbGVhbkhlbHBlci5mb3JtYXQo
aW5TdHJpbmcsIGluVHJ1ZVZhbHVlLCBpbkZhbHNlVmFsdWUsIG91dFRydWVWYWx1ZSwgb3V0RmFs
c2VWYWx1ZSkpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ0KCQ==</value>
</Values>
