<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGR4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZHVyYXRpb24ueCIpOw0K
ICAgIFN0cmluZyBkeSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGR1cmF0aW9uLnki
KTsNCiAgICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
cGF0dGVybi5pbnB1dCIpOw0KICAgIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsNCg0KICAgIElEYXRhVXRpbC5wdXQoY3Vy
c29yLCAiJGR1cmF0aW9uIiwgYWRkKGluUGF0dGVybiwgb3V0UGF0dGVybiwgZHgsIGR5KSk7DQp9
IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
