<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGR4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZHVyYXRpb24ueCIpOw0K
ICAgIFN0cmluZyBkeSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGR1cmF0aW9uLnki
KTsNCiAgICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
cGF0dGVybi5pbnB1dCIpOw0KICAgIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsNCg0KICAgIFN0cmluZyByZXN1bHQgPSBE
dXJhdGlvbkhlbHBlci5lbWl0KER1cmF0aW9uSGVscGVyLmFkZChEdXJhdGlvbkhlbHBlci5wYXJz
ZShkeCwgaW5QYXR0ZXJuKSwgRHVyYXRpb25IZWxwZXIucGFyc2UoZHksIGluUGF0dGVybikpLCBv
dXRQYXR0ZXJuKTsNCiAgICANCiAgICBpZiAocmVzdWx0ICE9IG51bGwpIElEYXRhVXRpbC5wdXQo
Y3Vyc29yLCAiJGR1cmF0aW9uIiwgcmVzdWx0KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRl
c3Ryb3koKTsNCn0=</value>
</Values>
