<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">match</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsUGF0dGVybiA9IElE
YXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xl
YW4uY2xhc3MsIElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkbGl0ZXJhbD8iLCBC
b29sZWFuLmNsYXNzLCBmYWxzZSkpOwoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJG1h
dGNoPyIsIFN0cmluZ0hlbHBlci5tYXRjaChzdHJpbmcsIHBhdHRlcm4sIGxpdGVyYWxQYXR0ZXJu
KSwgU3RyaW5nLmNsYXNzKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=
</value>
</Values>
