<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">callstack</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
TGlzdDxOU1NlcnZpY2U+IHN0YWNrID0gU2VydmljZUhlbHBlci5nZXRDYWxsU3RhY2soKTsNCiAg
ICBpZiAoc3RhY2suc2l6ZSgpID4gMCkgc3RhY2sucmVtb3ZlKHN0YWNrLnNpemUoKSAtIDEpOyAv
LyByZW1vdmUgY2FsbCB0byB0aGlzIHNlcnZpY2UKCiAgICBTdHJpbmcgY2FsbGVyID0gIiI7CiAg
ICBpZiAoc3RhY2suc2l6ZSgpID4gMSkgewogICAgICAgIE5TU2VydmljZSBzZXJ2aWNlID0gc3Rh
Y2suZ2V0KHN0YWNrLnNpemUoKSAtIDIpOwogICAgICAgIGlmIChzZXJ2aWNlICE9IG51bGwpIGNh
bGxlciA9IE9iamVjdEhlbHBlci5zdHJpbmdpZnkoc2VydmljZSk7CiAgICB9CgogICAgSURhdGFV
dGlsLnB1dChjdXJzb3IsICIkY2FsbHN0YWNrIiwgQ29sbGVjdGlvbkhlbHBlci5hcnJheWlmeShD
b2xsZWN0aW9uSGVscGVyLnN0cmluZ2lmeShzdGFjayksIFN0cmluZy5jbGFzcykpOwogICAgSURh
dGFVdGlsLnB1dChjdXJzb3IsICIkY2FsbGVycyIsIEl0ZXJhYmxlSGVscGVyLmpvaW4oc3RhY2ss
ICIgXHUyMTkyICIpKTsKICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNhbGxlciIsIGNhbGxl
cik7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
