<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">callstack</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
TGlzdDxOU1NlcnZpY2U+IHN0YWNrID0gU2VydmljZUhlbHBlci5nZXRDYWxsU3RhY2soKTsNCiAg
ICBpZiAoc3RhY2suc2l6ZSgpID4gMCkgc3RhY2sucmVtb3ZlKHN0YWNrLnNpemUoKSAtIDEpOyAv
LyByZW1vdmUgY2FsbCB0byB0aGlzIHNlcnZpY2UKCiAgICBTdHJpbmcgY2FsbGVyID0gIiIsIGlu
aXRpYXRvciA9ICIiOwogICAgaWYgKHN0YWNrLnNpemUoKSA+IDEpIHsKICAgICAgICBOU1NlcnZp
Y2UgY2FsbGluZ1NlcnZpY2UgPSBzdGFjay5nZXQoc3RhY2suc2l6ZSgpIC0gMik7CiAgICAgICAg
aWYgKGNhbGxpbmdTZXJ2aWNlICE9IG51bGwpIGNhbGxlciA9IE9iamVjdEhlbHBlci5zdHJpbmdp
ZnkoY2FsbGluZ1NlcnZpY2UpOwoKICAgICAgICBOU1NlcnZpY2UgaW5pdGlhdGluZ1NlcnZpY2Ug
PSBzdGFjay5nZXQoMCk7CiAgICAgICAgaWYgKGluaXRpYXRpbmdTZXJ2aWNlICE9IG51bGwpIGlu
aXRpYXRvciA9IE9iamVjdEhlbHBlci5zdHJpbmdpZnkoaW5pdGlhdGluZ1NlcnZpY2UpOwogICAg
fQoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkY2FsbHN0YWNrIiwgQ29sbGVjdGlvbkhl
bHBlci5hcnJheWlmeShDb2xsZWN0aW9uSGVscGVyLnN0cmluZ2lmeShzdGFjayksIFN0cmluZy5j
bGFzcykpOwogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRjYWxsZXJzIiwgSXRlcmFibGVI
ZWxwZXIuam9pbihzdGFjaywgIiBcdTIxOTIgIikpOwogICAgSURhdGFIZWxwZXIucHV0KGN1cnNv
ciwgIiRjYWxsZXIiLCBjYWxsZXIpOw0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkY2Fs
bGVyLmluaXRpYXRvciIsIGluaXRpYXRvcik7Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ry
b3koKTsNCn0=</value>
</Values>
