<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZS5zb3VyY2UiLCBT
dHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyB0YXJnZXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJGZpbGUudGFyZ2V0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFzcyk7DQoNCiAgICBGaWxlSGVs
cGVyLmNvcHkoc291cmNlLCB0YXJnZXQsIG1vZGUgPT0gbnVsbCB8fCBtb2RlLmVxdWFsc0lnbm9y
ZUNhc2UoImFwcGVuZCIpKTsNCn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRp
b25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0K
fQ==</value>
</Values>
