<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">difference</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0W10gbGlzdFggPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGxpc3QueCIsIE9iamVjdFtd
LmNsYXNzKTsKICAgIE9iamVjdFtdIGxpc3RZID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRs
aXN0LnkiLCBPYmplY3RbXS5jbGFzcyk7CgogICAgaWYgKGxpc3RYICE9IG51bGwpIHsKICAgICAg
ICBPYmplY3RbXSByZXN1bHQgPSBBcnJheUhlbHBlci5kaWZmZXJlbmNlKGxpc3RYLCBsaXN0WSk7
CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRsaXN0IiwgcmVzdWx0KTsKICAgICAg
ICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QubGVuZ3RoIiwgcmVzdWx0Lmxlbmd0aCwg
U3RyaW5nLmNsYXNzKTsKICAgIH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNv
ciwgIiRsaXN0Lmxlbmd0aCIsICIwIik7CiAgICB9Cgp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRl
c3Ryb3koKTsKfQ==</value>
</Values>
