<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compare</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGUxID0gSURhdGFIZWxwZXIuZmlyc3QoY3Vyc29yLCBTdHJpbmcuY2xhc3MsICIk
ZGF0ZXRpbWUuZmlyc3QiLCAiJGRhdGV0aW1lLngiKTsNCiAgICBTdHJpbmcgZGF0ZTIgPSBJRGF0
YUhlbHBlci5maXJzdChjdXJzb3IsIFN0cmluZy5jbGFzcywgIiRkYXRldGltZS5zZWNvbmQiLCAi
JGRhdGV0aW1lLnkiKTsNCiAgICBTdHJpbmcgcGF0dGVybjEgPSBJRGF0YUhlbHBlci5maXJzdChj
dXJzb3IsIFN0cmluZy5jbGFzcywgIiRkYXRldGltZS5maXJzdC5wYXR0ZXJuIiwgIiRwYXR0ZXJu
LngiLCAiJHBhdHRlcm4iKTsNCiAgICBTdHJpbmcgcGF0dGVybjIgPSBJRGF0YUhlbHBlci5maXJz
dChjdXJzb3IsIFN0cmluZy5jbGFzcywgIiRkYXRldGltZS5zZWNvbmQucGF0dGVybiIsICIkcGF0
dGVybi55IiwgIiRwYXR0ZXJuIik7DQoNCiAgICBpbnQgY29tcGFyaXNvbiA9IERhdGVUaW1lSGVs
cGVyLmNvbXBhcmUoZGF0ZTEsIHBhdHRlcm4xLCBkYXRlMiwgcGF0dGVybjIpOw0KDQogICAgSURh
dGFIZWxwZXIucHV0KGN1cnNvciwgIiRiZWZvcmU/IiwgY29tcGFyaXNvbiA8IDAsIFN0cmluZy5j
bGFzcyk7DQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRlcXVhbD8iLCBjb21wYXJpc29u
ID09IDAsIFN0cmluZy5jbGFzcyk7DQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRhZnRl
cj8iLCBjb21wYXJpc29uID4gMCwgU3RyaW5nLmNsYXNzKTsNCn0gZmluYWxseSB7DQogICAgY3Vy
c29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
