<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listify</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGtleSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIka2V5IiwgU3RyaW5nLmNsYXNzKTsK
ICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzY29wZSIsIElEYXRh
LmNsYXNzKTsKICAgIGJvb2xlYW4gc2NvcGVkID0gc2NvcGUgIT0gbnVsbDsKCiAgICBpZiAoc2Nv
cGVkKSB7CiAgICAgICAgc2NvcGUgPSBJRGF0YUhlbHBlci5kdXBsaWNhdGUoc2NvcGUpOwogICAg
fSBlbHNlIHsKICAgICAgICBzY29wZSA9IHBpcGVsaW5lOwogICAgfQoKICAgIHNjb3BlID0gSURh
dGFIZWxwZXIuYXJyYXlpZnkoc2NvcGUsIGtleSk7CgogICAgaWYgKHNjb3BlZCkgSURhdGFIZWxw
ZXIucHV0KGN1cnNvciwgIiRzY29wZSIsIHNjb3BlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
