<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">self</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZSIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJGRhdGV0aW1lLnBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgSURhdGEgdGltZXpv
bmUgPSBUaW1lWm9uZUhlbHBlci50b0lEYXRhKFRpbWVab25lSGVscGVyLnNlbGYoKSwgZGF0ZXRp
bWUsIHBhdHRlcm4pOw0KDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiR0aW1lem9uZSIs
IHRpbWV6b25lLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9
</value>
</Values>
