<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IG9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb2JqZWN0Iik7DQogICAg
Q2hhcnNldCBjaGFyc2V0ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRlbmNv
ZGluZyIsIENoYXJzZXQuY2xhc3MsIENoYXJzZXRIZWxwZXIuREVGQVVMVF9DSEFSU0VUKTsNCg0K
ICAgIElucHV0U3RyZWFtIHN0cmVhbSA9IElucHV0U3RyZWFtSGVscGVyLm5vcm1hbGl6ZShvYmpl
Y3QsIGNoYXJzZXQpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyZWFtIiwgc3Ry
ZWFtLCBmYWxzZSk7DQogICAgaWYgKHN0cmVhbSAhPSBudWxsICYmIG9iamVjdCBpbnN0YW5jZW9m
IFN0cmluZykgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRlbmNvZGluZyIsIGNoYXJzZXQubmFt
ZSgpKTsKfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
