<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">size</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGRpcmVjdG9yeSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZGlyZWN0b3J5IiwgU3Ry
aW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVs
dChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CgogICAgQmlnSW50
ZWdlciB0b3RhbFNpemUgPSBEaXJlY3RvcnlIZWxwZXIuc2l6ZShkaXJlY3RvcnksIHJlY3Vyc2Up
OwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc2l6ZSIsIHRvdGFsU2l6ZSwgU3RyaW5n
LmNsYXNzKTsKfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgewogICAgRXhjZXB0aW9uSGVscGVyLnJh
aXNlKGV4KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
