<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">size</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBkaXJlY3RvcnkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRpcmVjdG9yeSIsIEZpbGUu
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBCaWdJbnRlZ2Vy
IHRvdGFsU2l6ZSA9IERpcmVjdG9yeUhlbHBlci5zaXplKGRpcmVjdG9yeSwgcmVjdXJzZSk7Cgog
ICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzaXplIiwgdG90YWxTaXplLCBTdHJpbmcuY2xh
c3MpOwp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2Uo
ZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
