<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IG9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb2JqZWN0Iik7DQogICAg
aW50IHJhZGl4ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRyYWRpeCIsIElu
dGVnZXIuY2xhc3MsIEJpZ0ludGVnZXJIZWxwZXIuREVGQVVMVF9SQURJWCk7DQoKICAgIGlmIChv
YmplY3QgIT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyaW5n
IiwgQmlnSW50ZWdlckhlbHBlci5lbWl0KEJpZ0ludGVnZXJIZWxwZXIubm9ybWFsaXplKG9iamVj
dCksIHJhZGl4KSk7DQogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9
</value>
</Values>
