<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IG9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb2JqZWN0Iik7DQogICAg
aW50IHJhZGl4ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRyYWRpeCIsIElu
dGVnZXIuY2xhc3MsIEJpZ0ludGVnZXJIZWxwZXIuREVGQVVMVF9SQURJWCk7DQoKICAgIEJpZ0lu
dGVnZXIgcmVzdWx0ID0gQmlnSW50ZWdlckhlbHBlci5ub3JtYWxpemUob2JqZWN0LCByYWRpeCk7
Cg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyaW5nIiwgcmVzdWx0LCBTdHJpbmcu
Y2xhc3MsIGZhbHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
