<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">slice</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBpbnQgaW5kZXggPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29y
LCAiJGluZGV4IiwgSW50ZWdlci5jbGFzcywgMCk7DQogICAgaW50IGxlbmd0aCA9IElEYXRhSGVs
cGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkbGVuZ3RoIiwgSW50ZWdlci5jbGFzcywgc3RyaW5n
ID09IG51bGwgPyAwIDogKGluZGV4IDwgMCA/IC1zdHJpbmcubGVuZ3RoKCkgOiBzdHJpbmcubGVu
Z3RoKCkpKTsNCg0KICAgIGlmIChzdHJpbmcgIT0gbnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNv
ciwgIiRzdHJpbmciLCBTdHJpbmdIZWxwZXIuc2xpY2Uoc3RyaW5nLCBpbmRleCwgbGVuZ3RoKSk7
DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
