<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">slice</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgaW5kZXggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRpbmRleCIpOwogIFN0cmlu
ZyBsZW5ndGggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRsZW5ndGgiKTsKCiAgaW50
IGl4ID0gaW5kZXggPT0gbnVsbCA/IDAgOiBJbnRlZ2VyLnBhcnNlSW50KGluZGV4KTsKICBpbnQg
bGVuID0gbGVuZ3RoID09IG51bGwgPyAoc3RyaW5nID09IG51bGwgPyAwIDogKGl4IDwgMCA/IC1z
dHJpbmcubGVuZ3RoKCkgOiBzdHJpbmcubGVuZ3RoKCkpKSA6IEludGVnZXIucGFyc2VJbnQobGVu
Z3RoKTsKCgogIGlmIChzdHJpbmcgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkc3Ry
aW5nIiwgU3RyaW5nSGVscGVyLnNsaWNlKHN0cmluZywgaXgsIGxlbikpOwp9IGZpbmFsbHkgewog
IGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
