<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">take</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIpOwog
ICAgaW50IGNvdW50ID0gSW50ZWdlckhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRjb3VudCIpKTsKCiAgICBpZiAobGlzdCAhPSBudWxsKSB7CiAgICAgICAgQXJyYXlT
cGxpdHRlciBzcGxpdHRlciA9IG5ldyBBcnJheVNwbGl0dGVyKGxpc3QsIGNvdW50KTsKICAgICAg
ICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRoZWFkIiwgc3BsaXR0ZXIuZ2V0SGVhZCgpKTsKICAg
ICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiR0YWlsIiwgc3BsaXR0ZXIuZ2V0VGFpbCgpKTsK
ICAgIH0KfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
