<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">take</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtdLmNs
YXNzKTsKICAgIGludCBjb3VudCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkY291bnQiLCBJ
bnRlZ2VyLmNsYXNzKTsKCiAgICBpZiAobGlzdCAhPSBudWxsKSB7CiAgICAgICAgQXJyYXlTcGxp
dHRlciBzcGxpdHRlciA9IG5ldyBBcnJheVNwbGl0dGVyKGxpc3QsIGNvdW50KTsKICAgICAgICBJ
RGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGhlYWQiLCBzcGxpdHRlci5nZXRIZWFkKCkpOwogICAg
ICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkdGFpbCIsIHNwbGl0dGVyLmdldFRhaWwoKSk7
CiAgICB9Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
