<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBpbnZvY2F0aW9ucyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkaW52b2NhdGlv
bnMiLCBJRGF0YVtdLmNsYXNzKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGNvbmN1cnJlbmN5ID0g
SURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjb25jdXJyZW5jeSIsIFN0cmluZy5jbGFzcyk7DQoN
CiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGludm9jYXRpb25zIiwgaW52b2tlKGludm9j
YXRpb25zLCBtb2RlLCBjb25jdXJyZW5jeSkpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVz
dHJveSgpOw0KfQ==</value>
</Values>
