<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">exists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7
DQogICAgU3RyaW5nIG5hbWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG5hbWUiLCBTdHJp
bmcuY2xhc3MpOwoKICAgIGlmIChpZCAhPSBudWxsKSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0
KGN1cnNvciwgIiRleGlzdHM/IiwgU2NoZWR1bGVIZWxwZXIuZXhpc3RzKGlkKSwgU3RyaW5nLmNs
YXNzKTsNCiAgICB9IGVsc2UgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZXhp
c3RzPyIsIFNjaGVkdWxlSGVscGVyLmV4aXN0c0J5TmFtZShuYW1lKSwgU3RyaW5nLmNsYXNzKTsK
ICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
