<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">exists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkaWQiKTsNCiAgICBTdHJp
bmcgbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG5hbWUiKTsKCiAgICBpZiAo
aWQgIT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZXhpc3RzPyIs
IEJvb2xlYW5IZWxwZXIuZW1pdChTY2hlZHVsZUhlbHBlci5leGlzdHMoaWQpKSk7DQogICAgfSBl
bHNlIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGV4aXN0cz8iLCBCb29sZWFu
SGVscGVyLmVtaXQoU2NoZWR1bGVIZWxwZXIuZXhpc3RzQnlOYW1lKG5hbWUpKSk7CiAgICB9Cn0g
ZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
