<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkaWQiKTsNCiAgICBTdHJp
bmcgZGF0ZXRpbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkYXRldGltZSIpOw0K
ICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRp
bWUucGF0dGVybiIpOw0KDQogICAgSURhdGEgdGltZXpvbmUgPSBUaW1lWm9uZUhlbHBlci50b0lE
YXRhKFRpbWVab25lSGVscGVyLmdldChpZCksIGRhdGV0aW1lLCBwYXR0ZXJuKTsNCg0KICAgIGlm
ICh0aW1lem9uZSAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiR0aW1lem9uZSIsIHRp
bWV6b25lKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
