<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7
DQogICAgU3RyaW5nIGRhdGV0aW1lID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGlt
ZSIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJGRhdGV0aW1lLnBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgSURhdGEg
dGltZXpvbmUgPSBUaW1lWm9uZUhlbHBlci50b0lEYXRhKFRpbWVab25lSGVscGVyLmdldChpZCks
IGRhdGV0aW1lLCBwYXR0ZXJuKTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkdGlt
ZXpvbmUiLCB0aW1lem9uZSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJv
eSgpOw0KfQ==</value>
</Values>
