<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatenate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkYXRlIik7DQogICAg
U3RyaW5nIHRpbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiR0aW1lIik7DQogICAg
DQogICAgU3RyaW5nIGRhdGV0aW1lID0gRGF0ZVRpbWVIZWxwZXIuZW1pdChEYXRlVGltZUhlbHBl
ci5jb25jYXRlbmF0ZShEYXRlVGltZUhlbHBlci5wYXJzZShkYXRlLCAiZGF0ZSIpLCBEYXRlVGlt
ZUhlbHBlci5wYXJzZSh0aW1lLCAidGltZSIpKSk7DQoNCiAgICBpZiAoZGF0ZXRpbWUgIT0gbnVs
bCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZGF0ZXRpbWUiLCBkYXRldGltZSk7DQp9IGZpbmFs
bHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
