<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">translate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG91dHB1dEtleSA9ICIkdHJhbnNsYXRpb24ucmVzdWx0cyI7CiAgICBJRGF0YSBvcGVyYW5k
cyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkdHJhbnNsYXRpb24ub3BlcmFuZHMiLCBJRGF0
YS5jbGFzcyk7CiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkgewogICAgICAgIG9wZXJhbmRzID0g
SURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRvcGVyYW5kcyIsIElEYXRhLmNsYXNzKTsKICAgICAg
ICBvdXRwdXRLZXkgPSAiJHJlc3VsdHMiOwogICAgfQogICAgSURhdGEgdHJhbnNsYXRpb25zID0g
SURhdGFIZWxwZXIuZmlyc3QoY3Vyc29yLCBJRGF0YS5jbGFzcywgIiR0cmFuc2xhdGlvbi52YWx1
ZXMiLCAiJHRyYW5zbGF0aW9ucyIpOwogICAgYm9vbGVhbiBleGNsdWRlID0gSURhdGFIZWxwZXIu
Z2V0T3JEZWZhdWx0KGN1cnNvciwgIiR0cmFuc2xhdGlvbi5leGNsdWRlPyIsIEJvb2xlYW4uY2xh
c3MsIGZhbHNlKTsKICAgIGJvb2xlYW4gcmV2ZXJzZSA9IElEYXRhSGVscGVyLmZpcnN0T3JEZWZh
dWx0KGN1cnNvciwgQm9vbGVhbi5jbGFzcywgZmFsc2UsICIkdHJhbnNsYXRpb24ucmV2ZXJzZT8i
LCAiJHJldmVyc2U/Iik7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgb3V0cHV0S2V5LCBU
cmFuc2Zvcm1lci50cmFuc2Zvcm0ob3BlcmFuZHMsIG5ldyBUcmFuc2xhdG9yKHRyYW5zbGF0aW9u
cywgZXhjbHVkZSwgcmV2ZXJzZSkpLCBmYWxzZSk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVz
dHJveSgpOwp9</value>
</Values>
