<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">squeeze</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNxdWVlemUuaW5wdXQi
LCBJRGF0YS5jbGFzcyk7CiAgICBpZiAoZG9jdW1lbnQgPT0gbnVsbCkgewogICAgICAgIC8vIHN1
cHBvcnQgb2xkIHZlcnNpb24gb2Ygc3F1ZWV6ZSBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkK
ICAgICAgICBTdHJpbmcgc3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmci
LCBTdHJpbmcuY2xhc3MpOw0KICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmlu
ZyIsIFN0cmluZ0hlbHBlci5jb25kZW5zZShzdHJpbmcpKTsNCiAgICB9IGVsc2UgewogICAgICAg
IElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3F1ZWV6ZS5vdXRwdXQiLCBJRGF0YUhlbHBlci5z
cXVlZXplKGRvY3VtZW50LCB0cnVlKSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1
cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
