<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
Z1tdIGR1cmF0aW9ucyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkZHVyYXRp
b25zIik7CiAgU3RyaW5nIGRhdGV0aW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
ZGF0ZXRpbWUiKTsKICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJz
b3IsICIkcGF0dGVybi5pbnB1dCIpOwogIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsKICAKICBJRGF0YVV0aWwucHV0KGN1
cnNvciwgIiRkdXJhdGlvbnMiLCBmb3JtYXQoZHVyYXRpb25zLCBpblBhdHRlcm4sIG91dFBhdHRl
cm4sIGRhdGV0aW1lKSk7Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
