<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">round</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
QmlnRGVjaW1hbCBkZWNpbWFsID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkZWNpbWFsIiwg
QmlnRGVjaW1hbC5jbGFzcyk7DQogICAgaW50IHByZWNpc2lvbiA9IElEYXRhSGVscGVyLmdldE9y
RGVmYXVsdChjdXJzb3IsICIkcHJlY2lzaW9uIiwgSW50ZWdlci5jbGFzcywgLTEpOw0KICAgIFJv
dW5kaW5nTW9kZSByb3VuZGluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcm91bmRpbmci
LCBSb3VuZGluZ01vZGUuY2xhc3MpOw0KCiAgICBCaWdEZWNpbWFsIHJlc3VsdCA9IEJpZ0RlY2lt
YWxIZWxwZXIucm91bmQoZGVjaW1hbCwgcHJlY2lzaW9uLCByb3VuZGluZyk7Cg0KICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHJlc3VsdCwgU3RyaW5nLmNsYXNzLCBmYWxz
ZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
