<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">round</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRlY2ltYWwgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWNpbWFsIik7
DQogICAgU3RyaW5nIHByZWNpc2lvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBy
ZWNpc2lvbiIpOw0KICAgIFN0cmluZyByb3VuZGluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vy
c29yLCAiJHJvdW5kaW5nIik7DQoKICAgIFN0cmluZyByZXN1bHQgPSBCaWdEZWNpbWFsSGVscGVy
LmVtaXQoQmlnRGVjaW1hbEhlbHBlci5yb3VuZChCaWdEZWNpbWFsSGVscGVyLnBhcnNlKGRlY2lt
YWwpLCBwcmVjaXNpb24sIHJvdW5kaW5nKSk7Cg0KICAgIGlmIChyZXN1bHQgIT0gbnVsbCkgSURh
dGFVdGlsLnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHJlc3VsdCk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
