<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">find</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsUGF0dGVybiA9IElE
YXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xl
YW4uY2xhc3MsIElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkbGl0ZXJhbD8iLCBC
b29sZWFuLmNsYXNzLCBmYWxzZSkpOwoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGZv
dW5kPyIsIFN0cmluZ0hlbHBlci5maW5kKHN0cmluZywgcGF0dGVybiwgbGl0ZXJhbFBhdHRlcm4p
LCBTdHJpbmcuY2xhc3MpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==
</value>
</Values>
