<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">find</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURhdGFIZWxw
ZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRsaXRlcmFsPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNl
KTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZm91bmQ/IiwgU3RyaW5nSGVscGVy
LmZpbmQoc3RyaW5nLCBwYXR0ZXJuLCBsaXRlcmFsKSwgU3RyaW5nLmNsYXNzKTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
