<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">match</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBTdHJpbmcuY2xh
c3MpOw0KICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRwYXR0
ZXJuIiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRhSGVscGVyLmZpcnN0
T3JEZWZhdWx0KGN1cnNvciwgU3RyaW5nLmNsYXNzLCAicmVndWxhciBleHByZXNzaW9uIiwgIiRw
YXR0ZXJuLm1vZGUiLCAiJG1vZGUiKTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIk
bWF0Y2g/IiwgRmlsZUhlbHBlci5tYXRjaChmaWxlLCBwYXR0ZXJuLCBtb2RlLmVxdWFsc0lnbm9y
ZUNhc2UoInJlZ3VsYXIgZXhwcmVzc2lvbiIpIHx8IG1vZGUuZXF1YWxzSWdub3JlQ2FzZSgicmVn
ZXgiKSksIFN0cmluZy5jbGFzcyk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
