<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">match</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBTdHJpbmcuY2xh
c3MpOw0KICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRwYXR0
ZXJuIiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFzcyk7DQoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vy
c29yLCAiJG1hdGNoPyIsIEZpbGVIZWxwZXIubWF0Y2goZmlsZSwgcGF0dGVybiwgbW9kZSA9PSBu
dWxsIHx8IG1vZGUuZXF1YWxzSWdub3JlQ2FzZSgicmVndWxhciBleHByZXNzaW9uIikgIHx8IG1v
ZGUuZXF1YWxzSWdub3JlQ2FzZSgicmVnZXgiKSksIFN0cmluZy5jbGFzcyk7DQp9IGZpbmFsbHkg
ew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
