<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgY2xhc3NOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkY2xhc3MiKTsKCiAg
aWYgKHN0cmluZyAhPSBudWxsKSB7CiAgICBqYXZhLm1hdGguQmlnRGVjaW1hbCBvYmplY3QgPSBw
YXJzZShzdHJpbmcpOwogICAgaWYgKGNsYXNzTmFtZSA9PSBudWxsIHx8IGNsYXNzTmFtZS5lcXVh
bHMoImphdmEubWF0aC5CaWdEZWNpbWFsIikpIHsKICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3Is
ICIkb2JqZWN0Iiwgb2JqZWN0KTsKICAgIH0gZWxzZSBpZiAoY2xhc3NOYW1lLmVxdWFscygiamF2
YS5sYW5nLkZsb2F0IikpIHsKICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkb2JqZWN0Iiwg
b2JqZWN0LmZsb2F0VmFsdWUoKSk7CiAgICB9IGVsc2UgaWYgKGNsYXNzTmFtZS5lcXVhbHMoImph
dmEubGFuZy5Eb3VibGUiKSkgewogICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRvYmplY3Qi
LCBvYmplY3QuZG91YmxlVmFsdWUoKSk7CiAgICB9CiAgfQp9IGZpbmFsbHkgewogIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
