<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">split</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG91dHB1dFBhcmFtZXRlck5hbWUgPSAiJHNwbGl0LnJlc3VsdHMiOwogICAgSURhdGEgb3Bl
cmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNwbGl0Lm9wZXJhbmRzIiwgSURhdGEu
Y2xhc3MpOwogICAgaWYgKG9wZXJhbmRzID09IG51bGwpIHsKICAgICAgICAvLyBzdXBwb3J0ICRv
cGVyYW5kcyBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkKICAgICAgICBvcGVyYW5kcyA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkb3BlcmFuZHMiLCBJRGF0YS5jbGFzcyk7CiAgICAgICAg
b3V0cHV0UGFyYW1ldGVyTmFtZSA9ICIkcmVzdWx0cyI7CiAgICB9CiAgICBTdHJpbmcgcGF0dGVy
biA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNvciwgU3RyaW5nLmNsYXNzLCAiJHNwbGl0LnBhdHRl
cm4iLCAiJHBhdHRlcm4iKTsKICAgIGJvb2xlYW4gbGl0ZXJhbCA9IElEYXRhSGVscGVyLmZpcnN0
T3JEZWZhdWx0KGN1cnNvciwgQm9vbGVhbi5jbGFzcywgZmFsc2UsICIkc3BsaXQucGF0dGVybi5s
aXRlcmFsPyIsICIkcGF0dGVybi5saXRlcmFsPyIsICIkbGl0ZXJhbD8iKTsKCiAgICBpZiAob3Bl
cmFuZHMgPT0gbnVsbCkgewogICAgICAgIC8vIHN1cHBvcnQgJHN0cmluZyBmb3IgYmFja3dhcmRz
LWNvbXBhdGliaWxpdHkKICAgICAgICBTdHJpbmcgc3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1
cnNvciwgIiRzdHJpbmciLCBTdHJpbmcuY2xhc3MpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChj
dXJzb3IsICIkbGlzdCIsIFN0cmluZ0hlbHBlci5zcGxpdChzdHJpbmcsIHBhdHRlcm4sIGxpdGVy
YWwpLCBmYWxzZSk7CiAgICB9IGVsc2UgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
IG91dHB1dFBhcmFtZXRlck5hbWUsIFRyYW5zZm9ybWVyLnRyYW5zZm9ybShvcGVyYW5kcywgbmV3
IFNwbGl0dGVyKHBhdHRlcm4sIGxpdGVyYWwpKSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgewog
ICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
