<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">split</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURh
dGEuY2xhc3MpOwogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAi
JHBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KICAgIGJvb2xlYW4gbGl0ZXJhbCA9IElEYXRhSGVs
cGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xlYW4uY2xh
c3MsIElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkbGl0ZXJhbD8iLCBCb29sZWFu
LmNsYXNzLCBmYWxzZSkpOwoKICAgIGlmIChvcGVyYW5kcyAhPSBudWxsKSB7CiAgICAgICAgSURh
dGFIZWxwZXIucHV0KGN1cnNvciwgIiRyZXN1bHRzIiwgSURhdGFIZWxwZXIudHJhbnNmb3JtKG9w
ZXJhbmRzLCBuZXcgU3BsaXR0ZXIocGF0dGVybiwgbGl0ZXJhbCkpLCBmYWxzZSk7CiAgICB9IGVs
c2UgewogICAgICAgIFN0cmluZyBzdHJpbmcgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0
cmluZyIsIFN0cmluZy5jbGFzcyk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRs
aXN0IiwgU3RyaW5nSGVscGVyLnNwbGl0KHN0cmluZywgcGF0dGVybiwgbGl0ZXJhbCksIGZhbHNl
KTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
