<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">split</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURhdGFIZWxw
ZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRsaXRlcmFsPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNl
KTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkbGlzdCIsIFN0cmluZ0hlbHBlci5z
cGxpdChzdHJpbmcsIHBhdHRlcm4sIGxpdGVyYWwpLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
