<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">flatten</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGRvY3VtZW50Iik7CiAg
ICBTdHJpbmdbXSBrZXlzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRrZXlz
Iik7CiAgICBib29sZWFuIGluY2x1ZGVOdWxscyA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFV
dGlsLmdldFN0cmluZyhjdXJzb3IsICIkbnVsbHM/IikpOwoKICAgIC8vIHN1cHBvcnQgJGtleSBm
b3IgYmFja3dhcmRzIGNvbXBhdGliaWxpdHkKICAgIGlmIChrZXlzID09IG51bGwpIHsKICAgICAg
ICBTdHJpbmcga2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIka2V5Iik7CiAgICAg
ICAgaWYgKGtleSAhPSBudWxsKSBrZXlzID0gbmV3IFN0cmluZ1tdIHsga2V5IH07CiAgICB9Cgog
ICAgT2JqZWN0W10gdmFsdWVzID0gSURhdGFIZWxwZXIuZmxhdHRlbihkb2N1bWVudCwgaW5jbHVk
ZU51bGxzLCBrZXlzKTsKCiAgICBpZiAodmFsdWVzICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vy
c29yLCAiJHZhbHVlcyIsIHZhbHVlcyk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgp
Owp9</value>
</Values>
