<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unprefix</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIFN0cmluZyBwcmVmaXggPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAi
JHByZWZpeCIsIFN0cmluZy5jbGFzcyk7CiAgICBib29sZWFuIHJlY3Vyc2UgPSBJRGF0YUhlbHBl
ci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJHJlY3Vyc2U/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2Up
Ow0KICAgIFRyYW5zZm9ybWVyTW9kZSBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRt
b2RlIiwgVHJhbnNmb3JtZXJNb2RlLmNsYXNzKTsKCiAgICBpZiAocHJlZml4ICE9IG51bGwpIElE
YXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBJRGF0YUhlbHBlci51bnByZWZpeChk
b2N1bWVudCwgcHJlZml4LCBtb2RlLCByZWN1cnNlKSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAg
ICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
