<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">resolve</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbmFtZSIpOwogIGphdmEubmV0
LkluZXRBZGRyZXNzIGFkZHJlc3MgPSBqYXZhLm5ldC5JbmV0QWRkcmVzcy5nZXRCeU5hbWUobmFt
ZSk7CiAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZG9tYWluIiwgYWRkcmVzcy5nZXRDYW5vbmlj
YWxIb3N0TmFtZSgpLnRvTG93ZXJDYXNlKCkpOwogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGhv
c3QiLCBhZGRyZXNzLmdldEhvc3ROYW1lKCkudG9Mb3dlckNhc2UoKSk7CiAgSURhdGFVdGlsLnB1
dChjdXJzb3IsICIkaXAiLCBhZGRyZXNzLmdldEhvc3RBZGRyZXNzKCkudG9Mb3dlckNhc2UoKSk7
Cn0gY2F0Y2ggKGphdmEubmV0LlVua25vd25Ib3N0RXhjZXB0aW9uIGV4KSB7CiAgdHVuZHJhLmV4
Y2VwdGlvbi5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
