<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">capture</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIFN0
cmluZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsNCiAg
U3RyaW5nIHBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7
DQogIGJvb2xlYW4gbGl0ZXJhbCA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkbGl0ZXJhbD8iKSk7DQoNCiAgSURhdGFbXSBjYXB0dXJlcyA9IGNhcHR1
cmUoc3RyaW5nLCBwYXR0ZXJuKTsNCg0KICBpZiAoY2FwdHVyZXMgIT0gbnVsbCAmJiBjYXB0dXJl
cy5sZW5ndGggPiAwKSB7DQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY2FwdHVyZWQ/Iiwg
InRydWUiKTsNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRjYXB0dXJlcyIsIGNhcHR1cmVz
KTsNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRjYXB0dXJlcy5sZW5ndGgiLCAiIiArIGNh
cHR1cmVzLmxlbmd0aCk7DQogIH0gZWxzZSB7DQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIk
Y2FwdHVyZWQ/IiwgImZhbHNlIik7DQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY2FwdHVy
ZXMubGVuZ3RoIiwgIjAiKTsNCiAgfQ0KfSBmaW5hbGx5IHsNCiAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0NCg==</value>
</Values>
