<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">capture</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4iKTsKICBi
b29sZWFuIGxpdGVyYWwgPSB0dW5kcmEuYm9vbC5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRsaXRlcmFsPyIpKTsKCiAgSURhdGFbXSBjYXB0dXJlcyA9IGNhcHR1cmUoc3RyaW5n
LCBwYXR0ZXJuKTsKCiAgaWYgKGNhcHR1cmVzICE9IG51bGwgJiYgY2FwdHVyZXMubGVuZ3RoID4g
MCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY2FwdHVyZXMiLCBjYXB0dXJlcyk7Cn0gZmluYWxs
eSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
