<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">capture</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4iKTsKICBi
b29sZWFuIGxpdGVyYWwgPSB0dW5kcmEuYm9vbC5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRsaXRlcmFsPyIpKTsKCiAgSURhdGFbXSBjYXB0dXJlcyA9IGNhcHR1cmUoc3RyaW5n
LCBwYXR0ZXJuKTsKCiAgaWYgKGNhcHR1cmVzICE9IG51bGwgJiYgY2FwdHVyZXMubGVuZ3RoID4g
MCkgewogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY2FwdHVyZWQ/IiwgInRydWUiKTsKICAg
IElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNhcHR1cmVzIiwgY2FwdHVyZXMpOwogICAgSURhdGFV
dGlsLnB1dChjdXJzb3IsICIkY2FwdHVyZXMubGVuZ3RoIiwgIiIgKyBjYXB0dXJlcy5sZW5ndGgp
OwogIH0gZWxzZSB7CiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRjYXB0dXJlZD8iLCAiZmFs
c2UiKTsKICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNhcHR1cmVzLmxlbmd0aCIsICIwIik7
CiAgfQp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
