<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
Ym9vbGVhbiBlbmFibGVkT25seSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIk
ZW5hYmxlZD8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7DQoKICAgIElEYXRhW10gbGlzdCA9IFBh
Y2thZ2VIZWxwZXIudG9JRGF0YUFycmF5KFBhY2thZ2VIZWxwZXIubGlzdChlbmFibGVkT25seSkp
Ow0KCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHBhY2thZ2VzIiwgbGlzdCk7DQogICAg
SURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRwYWNrYWdlcy5sZW5ndGgiLCBsaXN0Lmxlbmd0aCwg
U3RyaW5nLmNsYXNzKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
