<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsKICAgIENo
YXJzZXQgY2hhcnNldCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZW5jb2RpbmciLCBDaGFy
c2V0LmNsYXNzKTsKCiAgICBpZiAoY29udGVudCAhPSBudWxsKSB7CiAgICAgICAgSURhdGFIZWxw
ZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudCIsIElEYXRhSGpzb25QYXJzZXIuZ2V0SW5zdGFuY2Uo
KS5wYXJzZShJbnB1dFN0cmVhbUhlbHBlci5ub3JtYWxpemUoY29udGVudCwgY2hhcnNldCksIGNo
YXJzZXQpLCBmYWxzZSk7CiAgICB9Cn0gY2F0Y2ggKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNl
cHRpb25IZWxwZXIucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsK
fQ==</value>
</Values>
