<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">intersection</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJG9wZXJhbmRzIik7
CgogICAgLy8gc3VwcG9ydCAkbGlzdC54IGFuZCAkbGlzdC55IGlucHV0cyBmb3IgYmFja3dhcmRz
LWNvbXBhdGliaWxpdHkKICAgIGlmIChvcGVyYW5kcyA9PSBudWxsKSB7CiAgICAgICAgT2JqZWN0
W10gbGlzdFggPSBJRGF0YVV0aWwuZ2V0T2JqZWN0QXJyYXkoY3Vyc29yLCAiJGxpc3QueCIpOwog
ICAgICAgIE9iamVjdFtdIGxpc3RZID0gSURhdGFVdGlsLmdldE9iamVjdEFycmF5KGN1cnNvciwg
IiRsaXN0LnkiKTsKCiAgICAgICAgSURhdGFNYXAgbWFwID0gbmV3IElEYXRhTWFwKCk7CiAgICAg
ICAgaWYgKGxpc3RYICE9IG51bGwpIG1hcC5wdXQoIiRsaXN0LngiLCBsaXN0WCk7CiAgICAgICAg
aWYgKGxpc3RZICE9IG51bGwpIG1hcC5wdXQoIiRsaXN0LnkiLCBsaXN0WSk7CiAgICAgICAgb3Bl
cmFuZHMgPSBtYXA7CiAgICB9CgogICAgaWYgKElEYXRhSGVscGVyLnNpemUob3BlcmFuZHMpID4g
MCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkbGlzdCIsIEFycmF5SGVscGVyLmludGVyc2VjdChv
cGVyYW5kcykpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
