<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compare</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmcueCIpOw0KICAg
IFN0cmluZyB5ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc3RyaW5nLnkiKTsNCiAg
ICBTdHJpbmcgaW5zZW5zaXRpdmVDYXNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
aW5zZW5zaXRpdmUuY2FzZT8iKTsKICAgIGlmIChpbnNlbnNpdGl2ZUNhc2UgPT0gbnVsbCkgaW5z
ZW5zaXRpdmVDYXNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkY2FzZS5pbnNlbnNp
dGl2ZT8iKTsKICAgIFN0cmluZyBpbnNlbnNpdGl2ZVdoaXRlc3BhY2UgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKGN1cnNvciwgIiRpbnNlbnNpdGl2ZS53aGl0ZXNwYWNlPyIpOwoNCiAgICBpbnQgY29t
cGFyaXNvbiA9IFN0cmluZ0hlbHBlci5jb21wYXJlKHgsIHksIEJvb2xlYW5IZWxwZXIucGFyc2Uo
aW5zZW5zaXRpdmVDYXNlKSwgQm9vbGVhbkhlbHBlci5wYXJzZShpbnNlbnNpdGl2ZVdoaXRlc3Bh
Y2UpKTsNCg0KICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGJlZm9yZT8iLCBCb29sZWFuSGVs
cGVyLmVtaXQoY29tcGFyaXNvbiA8IDApKTsNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRl
cXVhbD8iLCBCb29sZWFuSGVscGVyLmVtaXQoY29tcGFyaXNvbiA9PSAwKSk7DQogICAgSURhdGFV
dGlsLnB1dChjdXJzb3IsICIkYWZ0ZXI/IiwgQm9vbGVhbkhlbHBlci5lbWl0KGNvbXBhcmlzb24g
PiAwKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
