<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">duration</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdGFydCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRhdGV0aW1lLnN0YXJ0Iik7
CiAgU3RyaW5nIGVuZCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRhdGV0aW1lLmVu
ZCIpOwogIFN0cmluZyBkYXRldGltZVBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNv
ciwgIiRkYXRldGltZS5wYXR0ZXJuIik7CiAgLy8gc3VwcG9ydCAkcGF0dGVybiB0byBiZSBiYWNr
d2FyZHMgY29tcGF0aWJsZQogIGlmIChkYXRldGltZVBhdHRlcm4gPT0gbnVsbCkgZGF0ZXRpbWVQ
YXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0dGVybiIpOwogIFN0cmlu
ZyBkdXJhdGlvblBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkdXJhdGlv
bi5wYXR0ZXJuIik7CgogIGlmIChzdGFydCAhPSBudWxsICYmIGVuZCAhPSBudWxsKSBJRGF0YVV0
aWwucHV0KGN1cnNvciwgIiRkdXJhdGlvbiIsIGR1cmF0aW9uKHN0YXJ0LCBlbmQsIGRhdGV0aW1l
UGF0dGVybiwgZHVyYXRpb25QYXR0ZXJuKSk7Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3ko
KTsKfQ==</value>
</Values>
