<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">reflect</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQp0cnkgew0KICAgIE9i
amVjdCBvYmplY3QgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIiRvYmplY3QiKTsNCiAgICBTdHJp
bmcga2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIka2V5Iik7DQogICAgaWYgKG9i
amVjdCA9PSBudWxsICYmIGtleSAhPSBudWxsKSBvYmplY3QgPSBJRGF0YUhlbHBlci5nZXQocGlw
ZWxpbmUsIGtleSk7DQoNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRpZCIsIEludGVnZXJI
ZWxwZXIuZW1pdChTeXN0ZW0uaWRlbnRpdHlIYXNoQ29kZShvYmplY3QpKSk7DQogICAgaWYgKG9i
amVjdCAhPSBudWxsKSB7DQogICAgICAgIENsYXNzIGtsYXNzID0gb2JqZWN0LmdldENsYXNzKCk7
DQogICAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNsYXNzIiwga2xhc3MuZ2V0TmFtZSgp
KTsNCiAgICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkYXJyYXk/IiwgQm9vbGVhbkhlbHBl
ci5lbWl0KGtsYXNzLmlzQXJyYXkoKSkpOw0KICAgICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwg
IiRwcmltaXRpdmU/IiwgQm9vbGVhbkhlbHBlci5lbWl0KHByaW1pdGl2ZShvYmplY3QpKSk7DQog
ICAgfQ0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
