<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">reflect</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0IG9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb2JqZWN0Iik7CiAgICBTdHJp
bmcga2V5ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRrZXkiLCBTdHJpbmcuY2xhc3MpOwog
ICAgaWYgKG9iamVjdCA9PSBudWxsICYmIGtleSAhPSBudWxsKSBvYmplY3QgPSBJRGF0YUhlbHBl
ci5nZXQocGlwZWxpbmUsIGtleSk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRpZCIs
IFN5c3RlbS5pZGVudGl0eUhhc2hDb2RlKG9iamVjdCksIFN0cmluZy5jbGFzcyk7CiAgICBpZiAo
b2JqZWN0ICE9IG51bGwpIHsKICAgICAgICBDbGFzcyBvYmplY3RDbGFzcyA9IG9iamVjdC5nZXRD
bGFzcygpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkY2xhc3MiLCBvYmplY3RD
bGFzcy5nZXROYW1lKCkpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkYXJyYXk/
Iiwgb2JqZWN0Q2xhc3MuaXNBcnJheSgpLCBTdHJpbmcuY2xhc3MpOwogICAgICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkcHJpbWl0aXZlPyIsIE9iamVjdEhlbHBlci5pc1ByaW1pdGl2ZShv
YmplY3QpLCBTdHJpbmcuY2xhc3MpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ry
b3koKTsKfQ==</value>
</Values>
