<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">legalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGxlZ2FsaXplLm9wZXJh
bmRzIiwgSURhdGEuY2xhc3MpOwoKICAgIGlmIChvcGVyYW5kcyA9PSBudWxsKSB7CiAgICAgICAg
U3RyaW5nIGlucHV0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcu
Y2xhc3MpOw0KICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmlu
Z0hlbHBlci5sZWdhbGl6ZShpbnB1dCksIGZhbHNlKTsNCiAgICB9IGVsc2UgewogICAgICAgIElE
YXRhSGVscGVyLnB1dChjdXJzb3IsICIkbGVnYWxpemUucmVzdWx0cyIsIFRyYW5zZm9ybWVyLnRy
YW5zZm9ybShvcGVyYW5kcywgbmV3IExlZ2FsaXplcihUcmFuc2Zvcm1lck1vZGUuVkFMVUVTLCB0
cnVlKSksIGZhbHNlKTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0K
fQ==</value>
</Values>
