<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gb2JqZWN0cyA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkb2Jq
ZWN0cyIpOw0KICAgIENoYXJzZXQgY2hhcnNldCA9IENoYXJzZXRIZWxwZXIubm9ybWFsaXplKElE
YXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGVuY29kaW5nIikpOw0KDQogICAgU3RyaW5nW10g
c3RyaW5ncyA9IFN0cmluZ0hlbHBlci5ub3JtYWxpemUob2JqZWN0cywgY2hhcnNldCk7DQoNCiAg
ICBpZiAoc3RyaW5ncyAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRzdHJpbmdzIiwg
c3RyaW5ncyk7DQp9IGNhdGNoKGphdmEuaW8uSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRp
b25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0K
fQ==</value>
</Values>
