<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gb2JqZWN0cyA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkb2Jq
ZWN0cyIpOw0KICAgIFN0cmluZyBlbmNvZGluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJGVuY29kaW5nIik7DQoNCiAgICBTdHJpbmdbXSBzdHJpbmdzID0gU3RyaW5nSGVscGVyLm5v
cm1hbGl6ZShvYmplY3RzLCBlbmNvZGluZyk7DQoNCiAgICBpZiAoc3RyaW5ncyAhPSBudWxsKSBJ
RGF0YVV0aWwucHV0KGN1cnNvciwgIiRzdHJpbmdzIiwgc3RyaW5ncyk7DQp9IGNhdGNoKGphdmEu
aW8uSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBm
aW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
