<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">minimum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gZGF0ZXRpbWVzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRk
YXRldGltZXMiKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vy
c29yLCAiJHBhdHRlcm4iKTsNCg0KICAgIFN0cmluZyBkYXRldGltZSA9IERhdGVUaW1lSGVscGVy
LmVtaXQoRGF0ZVRpbWVIZWxwZXIubWluaW11bShEYXRlVGltZUhlbHBlci5wYXJzZShkYXRldGlt
ZXMsIHBhdHRlcm4pKSwgcGF0dGVybik7DQoJDQogICAgaWYgKGRhdGV0aW1lICE9IG51bGwpIElE
YXRhVXRpbC5wdXQoY3Vyc29yLCAiJGRhdGV0aW1lIiwgZGF0ZXRpbWUpOw0KfSBmaW5hbGx5IHsN
CiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
