<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">minimum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gZGF0ZXRpbWVzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZXMi
LCBTdHJpbmdbXS5jbGFzcyk7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgU3RyaW5nIGRhdGV0aW1l
ID0gRGF0ZVRpbWVIZWxwZXIuZW1pdChEYXRlVGltZUhlbHBlci5taW5pbXVtKERhdGVUaW1lSGVs
cGVyLnBhcnNlKGRhdGV0aW1lcywgcGF0dGVybikpLCBwYXR0ZXJuKTsNCgkNCiAgICBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGRhdGV0aW1lIiwgZGF0ZXRpbWUsIGZhbHNlKTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
