<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgSURhdGEgc2NvcGUgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29y
LCAiJHBpcGVsaW5lIiwgSURhdGEuY2xhc3MsIHBpcGVsaW5lKTsNCiAgICBTdHJpbmcgZGVmYXVs
dFZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkZWZhdWx0IiwgU3RyaW5nLmNsYXNz
KTsNCiAgICBFbnVtU2V0PFN1YnN0aXR1dGlvblR5cGU+IG1vZGUgPSBTdWJzdGl0dXRpb25UeXBl
Lm5vcm1hbGl6ZShJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG1vZGUiLCBTdHJpbmcuY2xhc3Mp
KTsKDQogICAgaWYgKGxpc3QgIT0gbnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRsaXN0
IiwgU3Vic3RpdHV0aW9uSGVscGVyLnN1YnN0aXR1dGUobGlzdCwgZGVmYXVsdFZhbHVlLCB0cnVl
LCBtb2RlLCBzY29wZSkpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==
</value>
</Values>
