<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoY3Vyc29yLCAiJGxpc3QiKTsN
CiAgICBJRGF0YSBzY29wZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIkcGlwZWxpbmUi
KTsNCiAgICBTdHJpbmcgZGVmYXVsdFZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3Is
ICIkZGVmYXVsdCIpOw0KDQogICAgaWYgKGxpc3QgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJz
b3IsICIkbGlzdCIsIElEYXRhSGVscGVyLnN1YnN0aXR1dGUobGlzdCwgZGVmYXVsdFZhbHVlLCBz
Y29wZSA9PSBudWxsID8gcGlwZWxpbmUgOiBzY29wZSwgdHJ1ZSkpOw0KfSBmaW5hbGx5IHsNCiAg
ICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
