<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgU3RyaW5nIGRlZmF1bHRWYWx1ZSA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNv
ciwgU3RyaW5nLmNsYXNzLCAiJHN1YnN0aXR1dGlvbi5kZWZhdWx0IiwgIiRkZWZhdWx0Iik7DQog
ICAgU3Vic3RpdHV0aW9uVHlwZSBtb2RlID0gSURhdGFIZWxwZXIuZmlyc3QoY3Vyc29yLCBTdWJz
dGl0dXRpb25UeXBlLmNsYXNzLCAiJHN1YnN0aXR1dGlvbi5tb2RlIiwgIiRtb2RlIik7CiAgICBJ
RGF0YSBzY29wZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGlwZWxpbmUi
LCBJRGF0YS5jbGFzcywgcGlwZWxpbmUpOwoNCiAgICBpZiAobGlzdCAhPSBudWxsKSBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBTdWJzdGl0dXRpb25IZWxwZXIuc3Vic3RpdHV0ZShs
aXN0LCBkZWZhdWx0VmFsdWUsIHRydWUsIGZhbHNlLCBtb2RlLCBzY29wZSkpOw0KfSBmaW5hbGx5
IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
