<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deviate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURhdGEu
Y2xhc3MpOwogICAgaW50IHByZWNpc2lvbiA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJz
b3IsICIkcHJlY2lzaW9uIiwgSW50ZWdlci5jbGFzcywgLTEpOwogICAgUm91bmRpbmdNb2RlIHJv
dW5kaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRyb3VuZGluZyIsIFJvdW5kaW5nTW9k
ZS5jbGFzcyk7CgogICAgT2JqZWN0W10gbGVhdmVzID0gSURhdGFIZWxwZXIuZ2V0TGVhZlZhbHVl
cyhvcGVyYW5kcyk7CgogICAgaWYgKGxlYXZlcyAhPSBudWxsICYmIGxlYXZlcy5sZW5ndGggPiAw
KSB7CiAgICAgICAgZG91YmxlW10gc2FtcGxlcyA9IERvdWJsZUhlbHBlci5ub3JtYWxpemUoQmln
RGVjaW1hbEhlbHBlci5ub3JtYWxpemUobGVhdmVzKSk7CgogICAgICAgIE5vcm1hbERpc3RyaWJ1
dGlvbkVzdGltYXRvciBlc3RpbWF0b3IgPSBuZXcgTm9ybWFsRGlzdHJpYnV0aW9uRXN0aW1hdG9y
KHNhbXBsZXMpOwoKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHNhbXBsZS5kZXZp
YXRpb24iLCBCaWdEZWNpbWFsSGVscGVyLnJvdW5kKG5ldyBCaWdEZWNpbWFsKGVzdGltYXRvci5n
ZXRTdGFuZGFyZERldmlhdGlvbigpKSwgcHJlY2lzaW9uLCByb3VuZGluZyksIFN0cmluZy5jbGFz
cywgZmFsc2UpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc2FtcGxlLnZhcmlh
bmNlIiwgQmlnRGVjaW1hbEhlbHBlci5yb3VuZChuZXcgQmlnRGVjaW1hbChlc3RpbWF0b3IuZ2V0
VmFyaWFuY2UoKSksIHByZWNpc2lvbiwgcm91bmRpbmcpLCBTdHJpbmcuY2xhc3MsIGZhbHNlKTsK
ICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHNhbXBsZS5tZWFuIiwgQmlnRGVjaW1h
bEhlbHBlci5yb3VuZChuZXcgQmlnRGVjaW1hbChlc3RpbWF0b3IuZ2V0TWVhbigpKSwgcHJlY2lz
aW9uLCByb3VuZGluZyksIFN0cmluZy5jbGFzcywgZmFsc2UpOwogICAgICAgIElEYXRhSGVscGVy
LnB1dChjdXJzb3IsICIkc2FtcGxlLmNvdW50IiwgZXN0aW1hdG9yLmdldENvdW50KCksIFN0cmlu
Zy5jbGFzcywgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsK
fQ==</value>
</Values>
