<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">lowercase</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGxvd2VyY2FzZS5vcGVyYW5k
cyIsIElEYXRhLmNsYXNzKTsKICAgIExvY2FsZSBsb2NhbGUgPSBJRGF0YUhlbHBlci5maXJzdE9y
RGVmYXVsdChjdXJzb3IsIExvY2FsZS5jbGFzcywgTG9jYWxlLmdldERlZmF1bHQoKSwgIiRsb3dl
cmNhc2UubG9jYWxlIiwgIiRsb2NhbGUiKTsKICAgIGlmIChvcGVyYW5kcyA9PSBudWxsKSB7CiAg
ICAgICAgU3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwg
U3RyaW5nLmNsYXNzKTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIs
IFN0cmluZ0hlbHBlci5sb3dlcmNhc2Uoc3RyaW5nLCBsb2NhbGUpLCBmYWxzZSk7CiAgICB9IGVs
c2UgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkbG93ZXJjYXNlLnJlc3VsdHMi
LCBUcmFuc2Zvcm1lci50cmFuc2Zvcm0ob3BlcmFuZHMsIG5ldyBMb3dlcmNhc2VyKFRyYW5zZm9y
bWVyTW9kZS5WQUxVRVMsIGxvY2FsZSwgdHJ1ZSkpLCBmYWxzZSk7CiAgICB9Cn0gZmluYWxseSB7
CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
