<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">touch</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmJvb2xlYW4gcmFp
c2UgPSB0cnVlOw0KDQp0cnkgew0KICAgIFN0cmluZyBzZXNzaW9uS2V5ID0gSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgICIkc2Z0cC5zZXNzaW9uLmtleSIsIFN0cmluZy5jbGFzcyk7DQogICAgU3Ry
aW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAgIiRmaWxlIiwgU3RyaW5nLmNsYXNz
KTsNCiAgICBib29sZWFuIGNyZWF0ZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3Is
ICIkZmlsZS5jcmVhdGU/IiwgQm9vbGVhbi5jbGFzcywgdHJ1ZSk7DQogICAgQ2FsZW5kYXIgdXBk
YXRlZCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICAiJGZpbGUudXBkYXRlZCIsIENhbGVuZGFy
LmNsYXNzKTsNCiAgICByYWlzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIk
cmFpc2U/IiwgQm9vbGVhbi5jbGFzcywgdHJ1ZSk7DQoJDQogICAgdG91Y2goc2Vzc2lvbktleSwg
ZmlsZSwgY3JlYXRlLCB1cGRhdGVkKTsNCn0gY2F0Y2goU2Z0cEV4Y2VwdGlvbiBleCkgew0KICAg
IGlmIChyYWlzZSkgew0KICAgICAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KICAgIH0N
Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
