<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">touch</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQoJU3Ry
aW5nIHNlc3Npb25LZXkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAgIiRzZnRwLnNlc3Npb24u
a2V5IiwgU3RyaW5nLmNsYXNzKTsNCglTdHJpbmcgZmlsZSA9IElEYXRhSGVscGVyLmdldChjdXJz
b3IsICAiJGZpbGUiLCBTdHJpbmcuY2xhc3MpOw0KCWJvb2xlYW4gY3JlYXRlID0gSURhdGFIZWxw
ZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRmaWxlLmNyZWF0ZT8iLCBCb29sZWFuLmNsYXNzLCB0
cnVlKTsNCglDYWxlbmRhciB1cGRhdGVkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgICIkZmls
ZS51cGRhdGVkIiwgQ2FsZW5kYXIuY2xhc3MpOw0KCQ0KCXRvdWNoKHNlc3Npb25LZXksIGZpbGUs
IGNyZWF0ZSwgdXBkYXRlZCk7DQp9IGNhdGNoKFNmdHBFeGNlcHRpb24gZXgpIHsNCglFeGNlcHRp
b25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCgljdXJzb3IuZGVzdHJveSgpOw0KfQ==
</value>
</Values>
