<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">each</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIFN0
cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2VydmljZSIpOwog
IElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGluZSIpOwog
IFN0cmluZyBrZXlJbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleS5pbnB1
dCIpOwogIFN0cmluZyB2YWx1ZUlucHV0ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
dmFsdWUuaW5wdXQiKTsKICBTdHJpbmcgdmFsdWVDbGFzcyA9IElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJHZhbHVlLmNsYXNzIik7CiAgYm9vbGVhbiByZWN1cnNlID0gQm9vbGVhbi5wYXJz
ZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcmVjdXJzZT8iKSk7CiAgYm9v
bGVhbiBzY29wZWQgPSBzY29wZSAhPSBudWxsOwoKICBlYWNoKGRvY3VtZW50LCBzZXJ2aWNlLCBz
Y29wZWQgPyBzY29wZTogcGlwZWxpbmUsIGtleUlucHV0LCB2YWx1ZUlucHV0LCB2YWx1ZUNsYXNz
ID09IG51bGw/IG51bGwgOiBDbGFzcy5mb3JOYW1lKHZhbHVlQ2xhc3MpLCByZWN1cnNlKTsKfSBj
YXRjaCAoQ2xhc3NOb3RGb3VuZEV4Y2VwdGlvbiBleCkgewogIHR1bmRyYS5leGNlcHRpb24ucmFp
c2UoZXgpOwp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
