<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">each</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIFN0
cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2VydmljZSIpOwog
IElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGluZSIpOwog
IFN0cmluZyBrZXlJbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleS5pbnB1
dCIpOwogIFN0cmluZyB2YWx1ZUlucHV0ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
dmFsdWUuaW5wdXQiKTsKICBTdHJpbmcgdmFsdWVDbGFzcyA9IElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJHZhbHVlLmNsYXNzIik7CiAgYm9vbGVhbiBzY29wZWQgPSBzY29wZSAhPSBudWxs
OwoKICBlYWNoKGRvY3VtZW50LCBzZXJ2aWNlLCBzY29wZWQgPyBzY29wZTogcGlwZWxpbmUsIGtl
eUlucHV0LCB2YWx1ZUlucHV0LCB2YWx1ZUNsYXNzID09IG51bGw/IG51bGwgOiBDbGFzcy5mb3JO
YW1lKHZhbHVlQ2xhc3MpLCB0cnVlKTsKfSBjYXRjaCAoQ2xhc3NOb3RGb3VuZEV4Y2VwdGlvbiBl
eCkgewogIHR1bmRyYS5leGNlcHRpb24ucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
