<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">raised</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIFN0
cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2VydmljZSIpOw0K
ICBJRGF0YSBzY29wZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIkcGlwZWxpbmUiKTsN
CiAgSURhdGEgY3JpdGVyaWEgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGV4Y2VwdGlv
biIpOw0KICBTdHJpbmcgbWVzc2FnZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1l
c3NhZ2UiKTsNCg0KICByYWlzZWQoc2VydmljZSwgc2NvcGUgPT0gbnVsbCA/IHBpcGVsaW5lIDog
c2NvcGUsIGNyaXRlcmlhLCBtZXNzYWdlKTsNCn0gZmluYWxseSB7DQogIGN1cnNvci5kZXN0cm95
KCk7DQp9DQo=</value>
</Values>
