<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">raised</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHNlcnZpY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNlcnZpY2UiLCBTdHJp
bmcuY2xhc3MpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRw
aXBlbGluZSIsIElEYXRhLmNsYXNzKTsNCiAgICBJRGF0YSBjcml0ZXJpYSA9IElEYXRhSGVscGVy
LmdldChjdXJzb3IsICIkZXhjZXB0aW9uIiwgSURhdGEuY2xhc3MpOw0KICAgIFN0cmluZyBtZXNz
YWdlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRtZXNzYWdlIiwgU3RyaW5nLmNsYXNzKTsN
Cg0KICAgIHJhaXNlZChzZXJ2aWNlLCBzY29wZSA9PSBudWxsID8gcGlwZWxpbmUgOiBzY29wZSwg
Y3JpdGVyaWEsIG1lc3NhZ2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0K
fQ==</value>
</Values>
