<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIE9iamVj
dCBjb250ZW50ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudCIpOwogIFN0cmluZyBk
ZWxpbWl0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWxpbWl0ZXIiKTsKICBT
dHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNvZGluZyIp
OwoKICBpZiAoY29udGVudCAhPSBudWxsKSB7CiAgICBJRGF0YVtdIGxpc3QgPSBwYXJzZSh0dW5k
cmEuc3RyZWFtLm5vcm1hbGl6ZShjb250ZW50LCBlbmNvZGluZyksIGRlbGltaXRlciwgZW5jb2Rp
bmcpOwogICAgaWYgKGxpc3QgIT0gbnVsbCkgewogICAgICBJRGF0YSBkb2N1bWVudCA9IElEYXRh
RmFjdG9yeS5jcmVhdGUoKTsKICAgICAgSURhdGFDdXJzb3IgZGMgPSBkb2N1bWVudC5nZXRDdXJz
b3IoKTsKICAgICAgSURhdGFVdGlsLnB1dChkYywgInJlY29yZFdpdGhOb0lEIiwgbGlzdCk7CiAg
ICAgIGRjLmRlc3Ryb3koKTsKICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZG9jdW1lbnQi
LCBkb2N1bWVudCk7CiAgICB9CiAgfQp9IGNhdGNoIChqYXZhLmlvLklPRXhjZXB0aW9uIGV4KSB7
CiAgdHVuZHJhLmV4Y2VwdGlvbi5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ry
b3koKTsKfQ==</value>
</Values>
