<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGRhdGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRhdGV0aW1lLm9iamVjdCIp
Ow0KICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRwYXR0ZXJu
IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgdGltZXpvbmUgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHRpbWV6b25lIiwgU3RyaW5nLmNsYXNzKTsNCgogICAgU3RyaW5nIGRhdGV0aW1l
ID0gRGF0ZVRpbWVIZWxwZXIuZW1pdChEYXRlVGltZUhlbHBlci5ub3JtYWxpemUoZGF0ZSksIHBh
dHRlcm4sIHRpbWV6b25lKTsKDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkYXRldGlt
ZSIsIGRhdGV0aW1lLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
