<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
amF2YS51dGlsLkRhdGUgZGF0ZXRpbWUgPSAoamF2YS51dGlsLkRhdGUpSURhdGFVdGlsLmdldChj
dXJzb3IsICIkZGF0ZXRpbWUub2JqZWN0Iik7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7DQogICAgU3RyaW5nIHRpbWV6b25lID0g
SURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkdGltZXpvbmUiKTsNCg0KICAgIGlmIChkYXRl
dGltZSAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkYXRldGltZSIsIERhdGVUaW1l
SGVscGVyLmVtaXQoZGF0ZXRpbWUsIHBhdHRlcm4sIHRpbWV6b25lKSk7DQp9IGZpbmFsbHkgew0K
ICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
