<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
RGF0ZSBkYXRlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZS5vYmplY3QiLCBE
YXRlLmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkcGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHRpbWV6b25lID0gSURhdGFI
ZWxwZXIuZ2V0KGN1cnNvciwgIiR0aW1lem9uZSIsIFN0cmluZy5jbGFzcyk7DQoKICAgIFN0cmlu
ZyBkYXRldGltZSA9IERhdGVUaW1lSGVscGVyLmVtaXQoZGF0ZSwgcGF0dGVybiwgdGltZXpvbmUp
OwoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGRhdGV0aW1lIiwgZGF0ZXRpbWUsIGZh
bHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
