<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">power</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRlY2ltYWwgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWNpbWFsIik7
DQogICAgU3RyaW5nIGV4cG9uZW50ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZXhw
b25lbnQiKTsNCiAgICBTdHJpbmcgcHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJz
b3IsICIkcHJlY2lzaW9uIik7DQogICAgU3RyaW5nIHJvdW5kaW5nID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkcm91bmRpbmciKTsNCgogICAgU3RyaW5nIHJlc3VsdCA9IEJpZ0RlY2lt
YWxIZWxwZXIuZW1pdChCaWdEZWNpbWFsSGVscGVyLnJvdW5kKEJpZ0RlY2ltYWxIZWxwZXIucG93
ZXIoQmlnRGVjaW1hbEhlbHBlci5wYXJzZShkZWNpbWFsKSwgQmlnSW50ZWdlckhlbHBlci5wYXJz
ZShleHBvbmVudCkpLCBwcmVjaXNpb24sIHJvdW5kaW5nKSk7Cg0KICAgIGlmIChyZXN1bHQgIT0g
bnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHJlc3VsdCk7DQp9IGZpbmFs
bHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
