<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc3RyaW5nIik7CiAgU3RyaW5nIGNs
YXNzTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGNsYXNzIik7CiAgU3RyaW5n
IHJhZGl4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcmFkaXgiKTsKCiAgaWYgKHMg
IT0gbnVsbCkgewogICAgamF2YS5tYXRoLkJpZ0ludGVnZXIgaW50ZWdlciA9IHBhcnNlKHMsIHJh
ZGl4KTsKICAgIGlmIChjbGFzc05hbWUgPT0gbnVsbCB8fCBjbGFzc05hbWUuZXF1YWxzKCJqYXZh
Lm1hdGguQmlnSW50ZWdlciIpKSB7CiAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJG9iamVj
dCIsIGludGVnZXIpOwogICAgfSBlbHNlIGlmIChjbGFzc05hbWUuZXF1YWxzKCJqYXZhLmxhbmcu
SW50ZWdlciIpKSB7CiAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJG9iamVjdCIsIGludGVn
ZXIuaW50VmFsdWUoKSk7CiAgICB9IGVsc2UgaWYgKGNsYXNzTmFtZS5lcXVhbHMoImphdmEubGFu
Zy5Mb25nIikpIHsKICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkb2JqZWN0IiwgaW50ZWdl
ci5sb25nVmFsdWUoKSk7CiAgICB9CiAgfQp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
