<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgY2xhc3NOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkY2xhc3MiKTsKICBT
dHJpbmcgcmFkaXggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRyYWRpeCIpOwoKICBp
ZiAoc3RyaW5nICE9IG51bGwpIHsKICAgIGphdmEubWF0aC5CaWdJbnRlZ2VyIG9iamVjdCA9IHBh
cnNlKHN0cmluZywgcmFkaXgpOwogICAgaWYgKGNsYXNzTmFtZSA9PSBudWxsIHx8IGNsYXNzTmFt
ZS5lcXVhbHMoImphdmEubWF0aC5CaWdJbnRlZ2VyIikpIHsKICAgICAgSURhdGFVdGlsLnB1dChj
dXJzb3IsICIkb2JqZWN0Iiwgb2JqZWN0KTsKICAgIH0gZWxzZSBpZiAoY2xhc3NOYW1lLmVxdWFs
cygiamF2YS5sYW5nLkludGVnZXIiKSkgewogICAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRv
YmplY3QiLCBvYmplY3QuaW50VmFsdWUoKSk7CiAgICB9IGVsc2UgaWYgKGNsYXNzTmFtZS5lcXVh
bHMoImphdmEubGFuZy5Mb25nIikpIHsKICAgICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkb2Jq
ZWN0Iiwgb2JqZWN0LmxvbmdWYWx1ZSgpKTsKICAgIH0KICB9Cn0gZmluYWxseSB7CiAgY3Vyc29y
LmRlc3Ryb3koKTsKfQ==</value>
</Values>
