<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGRvY3VtZW50Iik7
DQogICAgU3RyaW5nIHNvdXJjZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleS5z
b3VyY2UiKTsNCiAgICBTdHJpbmcgdGFyZ2V0ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3Is
ICIka2V5LnRhcmdldCIpOw0KICAgIGJvb2xlYW4gbGl0ZXJhbCA9IEJvb2xlYW5IZWxwZXIucGFy
c2UoSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIka2V5LmxpdGVyYWw/IikpOw0KICAgIA0K
ICAgIGlmIChkb2N1bWVudCAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkb2N1bWVu
dCIsIElEYXRhSGVscGVyLmNvcHkoZG9jdW1lbnQsIHNvdXJjZSwgdGFyZ2V0LCBsaXRlcmFsKSk7
DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
