<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">filter</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBTdHJpbmcgY29uZGl0aW9uID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwg
IiRjb25kaXRpb24iLCBTdHJpbmcuY2xhc3MpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxw
ZXIuZ2V0KGN1cnNvciwgIiRzY29wZSIsIElEYXRhLmNsYXNzKTsNCg0KICAgIGlmIChsaXN0ICE9
IG51bGwpIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkbGlzdCIsIGZpbHRlcihsaXN0LCBjb25k
aXRpb24sIHNjb3BlID09IG51bGw/IHBpcGVsaW5lIDogc2NvcGUpKTsNCn0gZmluYWxseSB7DQog
ICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
