<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">minimum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkZGVjaW1h
bHMiKTsNCiAgICBTdHJpbmcgcHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3Is
ICIkcHJlY2lzaW9uIik7DQogICAgU3RyaW5nIHJvdW5kaW5nID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhjdXJzb3IsICIkcm91bmRpbmciKTsNCg0KICAgIFN0cmluZyByZXN1bHQgPSBtaW5pbXVtKGxp
c3QsIHByZWNpc2lvbiwgcm91bmRpbmcpOw0KDQogICAgaWYgKHJlc3VsdCAhPSBudWxsKSBJRGF0
YVV0aWwucHV0KGN1cnNvciwgIiRkZWNpbWFsIiwgcmVzdWx0KTsNCn0gZmluYWxseSB7DQogICAg
Y3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
