<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHN0cmluZyIpOw0K
ICAgIFN0cmluZyBwYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0dGVy
biIpOw0KICAgIFN0cmluZyByZXBsYWNlbWVudCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJHJlcGxhY2VtZW50Iik7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gQm9vbGVhbkhlbHBlci5w
YXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRsaXRlcmFsPyIpKTsNCg0KICAgIElE
YXRhVXRpbC5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZ0hlbHBlci5yZXBsYWNlKHN0cmlu
ZywgcGF0dGVybiwgcmVwbGFjZW1lbnQsIGxpdGVyYWwpKTsNCn0gZmluYWxseSB7DQogICAgY3Vy
c29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
