<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHJlcGxhY2VtZW50ID0gSURhdGFI
ZWxwZXIuZ2V0KGN1cnNvciwgIiRyZXBsYWNlbWVudCIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9v
bGVhbiBsaXRlcmFsID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRsaXRlcmFs
PyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRhSGVscGVy
LmdldChjdXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFzcyk7Cg0KICAgIElEYXRhSGVscGVyLnB1
dChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nSGVscGVyLnJlcGxhY2Uoc3RyaW5nLCBwYXR0ZXJu
LCByZXBsYWNlbWVudCwgbGl0ZXJhbCwgKCEobW9kZSA9PSBudWxsIHx8IG1vZGUuZXF1YWxzKCJh
bGwiKSkpKSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==
</value>
</Values>
