<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIFN0
cmluZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsNCiAg
U3RyaW5nIHBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7
DQogIFN0cmluZyByZXBsYWNlbWVudCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHJl
cGxhY2VtZW50Iik7DQogIGJvb2xlYW4gbGl0ZXJhbCA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURh
dGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbGl0ZXJhbD8iKSk7DQoNCiAgSURhdGFVdGlsLnB1
dChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nSGVscGVyLnJlcGxhY2Uoc3RyaW5nLCBwYXR0ZXJu
LCByZXBsYWNlbWVudCwgbGl0ZXJhbCkpOw0KfSBmaW5hbGx5IHsNCiAgY3Vyc29yLmRlc3Ryb3ko
KTsNCn0NCg==</value>
</Values>
