<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">equal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBzb3VyY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUuc291cmNlIiwgRmlsZS5j
bGFzcyk7CiAgICBGaWxlIHRhcmdldCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZS50
YXJnZXQiLCBGaWxlLmNsYXNzKTsKICAgIGJvb2xlYW4gcmFpc2UgPSBJRGF0YUhlbHBlci5nZXRP
ckRlZmF1bHQoY3Vyc29yLCAiJHJhaXNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBi
b29sZWFuIGVxdWFsID0gRmlsZUhlbHBlci5lcXVhbChzb3VyY2UsIHRhcmdldCwgcmFpc2UpOwoK
ICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZmlsZS5lcXVhbD8iLCBlcXVhbCwgU3RyaW5n
LmNsYXNzKTsKfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgewogICAgRXhjZXB0aW9uSGVscGVyLnJh
aXNlKGV4KTsKfSBjYXRjaChOb1N1Y2hBbGdvcml0aG1FeGNlcHRpb24gZXgpIHsKICAgIEV4Y2Vw
dGlvbkhlbHBlci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9
</value>
</Values>
