<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">equal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZS5zb3VyY2UiLCBTdHJp
bmcuY2xhc3MpOwogICAgU3RyaW5nIHRhcmdldCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
ZmlsZS50YXJnZXQiLCBTdHJpbmcuY2xhc3MpOwogICAgYm9vbGVhbiByYWlzZSA9IElEYXRhSGVs
cGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcmFpc2U/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2Up
OwoKICAgIGJvb2xlYW4gZXF1YWwgPSBGaWxlSGVscGVyLmVxdWFsKHNvdXJjZSwgdGFyZ2V0LCBy
YWlzZSk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRmaWxlLmVxdWFsPyIsIGVxdWFs
LCBTdHJpbmcuY2xhc3MpOwp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRpb25I
ZWxwZXIucmFpc2UoZXgpOwp9IGNhdGNoKE5vU3VjaEFsZ29yaXRobUV4Y2VwdGlvbiBleCkgewog
ICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0
cm95KCk7Cn0=</value>
</Values>
