<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IG9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb2JqZWN0Iik7DQogICAg
Q2hhcnNldCBjaGFyc2V0ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRlbmNv
ZGluZyIsIENoYXJzZXQuY2xhc3MsIENoYXJzZXRIZWxwZXIuREVGQVVMVF9DSEFSU0VUKTsNCgog
ICAgYnl0ZVtdIGJ5dGVzID0gQnl0ZXNIZWxwZXIubm9ybWFsaXplKG9iamVjdCwgY2hhcnNldCk7
CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRieXRlcyIsIGJ5dGVzLCBmYWxzZSk7DQog
ICAgaWYgKGJ5dGVzICE9IG51bGwgJiYgb2JqZWN0IGluc3RhbmNlb2YgU3RyaW5nKSBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGVuY29kaW5nIiwgY2hhcnNldC5uYW1lKCkpOwp9IGNhdGNoKElP
RXhjZXB0aW9uIGV4KSB7DQogICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
