<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGRvY3VtZW50Iik7CiAg
ICBTdHJpbmcgdmFsdWVTZXBhcmF0b3IgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRz
ZXBhcmF0b3IudmFsdWUiKTsKICAgIFN0cmluZyBsaXN0U2VwYXJhdG9yID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjdXJzb3IsICIkc2VwYXJhdG9yLmxpc3QiKTsKICAgIFN0cmluZyBpdGVtU2VwYXJh
dG9yID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2VwYXJhdG9yLml0ZW0iKTsKICAg
IFNhbml0aXphdGlvbiBzYW5pdGl6YXRpb24gPSBTYW5pdGl6YXRpb24ubm9ybWFsaXplKElEYXRh
VXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHNhbml0aXphdGlvbiIpKTsKCiAgICBpZiAoZG9jdW1l
bnQgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkcmVzdWx0IiwgSURhdGFIZWxwZXIu
am9pbihkb2N1bWVudCwgaXRlbVNlcGFyYXRvciwgbGlzdFNlcGFyYXRvciwgdmFsdWVTZXBhcmF0
b3IsIHNhbml0aXphdGlvbikpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==
</value>
</Values>
