<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nIGNvbnRlbnRTY2hlbWEgPSBJRGF0YUhlbHBlci5maXJzdChjdXJz
b3IsIFN0cmluZy5jbGFzcywgIiRjb250ZW50LnNjaGVtYSIsICIkc2NoZW1hIik7CiAgICBib29s
ZWFuIHJhaXNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRyYWlzZT8iLCBC
b29sZWFuLmNsYXNzLCBmYWxzZSk7CgogICAgVmFsaWRhdGlvblJlc3VsdCByZXN1bHQgPSBWYWxp
ZGF0aW9uSGVscGVyLnZhbGlkYXRlKGRvY3VtZW50LCBjb250ZW50U2NoZW1hKTsKICAgIHJlc3Vs
dC5yYWlzZUlmSW52YWxpZChyYWlzZSk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiR2
YWxpZD8iLCByZXN1bHQuaXNWYWxpZCgpLCBTdHJpbmcuY2xhc3MpOwogICAgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiRtZXNzYWdlIiwgcmVzdWx0LmdldE1lc3NhZ2UoKSwgZmFsc2UpOwp9IGZp
bmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
