<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">reverse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHJldmVyc2Uub3BlcmFuZHMi
LCBJRGF0YS5jbGFzcyk7CiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkgewogICAgICAgIC8vIHN1
cHBvcnQgJHN0cmluZyBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkKICAgICAgICBTdHJpbmcg
aW5wdXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZy5jbGFzcyk7
CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmdIZWxwZXIu
cmV2ZXJzZShpbnB1dCksIGZhbHNlKTsKICAgIH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiRyZXZlcnNlLnJlc3VsdHMiLCBUcmFuc2Zvcm1lci50cmFuc2Zvcm0ob3Bl
cmFuZHMsIG5ldyBSZXZlcnNlcihUcmFuc2Zvcm1lck1vZGUuVkFMVUVTLCB0cnVlKSksIGZhbHNl
KTsKICAgIH0KfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
