<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">each</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBTdHJpbmcgc2VydmljZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
c2VydmljZSIsIFN0cmluZy5jbGFzcyk7DQogICAgSURhdGEgc2NvcGUgPSBJRGF0YUhlbHBlci5n
ZXQoY3Vyc29yLCAiJHBpcGVsaW5lIiwgSURhdGEuY2xhc3MpOw0KICAgIFN0cmluZyBpbnB1dCA9
IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkaXRlbS5pbnB1dCIsIFN0cmluZy5jbGFzcyk7DQoN
CiAgICBib29sZWFuIHNjb3BlZCA9IHNjb3BlICE9IG51bGw7DQoNCiAgICAvLyBpbnZva2UgdGhl
IHNlcnZpY2UgZm9yIGVhY2ggaXRlbSBpbiB0aGUgbGlzdCwgcGFzc2luZyANCiAgICAvLyAkaXRl
bSBhbmQgJGluZGV4IHZhcmlhYmxlcyBvbiBlYWNoIGludm9jYXRpb24NCiAgICBlYWNoKGxpc3Qs
IHNlcnZpY2UsIHNjb3BlZCA/IHNjb3BlIDogcGlwZWxpbmUsIGlucHV0KTsNCn0gZmluYWxseSB7
DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
