<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">each</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIFN0cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2Vy
dmljZSIpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRw
aXBlbGluZSIpOw0KICAgIFN0cmluZyBpbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJGl0ZW0uaW5wdXQiKTsNCg0KICAgIGJvb2xlYW4gc2NvcGVkID0gc2NvcGUgIT0gbnVsbDsN
Cg0KICAgIC8vIGludm9rZSB0aGUgc2VydmljZSBmb3IgZWFjaCBpdGVtIGluIHRoZSBsaXN0LCBw
YXNzaW5nIA0KICAgIC8vICRpdGVtIGFuZCAkaW5kZXggdmFyaWFibGVzIG9uIGVhY2ggaW52b2Nh
dGlvbg0KICAgIGVhY2gobGlzdCwgc2VydmljZSwgc2NvcGVkID8gc2NvcGUgOiBwaXBlbGluZSwg
aW5wdXQpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
