<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">group</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgSURhdGEgY3JpdGVyaWEgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGdy
b3VwIiwgSURhdGEuY2xhc3MpOwogICAgU3RyaW5nW10ga2V5cyA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIka2V5cyIsIFN0cmluZ1tdLmNsYXNzKTsNCg0KICAgIGlmIChsaXN0ICE9IG51bGwp
IHsKICAgICAgICBpZiAoa2V5cyAhPSBudWxsKSB7CiAgICAgICAgICAgIElEYXRhSGVscGVyLnB1
dChjdXJzb3IsICIkbGlzdC5ncm91cGVkIiwgSURhdGFIZWxwZXIuZ3JvdXAobGlzdCwga2V5cykp
OwogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIk
bGlzdC5ncm91cHMiLCBJRGF0YUhlbHBlci5ncm91cChsaXN0LCBjcml0ZXJpYSkpOwogICAgICAg
IH0KICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
