<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remainder</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
QmlnSW50ZWdlciBkaXZpZGVuZCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZGl2aWRlbmQi
LCBCaWdJbnRlZ2VyLmNsYXNzKTsKICAgIEJpZ0ludGVnZXIgZGl2aXNvciA9IElEYXRhSGVscGVy
LmdldChjdXJzb3IsICIkZGl2aXNvciIsIEJpZ0ludGVnZXIuY2xhc3MpOwoKICAgIC8vIHN1cHBv
cnQgJGludGVnZXIueCBhbmQgJGludGVnZXIueSBpbnB1dHMgZm9yIGJhY2t3YXJkcy1jb21wYXRp
YmlsaXR5CiAgICBib29sZWFuIGJhY2t3YXJkc0NvbXBhdGlibGl0eVJlcXVpcmVkID0gZmFsc2U7
CiAgICBpZiAoZGl2aWRlbmQgPT0gbnVsbCAmJiBkaXZpc29yID09IG51bGwpIHsKICAgICAgICBk
aXZpZGVuZCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkaW50ZWdlci54IiwgQmlnSW50ZWdl
ci5jbGFzcyk7CiAgICAgICAgZGl2aXNvciA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkaW50
ZWdlci55IiwgQmlnSW50ZWdlci5jbGFzcyk7CiAgICAgICAgYmFja3dhcmRzQ29tcGF0aWJsaXR5
UmVxdWlyZWQgPSB0cnVlOwogICAgfQoKICAgIEJpZ0ludGVnZXIgcmVzdWx0ID0gQmlnSW50ZWdl
ckhlbHBlci5yZW1haW5kZXIoZGl2aWRlbmQsIGRpdmlzb3IpOwoKICAgIGlmIChiYWNrd2FyZHND
b21wYXRpYmxpdHlSZXF1aXJlZCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIk
aW50ZWdlciIsIHJlc3VsdCwgU3RyaW5nLmNsYXNzLCBmYWxzZSk7CiAgICB9IGVsc2UgewogICAg
ICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcmVtYWluZGVyIiwgcmVzdWx0LCBTdHJpbmcu
Y2xhc3MsIGZhbHNlKTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0K
fQ==</value>
</Values>
