<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIiRjb250ZW50Iik7DQogICAg
Q2hhcnNldCBjaGFyc2V0ID0gQ2hhcnNldEhlbHBlci5ub3JtYWxpemUoSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkZW5jb2RpbmciKSk7DQoNCiAgICBpZiAoY29udGVudCAhPSBudWxsKSB7
DQogICAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGFZQU1MUGFy
c2VyLmdldEluc3RhbmNlKCkucGFyc2UoSW5wdXRTdHJlYW1IZWxwZXIubm9ybWFsaXplKGNvbnRl
bnQsIGNoYXJzZXQpKSk7DQogICAgfQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZXgpIHsNCiAgICBF
eGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJv
eSgpOw0KfQ==</value>
</Values>
