<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsNCiAg
ICBDaGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGVuY29kaW5nIiwg
Q2hhcnNldC5jbGFzcyk7DQoNCiAgICBpZiAoY29udGVudCAhPSBudWxsKSB7DQogICAgICAgIElE
YXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBuZXcgSURhdGFZQU1MUGFyc2VyKCku
cGFyc2UoSW5wdXRTdHJlYW1IZWxwZXIubm9ybWFsaXplKGNvbnRlbnQsIGNoYXJzZXQpKSk7DQog
ICAgfQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFp
c2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
