<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsNCiAg
ICBDaGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIENoYXJzZXQuY2xh
c3MsICIkY29udGVudC5lbmNvZGluZyIsICIkZW5jb2RpbmciKTsNCg0KICAgIGlmIChjb250ZW50
ICE9IG51bGwpIHsNCiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudCIs
IG5ldyBJRGF0YVlBTUxQYXJzZXIoKS5wYXJzZShJbnB1dFN0cmVhbUhlbHBlci5ub3JtYWxpemUo
Y29udGVudCwgY2hhcnNldCkpKTsNCiAgICB9DQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBleCkgew0K
ICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5k
ZXN0cm95KCk7DQp9</value>
</Values>
