<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convert</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkdmFsdWUiKTsKICAgIFN0
cmluZyBpbnB1dFVuaXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiR1bml0LmlucHV0
Iik7CiAgICBTdHJpbmcgb3V0cHV0VW5pdCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAi
JHVuaXQub3V0cHV0Iik7CiAgICBTdHJpbmcgcHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhjdXJzb3IsICIkcHJlY2lzaW9uIik7CiAgICBTdHJpbmcgcm91bmRpbmcgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKGN1cnNvciwgIiRyb3VuZGluZyIpOwoKICAgIGlmICh2YWx1ZSAhPSBudWxsKSBJ
RGF0YVV0aWwucHV0KGN1cnNvciwgIiRyZXN1bHQiLCBCaWdEZWNpbWFsSGVscGVyLmVtaXQoQmln
RGVjaW1hbEhlbHBlci5yb3VuZChNZWFzdXJlSGVscGVyLmZvcm1hdChCaWdEZWNpbWFsSGVscGVy
LnBhcnNlKHZhbHVlKSwgVW5pdEhlbHBlci5wYXJzZShpbnB1dFVuaXQpLCBVbml0SGVscGVyLnBh
cnNlKG91dHB1dFVuaXQpLCBNYXRoQ29udGV4dC5ERUNJTUFMMTI4KSwgcHJlY2lzaW9uLCByb3Vu
ZGluZykpKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
