<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">truncate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURhdGEu
Y2xhc3MpOwogICAgaW50IGxlbmd0aCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGVuZ3Ro
IiwgSW50ZWdlci5jbGFzcyk7CiAgICBib29sZWFuIGVsbGlwc2lzID0gSURhdGFIZWxwZXIuZ2V0
T3JEZWZhdWx0KGN1cnNvciwgIiRlbGxpcHNpcz8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7Cgog
ICAgSURhdGEgcmVzdWx0cyA9IFN0cmluZ0hlbHBlci50cnVuY2F0ZShvcGVyYW5kcywgbGVuZ3Ro
LCBlbGxpcHNpcyk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRyZXN1bHRzIiwgcmVz
dWx0cywgZmFsc2UpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
