<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">truncate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG91dHB1dFBhcmFtZXRlck5hbWUgPSAiJHRydW5jYXRlLnJlc3VsdHMiOwogICAgSURhdGEg
b3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHRydW5jYXRlLm9wZXJhbmRzIiwg
SURhdGEuY2xhc3MpOwogICAgaWYgKG9wZXJhbmRzID09IG51bGwpIHsKICAgICAgICAvLyBzdXBw
b3J0ICRvcGVyYW5kcyBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkKICAgICAgICBvcGVyYW5k
cyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb3BlcmFuZHMiLCBJRGF0YS5jbGFzcyk7CiAg
ICAgICAgb3V0cHV0UGFyYW1ldGVyTmFtZSA9ICIkcmVzdWx0cyI7CiAgICB9CiAgICBpbnQgbGVu
Z3RoID0gSURhdGFIZWxwZXIuZmlyc3QoY3Vyc29yLCBJbnRlZ2VyLmNsYXNzLCAiJHRydW5jYXRl
Lmxlbmd0aCIsICIkbGVuZ3RoIik7CiAgICBib29sZWFuIGVsbGlwc2lzID0gSURhdGFIZWxwZXIu
Zmlyc3RPckRlZmF1bHQoY3Vyc29yLCBCb29sZWFuLmNsYXNzLCBmYWxzZSwgIiR0cnVuY2F0ZS5l
bGxpcHNpcz8iLCAiJGVsbGlwc2lzPyIpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsIG91
dHB1dFBhcmFtZXRlck5hbWUsIFRyYW5zZm9ybWVyLnRyYW5zZm9ybShvcGVyYW5kcywgbmV3IFRy
dW5jYXRvcihsZW5ndGgsIGVsbGlwc2lzKSksIGZhbHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNv
ci5kZXN0cm95KCk7Cn0=</value>
</Values>
