<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">amend</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIElEYXRhIG5hbWVzcGFjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkZG9jdW1lbnQubmFtZXNwYWNlIiwgSURhdGEuY2xhc3MpOwogICAgSURhdGFbXSBhbWVuZG1l
bnRzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRhbWVuZG1lbnRzIiwgSURhdGFbXS5jbGFz
cyk7DQoNCiAgICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwg
IiRkb2N1bWVudCIsIElEYXRhSGVscGVyLmFtZW5kKGRvY3VtZW50LCBuYW1lc3BhY2UsIGFtZW5k
bWVudHMsIHBpcGVsaW5lKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9
</value>
</Values>
