<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">chain</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
Z1tdIHNlcnZpY2VzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRzZXJ2aWNl
cyIpOwogIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGlu
ZSIpOwogIGJvb2xlYW4gc2NvcGVkID0gc2NvcGUgIT0gbnVsbDsKCiAgU3RyaW5nIHN0YXJ0ID0g
dHVuZHJhLmRhdGV0aW1lLm5vdygpOwogIHNjb3BlID0gY2hhaW4oc2VydmljZXMsIHNjb3BlZCA/
IHNjb3BlIDogcGlwZWxpbmUpOwogIFN0cmluZyBlbmQgPSB0dW5kcmEuZGF0ZXRpbWUubm93KCk7
CgogIGlmIChzY29wZWQpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHBpcGVsaW5lIiwgc2NvcGUp
OwogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGR1cmF0aW9uIiwgdHVuZHJhLmRhdGV0aW1lLmR1
cmF0aW9uKHN0YXJ0LCBlbmQpKTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
