<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgZGVmYXVsdFZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkZWZhdWx0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVs
cGVyLmdldChjdXJzb3IsICIkcGlwZWxpbmUiLCBJRGF0YS5jbGFzcyk7DQogICAgRW51bVNldDxT
dWJzdGl0dXRpb25UeXBlPiBtb2RlID0gU3Vic3RpdHV0aW9uVHlwZS5ub3JtYWxpemUoSURhdGFI
ZWxwZXIuZ2V0KGN1cnNvciwgIiRtb2RlIiwgU3RyaW5nLmNsYXNzKSk7Cg0KICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkc3RyaW5nIiwgU3Vic3RpdHV0aW9uSGVscGVyLnN1YnN0aXR1dGUo
c3RyaW5nLCBkZWZhdWx0VmFsdWUsIHNjb3BlID09IG51bGwgPyBwaXBlbGluZSA6IHNjb3BlLCBt
b2RlKSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
