<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgZGVmYXVsdFZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkZWZhdWx0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVs
cGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGlwZWxpbmUiLCBJRGF0YS5jbGFzcywgcGlwZWxp
bmUpOw0KICAgIEVudW1TZXQ8U3Vic3RpdHV0aW9uVHlwZT4gbW9kZSA9IFN1YnN0aXR1dGlvblR5
cGUubm9ybWFsaXplKElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFz
cykpOwoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN1YnN0aXR1dGlv
bkhlbHBlci5zdWJzdGl0dXRlKHN0cmluZywgZGVmYXVsdFZhbHVlLCBtb2RlLCBzY29wZSksIGZh
bHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
