<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHBh
dHRlcm4iLCBTdHJpbmcuY2xhc3MpOwogICAgYm9vbGVhbiBsaXRlcmFsUGF0dGVybiA9IElEYXRh
SGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xlYW4u
Y2xhc3MsIGZhbHNlKTsKICAgIGJvb2xlYW4gZmlyc3RPY2N1cnJlbmNlID0gSURhdGFIZWxwZXIu
Z2V0T3JEZWZhdWx0KGN1cnNvciwgIiRvY2N1cnJlbmNlLmZpcnN0PyIsIEJvb2xlYW4uY2xhc3Ms
IGZhbHNlKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChj
dXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAgICBUcmFuc2Zvcm1l
ck1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFRyYW5zZm9ybWVy
TW9kZS5jbGFzcyk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudCIsIFRy
YW5zZm9ybWVyLnRyYW5zZm9ybShkb2N1bWVudCwgbmV3IFJlcGxhY2VyKG1vZGUsIFBhdHRlcm5I
ZWxwZXIuY29tcGlsZShwYXR0ZXJuLCBsaXRlcmFsUGF0dGVybiksICIiLCBmaXJzdE9jY3VycmVu
Y2UsIHJlY3Vyc2UpKSwgZmFsc2UpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsK
fQ==</value>
</Values>
