<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">evaluate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGNvbmRpdGlvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGNvbmRpdGlv
biIpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRzY29w
ZSIpOw0KDQogICAgaWYgKGNvbmRpdGlvbiA9PSBudWxsKSB7CiAgICAgICAgSURhdGFVdGlsLnB1
dChjdXJzb3IsICIkcmVzdWx0PyIsICJ0cnVlIik7CiAgICB9IGVsc2UgewogICAgICAgIElEYXRh
VXRpbC5wdXQoY3Vyc29yLCAiJHJlc3VsdD8iLCAiIiArIENvbmRpdGlvbkV2YWx1YXRvci5ldmFs
dWF0ZShjb25kaXRpb24sIHNjb3BlID09IG51bGw/IHBpcGVsaW5lIDogc2NvcGUpKTsNCiAgICB9
Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0NCg0K</value>
</Values>
