<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">evaluate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGNvbmRpdGlvbiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkY29uZGl0aW9uIiwg
U3RyaW5nLmNsYXNzKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkc2NvcGUiLCBJRGF0YS5jbGFzcyk7DQogICAgSURhdGFOYW1lc3BhY2VDb250ZXh0IG5hbWVz
cGFjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbmFtZXNwYWNlIiwgSURhdGFOYW1lc3Bh
Y2VDb250ZXh0LmNsYXNzKTsKDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRyZXN1bHQ/
IiwgQ29uZGl0aW9uRXZhbHVhdG9yLmV2YWx1YXRlKGNvbmRpdGlvbiwgc2NvcGUgPT0gbnVsbD8g
cGlwZWxpbmUgOiBzY29wZSwgbmFtZXNwYWNlKSwgU3RyaW5nLmNsYXNzKTsNCn0gZmluYWxseSB7
DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
