<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">evaluate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGNvbmRpdGlvbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGNvbmRpdGlv
biIpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRzY29w
ZSIpOw0KICAgIElEYXRhIG5hbWVzcGFjZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIk
bmFtZXNwYWNlIik7Cg0KICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHJlc3VsdD8iLCBCb29s
ZWFuSGVscGVyLmVtaXQoQ29uZGl0aW9uRXZhbHVhdG9yLmV2YWx1YXRlKGNvbmRpdGlvbiwgc2Nv
cGUgPT0gbnVsbD8gcGlwZWxpbmUgOiBzY29wZSwgSURhdGFOYW1lc3BhY2VDb250ZXh0Lm9mKG5h
bWVzcGFjZSkpKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
