<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">coalesce</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIE9iamVj
dCB4ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkb2JqZWN0LngiKTsKICBPYmplY3QgeSA9IElE
YXRhVXRpbC5nZXQoY3Vyc29yLCAiJG9iamVjdC55Iik7CiAgU3RyaW5nIG1vZGUgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRtb2RlIik7CgogIE9iamVjdCByZXN1bHQgPSB0dW5kcmEu
b2JqZWN0LmNvYWxlc2NlKHgsIHkpOwoKICBpZiAocmVzdWx0ICE9IG51bGwgfHwgKG1vZGUgIT0g
bnVsbCAmJiBtb2RlLmVxdWFscygibnVsbCIpKSkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkb2Jq
ZWN0IiwgcmVzdWx0KTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
