<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pad</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBpbnQgbGVuZ3RoID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNv
ciwgIiRsZW5ndGgiLCBJbnRlZ2VyLmNsYXNzLCAwKTsNCiAgICBTdHJpbmcgY2hhcmFjdGVyID0g
SURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjaGFyYWN0ZXIiLCBTdHJpbmcuY2xhc3MpOw0KDQog
ICAgY2hhciBjID0gKGNoYXJhY3RlciA9PSBudWxsIHx8IGNoYXJhY3Rlci5sZW5ndGgoKSA9PSAw
KSA/ICcgJyA6IGNoYXJhY3Rlci5jaGFyQXQoMCk7DQoNCiAgICBpZiAoc3RyaW5nICE9IG51bGwp
IHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZ0hlbHBl
ci5wYWQoc3RyaW5nLCBsZW5ndGgsIGMpKTsNCiAgICB9Cn0gZmluYWxseSB7DQogICAgY3Vyc29y
LmRlc3Ryb3koKTsNCn0=</value>
</Values>
