<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pad</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBzdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzdHJpbmciKTsKICBTdHJp
bmcgbGVuZ3RoID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbGVuZ3RoIik7CiAgU3Ry
aW5nIGNoYXJhY3RlciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGNoYXJhY3RlciIp
OwoKICBpbnQgbGVuID0gbGVuZ3RoID09IG51bGwgPyAwIDogSW50ZWdlci5wYXJzZUludChsZW5n
dGgpOwogIGNoYXIgYyA9IChjaGFyYWN0ZXIgPT0gbnVsbCB8fCBjaGFyYWN0ZXIubGVuZ3RoKCkg
PT0gMCkgPyAnICcgOiBjaGFyYWN0ZXIuY2hhckF0KDApOwoKICBpZiAoc3RyaW5nICE9IG51bGwp
IElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZ0hlbHBlci5wYWQoc3RyaW5n
LCBsZW4sIGMpKTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
