<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pad</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHN0cmluZyIpOw0K
ICAgIFN0cmluZyBsZW5ndGggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRsZW5ndGgi
KTsNCiAgICBTdHJpbmcgY2hhcmFjdGVyID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIk
Y2hhcmFjdGVyIik7DQoNCiAgICBpbnQgbGVuID0gbGVuZ3RoID09IG51bGwgPyAwIDogSW50ZWdl
ci5wYXJzZUludChsZW5ndGgpOw0KICAgIGNoYXIgYyA9IChjaGFyYWN0ZXIgPT0gbnVsbCB8fCBj
aGFyYWN0ZXIubGVuZ3RoKCkgPT0gMCkgPyAnICcgOiBjaGFyYWN0ZXIuY2hhckF0KDApOw0KDQog
ICAgaWYgKHN0cmluZyAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRzdHJpbmciLCBT
dHJpbmdIZWxwZXIucGFkKHN0cmluZywgbGVuLCBjKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNv
ci5kZXN0cm95KCk7DQp9</value>
</Values>
