<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">gzip</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBzb3VyY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBGaWxlLmNsYXNzKTsK
ICAgIEZpbGUgdGFyZ2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlLmd6aXAiLCBG
aWxlLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVwbGFjZSA9IElEYXRhSGVscGVyLmZpcnN0T3JEZWZh
dWx0KGN1cnNvciwgQm9vbGVhbi5jbGFzcywgZmFsc2UsICIkZmlsZS5yZW1vdmU/IiwgIiRyZXBs
YWNlPyIpOwogICAgaW50IGJ1ZmZlclNpemUgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vy
c29yLCAiJGZpbGUuYnVmZmVyLnNpemUiLCBJbnRlZ2VyLmNsYXNzLCAtMSk7CgogICAgSURhdGFI
ZWxwZXIucHV0KGN1cnNvciwgIiRmaWxlLmd6aXAiLCBGaWxlSGVscGVyLm5vcm1hbGl6ZShGaWxl
SGVscGVyLmd6aXAoc291cmNlLCB0YXJnZXQsIHJlcGxhY2UsIGJ1ZmZlclNpemUpKSk7Cn0gY2F0
Y2goSU9FeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7Cn0gZmlu
YWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
