<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgTWFw
IG1hcCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbWFwIiwgTWFwLmNsYXNzKTsKICAgIE9i
amVjdCBrZXkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGtleSIpOwogICAgT2JqZWN0IHZh
bHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiR2YWx1ZSIpOwoKICAgIGJvb2xlYW4gcmVt
b3ZlZCA9IHRydWU7CgogICAgaWYgKHZhbHVlID09IG51bGwpIHsKICAgICAgICB2YWx1ZSA9IE1h
cEhlbHBlci5yZW1vdmUobWFwLCBrZXkpOwogICAgfSBlbHNlIHsKICAgICAgICByZW1vdmVkID0g
Q29uY3VycmVudE1hcEhlbHBlci5yZW1vdmUoKENvbmN1cnJlbnRNYXApbWFwLCBrZXksIHZhbHVl
KTsKICAgIH0KCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGtleS5yZW1vdmVkPyIsIHJl
bW92ZWQsIFN0cmluZy5jbGFzcyk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9
</value>
</Values>
