<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">reject</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBTdHJpbmcgY29uZGl0aW9uID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwg
IiRjb25kaXRpb24iLCBTdHJpbmcuY2xhc3MpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxw
ZXIuZ2V0KGN1cnNvciwgIiRzY29wZSIsIElEYXRhLmNsYXNzKTsNCg0KICAgIE9iamVjdFtdIHJl
amVjdGVkTGlzdCA9IHJlamVjdChsaXN0LCBjb25kaXRpb24sIHNjb3BlID09IG51bGw/IHBpcGVs
aW5lIDogc2NvcGUpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkbGlzdCIsIHJlamVj
dGVkTGlzdCwgZmFsc2UpOw0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkbGlzdC5sZW5n
dGgiLCByZWplY3RlZExpc3QgPT0gbnVsbCA/IDAgOiByZWplY3RlZExpc3QubGVuZ3RoLCBTdHJp
bmcuY2xhc3MpOwp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
