<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5jbGFz
cyk7CiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcGF0dGVy
biIsIFN0cmluZy5jbGFzcyk7CiAgICBib29sZWFuIGxpdGVyYWxQYXR0ZXJuID0gSURhdGFIZWxw
ZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRwYXR0ZXJuLmxpdGVyYWw/IiwgQm9vbGVhbi5jbGFz
cywgZmFsc2UpOwogICAgYm9vbGVhbiBmaXJzdE9jY3VycmVuY2UgPSBJRGF0YUhlbHBlci5nZXRP
ckRlZmF1bHQoY3Vyc29yLCAiJG9jY3VycmVuY2UuZmlyc3Q/IiwgQm9vbGVhbi5jbGFzcywgZmFs
c2UpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNv
ciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKICAgIFRyYW5zZm9ybWVyTW9k
ZSBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRtb2RlIiwgVHJhbnNmb3JtZXJNb2Rl
LmNsYXNzKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBJRGF0YUhlbHBl
ci5yZW1vdmUobGlzdCwgcGF0dGVybiwgbGl0ZXJhbFBhdHRlcm4sIGZpcnN0T2NjdXJyZW5jZSwg
bW9kZSwgcmVjdXJzZSksIGZhbHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
