<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">lowercase</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgTG9jYWxlIGxvY2FsZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbG9j
YWxlIiwgTG9jYWxlLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdl
dE9yRGVmYXVsdChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAg
ICBUcmFuc2Zvcm1lck1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIs
IFRyYW5zZm9ybWVyTW9kZS5jbGFzcyk7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRs
aXN0IiwgSURhdGFIZWxwZXIubG93ZXJjYXNlKGxpc3QsIGxvY2FsZSwgbW9kZSwgcmVjdXJzZSks
IGZhbHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
