<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IG9iamVjdCA9IElEYXRhVXRpbC5nZXQoY3Vyc29yLCAiJG9iamVjdCIpOw0KICAgIENo
YXJzZXQgY2hhcnNldCA9IENoYXJzZXRIZWxwZXIubm9ybWFsaXplKElEYXRhVXRpbC5nZXRTdHJp
bmcoY3Vyc29yLCAiJGVuY29kaW5nIikpOw0KDQogICAgaWYgKG9iamVjdCAhPSBudWxsKSBJRGF0
YVV0aWwucHV0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmdIZWxwZXIubm9ybWFsaXplKG9iamVj
dCwgY2hhcnNldCkpOw0KfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgew0KICAgIEV4Y2VwdGlvbkhl
bHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
