<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsNCiAg
ICBDaGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIENoYXJzZXQuY2xh
c3MsICIkY29udGVudC5lbmNvZGluZyIsICIkZW5jb2RpbmciKTsNCg0KICAgIElEYXRhSGVscGVy
LnB1dChjdXJzb3IsICIkY29udGVudC5zdHJpbmciLCBTdHJpbmdIZWxwZXIubm9ybWFsaXplKGNv
bnRlbnQsIGNoYXJzZXQpLCBmYWxzZSk7DQoKICAgIE9iamVjdCBvYmplY3QgPSBJRGF0YUhlbHBl
ci5nZXQoY3Vyc29yLCAiJG9iamVjdCIpOwogICAgaWYgKG9iamVjdCAhPSBudWxsKSB7CiAgICAg
ICAgLy8gc3VwcG9ydCAkb2JqZWN0IGZvciBiYWNrd2FyZHMtY29tcGF0aWJpbGl0eQogICAgICAg
IElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nSGVscGVyLm5vcm1hbGl6
ZShvYmplY3QsIGNoYXJzZXQpLCBmYWxzZSk7CiAgICB9Cn0gY2F0Y2goSU9FeGNlcHRpb24gZXgp
IHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJz
b3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
