<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">drop</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIFN0cmluZyBrZXkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGtl
eSIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURhdGFIZWxwZXIuZ2V0
T3JEZWZhdWx0KGN1cnNvciwgIiRrZXkubGl0ZXJhbD8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7
DQogICAgDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudCIsIElEYXRhSGVs
cGVyLmRyb3AoZG9jdW1lbnQsIGtleSwgbGl0ZXJhbCksIGZhbHNlKTsNCn0gZmluYWxseSB7DQog
ICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
