<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
W10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7CiAgU3Ry
aW5nIGVuY29kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZW5jb2RpbmciKTsK
ICBTdHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsKCiAg
aWYgKGxpc3QgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY29udGVudCIsIGVtaXQo
bGlzdCwgbW9kZSwgZW5jb2RpbmcpKTsKfSBjYXRjaCAoamF2YS5pby5JT0V4Y2VwdGlvbiBleCkg
ewogIHR1bmRyYS5leGNlcHRpb24ucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0
cm95KCk7Cn0=</value>
</Values>
