<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIFN0
cmluZyBkZWxpbWl0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWxpbWl0ZXIi
KTsKICBTdHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNv
ZGluZyIpOwogIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9k
ZSIpOwoKICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgewogICAgSURhdGFDdXJzb3IgZGMgPSBkb2N1
bWVudC5nZXRDdXJzb3IoKTsKICAgIElEYXRhW10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFy
cmF5KGRjLCAicmVjb3JkV2l0aE5vSUQiKTsKICAgIGRjLmRlc3Ryb3koKTsKCiAgICBpZiAobGlz
dCAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRjb250ZW50IiwgZW1pdChsaXN0LCBk
ZWxpbWl0ZXIsIG1vZGUsIGVuY29kaW5nKSk7CiAgfQp9IGNhdGNoIChqYXZhLmlvLklPRXhjZXB0
aW9uIGV4KSB7CiAgdHVuZHJhLmV4Y2VwdGlvbi5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
