<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIFN0
cmluZyBkZWxpbWl0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWxpbWl0ZXIi
KTsKICBTdHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNv
ZGluZyIpOwogIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9k
ZSIpOwoKICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgewogICAgSURhdGFDdXJzb3IgZGMgPSBkb2N1
bWVudC5nZXRDdXJzb3IoKTsKICAgIElEYXRhW10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFy
cmF5KGRjLCAicmVjb3JkcyIpOwogICAgZGMuZGVzdHJveSgpOwoKICAgIGlmIChsaXN0ICE9IG51
bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGNvbnRlbnQiLCBlbWl0KGxpc3QsIGRlbGltaXRl
ciwgbW9kZSwgZW5jb2RpbmcpKTsKICB9Cn0gY2F0Y2ggKGphdmEuaW8uSU9FeGNlcHRpb24gZXgp
IHsKICB0dW5kcmEuZXhjZXB0aW9uLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVz
dHJveSgpOwp9</value>
</Values>
