<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zip</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZSIsIFN0cmluZy5jbGFz
cyk7CiAgICBTdHJpbmcgdGFyZ2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlLnpp
cCIsIFN0cmluZy5jbGFzcyk7CiAgICBib29sZWFuIHJlcGxhY2UgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHJlcGxhY2U/IiwgQm9vbGVhbi5jbGFzcyk7CgogICAgSURhdGFIZWxwZXIucHV0
KGN1cnNvciwgIiRmaWxlLnppcCIsIEZpbGVIZWxwZXIuemlwKHNvdXJjZSwgdGFyZ2V0LCByZXBs
YWNlKSk7Cn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlz
ZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
