<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zip</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBzb3VyY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBGaWxlLmNsYXNzKTsK
ICAgIEZpbGUgdGFyZ2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlLnppcCIsIEZp
bGUuY2xhc3MpOwogICAgYm9vbGVhbiByZXBsYWNlID0gSURhdGFIZWxwZXIuZmlyc3RPckRlZmF1
bHQoY3Vyc29yLCBCb29sZWFuLmNsYXNzLCBmYWxzZSwgIiRmaWxlLnJlbW92ZT8iLCAiJHJlcGxh
Y2U/Iik7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRmaWxlLnppcCIsIEZpbGVIZWxw
ZXIubm9ybWFsaXplKEZpbGVIZWxwZXIuemlwKHNvdXJjZSwgdGFyZ2V0LCByZXBsYWNlKSkpOwp9
IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOwp9
IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
