<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zip</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZSIsIFN0cmluZy5jbGFz
cyk7CiAgICBTdHJpbmcgdGFyZ2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlLnpp
cCIsIFN0cmluZy5jbGFzcyk7CiAgICBib29sZWFuIHJlcGxhY2UgPSBJRGF0YUhlbHBlci5maXJz
dE9yRGVmYXVsdChjdXJzb3IsIEJvb2xlYW4uY2xhc3MsIGZhbHNlLCAiJGZpbGUucmVtb3ZlPyIs
ICIkcmVwbGFjZT8iKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGZpbGUuemlwIiwg
RmlsZUhlbHBlci56aXAoc291cmNlLCB0YXJnZXQsIHJlcGxhY2UpKTsKfSBjYXRjaChJT0V4Y2Vw
dGlvbiBleCkgewogICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICAg
IGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
