<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">trim</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKICAgIFRyYW5zZm9ybWVy
TW9kZSBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRtb2RlIiwgVHJhbnNmb3JtZXJN
b2RlLmNsYXNzKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBJRGF0YUhl
bHBlci50cmltKGxpc3QsIG1vZGUsIHJlY3Vyc2UpLCBmYWxzZSk7Cn0gZmluYWxseSB7DQogICAg
Y3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
