<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">leaves</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKICAgIENsYXNzIGtsYXNz
ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRjbGFzcyIsIENsYXNzLmNsYXNz
LCBPYmplY3QuY2xhc3MpOwoKICAgIE9iamVjdFtdIHZhbHVlcyA9IElEYXRhSGVscGVyLmdldExl
YXZlcyhkb2N1bWVudCwga2xhc3MsIHJlY3Vyc2UpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJz
b3IsICIkdmFsdWVzIiwgdmFsdWVzLCBmYWxzZSwgZmFsc2UpOwp9IGZpbmFsbHkgewogICAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
