<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">leaves</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nW10gY2xhc3NlcyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
Y2xhc3NlcyIsIFN0cmluZ1tdLmNsYXNzKTsKCiAgICBPYmplY3RbXSB2YWx1ZXMgPSBJRGF0YUhl
bHBlci5nZXRMZWFmVmFsdWVzKGRvY3VtZW50LCBDbGFzc0hlbHBlci5mb3JOYW1lKGNsYXNzZXMp
KTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHZhbHVlcyIsIHZhbHVlcywgZmFsc2Us
IGZhbHNlKTsKfSBjYXRjaChDbGFzc05vdEZvdW5kRXhjZXB0aW9uIGV4KSB7CiAgICBFeGNlcHRp
b25IZWxwZXIucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==
</value>
</Values>
