<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">subtract</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUi
KTsNCiAgICBTdHJpbmcgZGF0ZXRpbWVQYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJz
b3IsICIkZGF0ZXRpbWUucGF0dGVybiIpOw0KICAgIC8vIHN1cHBvcnQgJHBhdHRlcm4gdG8gYmUg
YmFja3dhcmRzIGNvbXBhdGlibGUNCiAgICBpZiAoZGF0ZXRpbWVQYXR0ZXJuID09IG51bGwpIGRh
dGV0aW1lUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4iKTsN
CiAgICBTdHJpbmcgZHVyYXRpb24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkdXJh
dGlvbiIpOw0KICAgIFN0cmluZyBkdXJhdGlvblBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KGN1cnNvciwgIiRkdXJhdGlvbi5wYXR0ZXJuIik7DQoNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNv
ciwgIiRkYXRldGltZSIsIHN1YnRyYWN0KGRhdGV0aW1lLCBkYXRldGltZVBhdHRlcm4sIGR1cmF0
aW9uLCBkdXJhdGlvblBhdHRlcm4pKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3ko
KTsNCn0=</value>
</Values>
