<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">subtract</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkYXRldGltZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRhdGV0aW1lIik7CiAg
U3RyaW5nIGRhdGV0aW1lUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRh
dGV0aW1lLnBhdHRlcm4iKTsKICAvLyBzdXBwb3J0ICRwYXR0ZXJuIHRvIGJlIGJhY2t3YXJkcyBj
b21wYXRpYmxlCiAgaWYgKGRhdGV0aW1lUGF0dGVybiA9PSBudWxsKSBkYXRldGltZVBhdHRlcm4g
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7CiAgU3RyaW5nIGR1cmF0
aW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZHVyYXRpb24iKTsKICBTdHJpbmcg
ZHVyYXRpb25QYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZHVyYXRpb24u
cGF0dGVybiIpOwoKICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkYXRldGltZSIsIHN1YnRyYWN0
KGRhdGV0aW1lLCBkYXRldGltZVBhdHRlcm4sIGR1cmF0aW9uLCBkdXJhdGlvblBhdHRlcm4pKTsK
fSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
