<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHVyaSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nLmNsYXNz
KTsKICAgIFN0cmluZyBkZWZhdWx0VmFsdWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN1
YnN0aXR1dGlvbi5kZWZhdWx0IiwgU3RyaW5nLmNsYXNzKTsKICAgIFN1YnN0aXR1dGlvblR5cGUg
bW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3Vic3RpdHV0aW9uLm1vZGUiLCBTdWJz
dGl0dXRpb25UeXBlLmNsYXNzKTsKICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZmlyc3Qo
Y3Vyc29yLCBJRGF0YS5jbGFzcywgIiRwaXBlbGluZSIsICIkc2NvcGUiKTsKCiAgICBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFVSSUhlbHBlci5zdWJzdGl0dXRlKHVyaSwgZGVm
YXVsdFZhbHVlLCBtb2RlLCBzY29wZSA9PSBudWxsID8gcGlwZWxpbmUgOiBzY29wZSksIGZhbHNl
KTsKfSBjYXRjaChVUklTeW50YXhFeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBlci5y
YWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
