<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIENoYXJzZXQgY2hhcnNldCA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNv
ciwgQ2hhcnNldC5jbGFzcywgIiRjb250ZW50LmVuY29kaW5nIiwgIiRlbmNvZGluZyIpOw0KICAg
IE9iamVjdENvbnZlcnRNb2RlIG1vZGUgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIE9iamVj
dENvbnZlcnRNb2RlLmNsYXNzLCAiJGNvbnRlbnQubW9kZSIsICIkbW9kZSIpOw0KDQogICAgaWYg
KGRvY3VtZW50ICE9IG51bGwpIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGNv
bnRlbnQiLCBPYmplY3RIZWxwZXIuY29udmVydChuZXcgSURhdGFZQU1MUGFyc2VyKCkuZW1pdChk
b2N1bWVudCwgY2hhcnNldCksIGNoYXJzZXQsIG1vZGUpKTsNCiAgICB9Cn0gY2F0Y2ggKElPRXhj
ZXB0aW9uIGV4KSB7DQogICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxseSB7
DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
