<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">suffix</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgU3RyaW5nIHN1ZmZpeCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3Vm
Zml4IiwgU3RyaW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdl
dE9yRGVmYXVsdChjdXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAg
ICBib29sZWFuIGZvcmNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRmb3Jj
ZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CiAgICBUcmFuc2Zvcm1lck1vZGUgbW9kZSA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFRyYW5zZm9ybWVyTW9kZS5jbGFzcyk7Cgog
ICAgaWYgKHN1ZmZpeCAhPSBudWxsKSBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxpc3QiLCBJ
RGF0YUhlbHBlci5zdWZmaXgobGlzdCwgc3VmZml4LCBmb3JjZSwgbW9kZSwgcmVjdXJzZSksIGZh
bHNlKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
