<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmRlY29k
ZWQiLCBJRGF0YS5jbGFzcyk7CgogICAgaWYgKGRvY3VtZW50ID09IG51bGwpIHsKICAgICAgICBT
dHJpbmcgc3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcu
Y2xhc3MpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyaW5nIiwgSFRNTEhl
bHBlci5lbmNvZGUoc3RyaW5nKSwgZmFsc2UpOwogICAgfSBlbHNlIHsKICAgICAgICBJRGF0YUhl
bHBlci5wdXQoY3Vyc29yLCAiJGRvY3VtZW50LmVuY29kZWQiLCBIVE1MSGVscGVyLmVuY29kZShk
b2N1bWVudCksIGZhbHNlKTsKICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgp
Ow0KfQ==</value>
</Values>
