<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmRlY29k
ZWQiLCBJRGF0YS5jbGFzcyk7CiAgICBpZiAoZG9jdW1lbnQgPT0gbnVsbCkgewogICAgICAgIFN0
cmluZyBzdHJpbmcgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZy5j
bGFzcyk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzdHJpbmciLCBIVE1MSGVs
cGVyLmVuY29kZShzdHJpbmcpLCBmYWxzZSk7CiAgICB9IGVsc2UgewogICAgICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQuZW5jb2RlZCIsIEhUTUxIZWxwZXIuZW5jb2RlKGRv
Y3VtZW50KSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
