<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">create</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRhY2wubmFtZSIpOwogICAg
U3RyaW5nW10gYWxsb3dlZCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkZ3Jv
dXBzLmFsbG93ZWQiKTsKICAgIFN0cmluZ1tdIGRlbmllZCA9IElEYXRhVXRpbC5nZXRTdHJpbmdB
cnJheShjdXJzb3IsICIkZ3JvdXBzLmRlbmllZCIpOwogICAgYm9vbGVhbiBmb3JjZSA9IEJvb2xl
YW5IZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZm9yY2U/IikpOwoK
ICAgIEFDTEhlbHBlci5jcmVhdGUobmFtZSwgR3JvdXBIZWxwZXIuZmluZE9yQ3JlYXRlKGFsbG93
ZWQpLCBHcm91cEhlbHBlci5maW5kT3JDcmVhdGUoZGVuaWVkKSwgZm9yY2UpOwp9IGZpbmFsbHkg
ewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
