<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatenate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nIHNlcGFyYXRvciA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
c2VwYXJhdG9yIiwgU3RyaW5nLmNsYXNzKTsKICAgIFNhbml0aXphdGlvbiBzYW5pdGl6YXRpb24g
PSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNhbml0aXphdGlvbiIsIFNhbml0aXphdGlvbi5j
bGFzcyk7CgogICAgU3RyaW5nIHJlc3VsdCA9IFN0cmluZ0hlbHBlci5jb25jYXRlbmF0ZShvcGVy
YW5kcywgc2VwYXJhdG9yLCBzYW5pdGl6YXRpb24pOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJz
b3IsICIkc3RyaW5nIiwgcmVzdWx0LCBmYWxzZSk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVz
dHJveSgpOwp9</value>
</Values>
