<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatenate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG91dHB1dFBhcmFtZXRlck5hbWUgPSAiJGNvbmNhdGVuYXRlLnJlc3VsdCI7CiAgICBJRGF0
YSBvcGVyYW5kcyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkY29uY2F0ZW5hdGUub3BlcmFu
ZHMiLCBJRGF0YS5jbGFzcyk7CiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkgewogICAgICAgIG9w
ZXJhbmRzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRvcGVyYW5kcyIsIElEYXRhLmNsYXNz
KTsKICAgICAgICBvdXRwdXRQYXJhbWV0ZXJOYW1lID0gIiRzdHJpbmciOwogICAgfQogICAgU3Ry
aW5nIHNlcGFyYXRvciA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNvciwgU3RyaW5nLmNsYXNzLCAi
JGNvbmNhdGVuYXRlLnNlcGFyYXRvciIsICIkc2VwYXJhdG9yIik7CiAgICBTYW5pdGl6YXRpb24g
c2FuaXRpemF0aW9uID0gSURhdGFIZWxwZXIuZmlyc3QoY3Vyc29yLCBTYW5pdGl6YXRpb24uY2xh
c3MsICIkY29uY2F0ZW5hdGUuc2FuaXRpemF0aW9uIiwgIiRzYW5pdGl6YXRpb24iKTsKCiAgICBT
dHJpbmcgcmVzdWx0ID0gU3RyaW5nSGVscGVyLmNvbmNhdGVuYXRlKG9wZXJhbmRzLCBzZXBhcmF0
b3IsIHNhbml0aXphdGlvbik7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgb3V0cHV0UGFy
YW1ldGVyTmFtZSwgcmVzdWx0LCBmYWxzZSk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJv
eSgpOwp9</value>
</Values>
