<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIka2V5LnNvdXJjZSIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHRhcmdldCA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIka2V5LnRhcmdldCIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURh
dGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRrZXkubGl0ZXJhbD8iLCBCb29sZWFuLmNs
YXNzLCBmYWxzZSk7DQoNCiAgICBJRGF0YUhlbHBlci5jb3B5KHBpcGVsaW5lLCBzb3VyY2UsIHRh
cmdldCwgbGl0ZXJhbCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
