<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">last</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOwoNCiAgICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgew0KICAgICAgICBJRGF0YUN1
cnNvciBkb2N1bWVudEN1cnNvciA9IGRvY3VtZW50LmdldEN1cnNvcigpOw0KICAgICAgICBpZiAo
ZG9jdW1lbnRDdXJzb3IubGFzdCgpKSB7DQogICAgICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vy
c29yLCAiJGtleSIsIGRvY3VtZW50Q3Vyc29yLmdldEtleSgpKTsNCiAgICAgICAgICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkdmFsdWUiLCBkb2N1bWVudEN1cnNvci5nZXRWYWx1ZSgpKTsN
CiAgICAgICAgfQ0KICAgICAgICBkb2N1bWVudEN1cnNvci5kZXN0cm95KCk7DQogICAgfQ0KfSBm
aW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
