<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">last</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIGlm
IChkb2N1bWVudCAhPSBudWxsKSB7CiAgICBJRGF0YUN1cnNvciBkYyA9IGRvY3VtZW50LmdldEN1
cnNvcigpOwogICAgaWYgKGRjLmxhc3QoKSkgewogICAgICBTdHJpbmcga2V5ID0gZGMuZ2V0S2V5
KCk7CiAgICAgIE9iamVjdCB2YWx1ZSA9IGRjLmdldFZhbHVlKCk7CiAgICAgIElEYXRhVXRpbC5w
dXQoY3Vyc29yLCAiJGtleSIsIGtleSk7CiAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHZh
bHVlIiwgdmFsdWUpOwogICAgfQogICAgZGMuZGVzdHJveSgpOwogIH0KfSBmaW5hbGx5IHsKICBj
dXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
