<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unequal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGV4cGVjdGVkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRleHBlY3RlZCIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGFjdHVhbCA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkYWN0dWFsIiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVs
cGVyLmdldChjdXJzb3IsICIkcGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIG1l
c3NhZ2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG1lc3NhZ2UiLCBTdHJpbmcuY2xhc3Mp
Ow0KDQogICAgZXF1YWwoZXhwZWN0ZWQsIGFjdHVhbCwgcGF0dGVybiwgbWVzc2FnZSk7DQp9IGZp
bmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
