<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listify</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGtleSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIka2V5IiwgU3RyaW5nLmNsYXNz
KTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc2NvcGUiLCBJ
RGF0YS5jbGFzcyk7DQogICAgYm9vbGVhbiBzY29wZWQgPSBzY29wZSAhPSBudWxsOw0KDQogICAg
aWYgKHNjb3BlZCkgew0KICAgICAgICBzY29wZSA9IElEYXRhSGVscGVyLmR1cGxpY2F0ZShzY29w
ZSk7DQogICAgfSBlbHNlIHsNCiAgICAgICAgc2NvcGUgPSBwaXBlbGluZTsNCiAgICB9DQoNCiAg
ICBzY29wZSA9IElEYXRhSGVscGVyLmFycmF5aWZ5KHNjb3BlLCBrZXkpOw0KDQogICAgaWYgKHNj
b3BlZCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzY29wZSIsIHNjb3BlKTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
