<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listify</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGtleSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleSIpOw0KICAgIElE
YXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRzY29wZSIpOw0KICAgIGJv
b2xlYW4gc2NvcGVkID0gc2NvcGUgIT0gbnVsbDsNCg0KICAgIGlmIChzY29wZWQpIHsNCiAgICAg
ICAgc2NvcGUgPSBJRGF0YUhlbHBlci5kdXBsaWNhdGUoc2NvcGUpOw0KICAgIH0gZWxzZSB7DQog
ICAgICAgIHNjb3BlID0gcGlwZWxpbmU7DQogICAgfQ0KDQogICAgc2NvcGUgPSBJRGF0YUhlbHBl
ci5hcnJheWlmeShzY29wZSwga2V5KTsNCg0KICAgIGlmIChzY29wZWQpIElEYXRhVXRpbC5wdXQo
Y3Vyc29yLCAiJHNjb3BlIiwgc2NvcGUpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJv
eSgpOw0KfQ==</value>
</Values>
