<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">map</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIE9iamVj
dFtdIGxpc3QgPSBJRGF0YVV0aWwuZ2V0T2JqZWN0QXJyYXkoY3Vyc29yLCAiJGxpc3QiKTsKICBT
dHJpbmcgc2VydmljZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHNlcnZpY2UiKTsK
ICBTdHJpbmcgaW5wdXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRpdGVtLmlucHV0
Iik7CiAgU3RyaW5nIG91dHB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGl0ZW0u
b3V0cHV0Iik7CgogIC8vIGludm9rZSB0aGUgc2VydmljZSBmb3IgZWFjaCBpdGVtIGluIHRoZSBs
aXN0LCBwYXNzaW5nICRpdGVtIGFuZCAkaW5kZXggdmFyaWFibGVzIG9uIGVhY2ggaW52b2NhdGlv
bgogIC8vIGFuZCBjb2xsZWN0IHRoZSByZXR1cm5lZCAkaXRlbSdzIGludG8gYSBuZXcgbGlzdAog
IElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGxpc3QiLCBtYXAobGlzdCwgc2VydmljZSwgcGlwZWxp
bmUsIGlucHV0LCBvdXRwdXQpKTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
