<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">write</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBmaWxlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZmlsZSIpOwogIFN0cmluZyBt
b2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9kZSIpOwogIE9iamVjdCBjb250
ZW50ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudCIpOwogIFN0cmluZyBlbmNvZGlu
ZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGVuY29kaW5nIik7CgogIGZpbGUgPSB3
cml0ZShmaWxlLCBtb2RlLCBjb250ZW50LCBlbmNvZGluZyk7CgogIElEYXRhVXRpbC5wdXQoY3Vy
c29yLCAiJGZpbGUiLCBmaWxlKTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
