<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">uncase</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgTG9jYWxlIGxvY2FsZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJz
b3IsICIkbG9jYWxlIiwgTG9jYWxlLmNsYXNzLCBMb2NhbGUuZ2V0RGVmYXVsdCgpKTsKCiAgICBp
ZiAoZG9jdW1lbnQgIT0gbnVsbCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudCIs
IG5ldyBDYXNlSW5zZW5zaXRpdmVJRGF0YShJRGF0YUhlbHBlci5kdXBsaWNhdGUoZG9jdW1lbnQs
IHRydWUpLCBsb2NhbGUpKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
