<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">condense</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIG91dHB1dFBhcmFtZXRlck5hbWUgPSAiJGNvbmRlbnNlLnJlc3VsdHMiOwogICAgSURhdGEg
b3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbmRlbnNlLm9wZXJhbmRzIiwg
SURhdGEuY2xhc3MpOwogICAgaWYgKG9wZXJhbmRzID09IG51bGwpIHsKICAgICAgICBvcGVyYW5k
cyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkb3BlcmFuZHMiLCBJRGF0YS5jbGFzcyk7CiAg
ICAgICAgb3V0cHV0UGFyYW1ldGVyTmFtZSA9ICIkcmVzdWx0cyI7CiAgICB9CgogICAgaWYgKG9w
ZXJhbmRzID09IG51bGwpIHsKICAgICAgICBTdHJpbmcgc3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0
KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcuY2xhc3MpOwogICAgICAgIElEYXRhSGVscGVyLnB1
dChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nSGVscGVyLmNvbmRlbnNlKHN0cmluZyksIGZhbHNl
KTsKICAgIH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgb3V0cHV0UGFy
YW1ldGVyTmFtZSwgVHJhbnNmb3JtZXIudHJhbnNmb3JtKG9wZXJhbmRzLCBuZXcgQ29uZGVuc2Vy
KHRydWUpKSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsK
fQ==</value>
</Values>
