<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">condense</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG9wZXJhbmRzIiwgSURhdGEu
Y2xhc3MpOwoKICAgIGlmIChvcGVyYW5kcyA9PSBudWxsKSB7CiAgICAgICAgU3RyaW5nIHN0cmlu
ZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nLmNsYXNzKTsKICAg
ICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZ0hlbHBlci5jb25k
ZW5zZShzdHJpbmcpLCBmYWxzZSk7CiAgICB9IGVsc2UgewogICAgICAgIElEYXRhSGVscGVyLnB1
dChjdXJzb3IsICIkcmVzdWx0cyIsIFRyYW5zZm9ybWVyLnRyYW5zZm9ybShvcGVyYW5kcywgbmV3
IENvbmRlbnNlcih0cnVlKSksIGZhbHNlKTsKICAgIH0KfSBmaW5hbGx5IHsKICAgIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
