<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pivot</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
W10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7CiAgU3Ry
aW5nW10ga2V5cyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIka2V5cyIpOwog
IFN0cmluZyBrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRrZXkiKTsKICBTdHJp
bmcgZGVsaW1pdGVyID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVsaW1pdGVyIik7
CgogIGlmIChsaXN0ICE9IG51bGwpIHsKICAgIGlmIChrZXlzICE9IG51bGwpIHsKICAgICAgSURh
dGFVdGlsLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBJRGF0YUhlbHBlci5waXZvdChsaXN0LCBk
ZWxpbWl0ZXIsIGtleXMpKTsKICAgIH0gZWxzZSB7CiAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29y
LCAiJGRvY3VtZW50IiwgSURhdGFIZWxwZXIucGl2b3QobGlzdCwgZGVsaW1pdGVyLCBrZXkpKTsK
ICAgIH0KICB9Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
