<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pivot</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
W10gbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRsaXN0Iik7CiAgU3Ry
aW5nW10ga2V5cyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIka2V5cyIpOwog
IFN0cmluZyBrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRrZXkiKTsKICBTdHJp
bmcgZGVsaW1pdGVyID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVsaW1pdGVyIik7
CgogIGlmIChsaXN0ICE9IG51bGwpIHsKICAgIGlmIChrZXlzICE9IG51bGwpIHsKICAgICAgSURh
dGFVdGlsLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBwaXZvdChsaXN0LCBkZWxpbWl0ZXIsIGtl
eXMpKTsKICAgIH0gZWxzZSB7CiAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGRvY3VtZW50
IiwgcGl2b3QobGlzdCwgZGVsaW1pdGVyLCBrZXkpKTsKICAgIH0KICB9Cn0gZmluYWxseSB7CiAg
Y3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
