<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pad</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIFN0cmluZ1tdLmNs
YXNzKTsKICAgIGludCBsZW5ndGggPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAi
JGxlbmd0aCIsIEludGVnZXIuY2xhc3MsIDApOwogICAgU3RyaW5nIGNoYXJhY3RlciA9IElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkY2hhcmFjdGVyIiwgU3RyaW5nLmNsYXNzKTsKCiAgICBjaGFy
IGMgPSAoY2hhcmFjdGVyID09IG51bGwgfHwgY2hhcmFjdGVyLmxlbmd0aCgpID09IDApID8gJyAn
IDogY2hhcmFjdGVyLmNoYXJBdCgwKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGxp
c3QiLCBTdHJpbmdIZWxwZXIucGFkKGxpc3QsIGxlbmd0aCwgYyksIGZhbHNlKTsKfSBmaW5hbGx5
IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
