<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">values</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGFbXSBsaXN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRsaXN0IiwgSURhdGFbXS5j
bGFzcyk7DQogICAgU3RyaW5nIGtleSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIka2V5Iiwg
U3RyaW5nLmNsYXNzKTsNCiAgICBPYmplY3QgZGVmYXVsdE9iamVjdCA9IElEYXRhSGVscGVyLmdl
dChjdXJzb3IsICIkZGVmYXVsdC5vYmplY3QiKTsNCiAgICBpZiAoZGVmYXVsdE9iamVjdCA9PSBu
dWxsKSBkZWZhdWx0T2JqZWN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkZWZhdWx0LnN0
cmluZyIsIFN0cmluZy5jbGFzcyk7DQoNCiAgICBPYmplY3RbXSB2YWx1ZXMgPSBJRGF0YUhlbHBl
ci5nZXRWYWx1ZXMobGlzdCwga2V5LCBkZWZhdWx0T2JqZWN0KTsNCg0KICAgIElEYXRhSGVscGVy
LnB1dChjdXJzb3IsICIkdmFsdWVzIiwgdmFsdWVzLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
