<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">coalesce</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIE9iamVjdCBkZWZhdWx0VmFsdWUgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIiRkZWZh
dWx0Iik7DQogICAgU3RyaW5nIG1vZGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRt
b2RlIik7DQoNCiAgICBPYmplY3QgcmVzdWx0ID0gQXJyYXlIZWxwZXIuY29hbGVzY2UobGlzdCwg
ZGVmYXVsdFZhbHVlKTsNCg0KICAgIGlmIChyZXN1bHQgIT0gbnVsbCB8fCAobW9kZSAhPSBudWxs
ICYmIG1vZGUuZXF1YWxzKCJudWxsIikpKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRpdGVtIiwg
cmVzdWx0KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
