<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">coalesce</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBPYmplY3QgZGVmYXVsdFZhbHVlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkZWZhdWx0Iik7DQogICAgU3RyaW5nIG1vZGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJG1vZGUiLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgT2JqZWN0IHJlc3VsdCA9IEFycmF5SGVs
cGVyLmNvYWxlc2NlKGxpc3QsIGRlZmF1bHRWYWx1ZSk7DQoNCiAgICBpZiAocmVzdWx0ICE9IG51
bGwgfHwgKG1vZGUgIT0gbnVsbCAmJiBtb2RlLmVxdWFscygibnVsbCIpKSkgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiRpdGVtIiwgcmVzdWx0KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRl
c3Ryb3koKTsNCn0=</value>
</Values>
