<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGlucHV0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudCIpOw0KICAgIFN0
cmluZyBjaGFyc2V0ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZW5jb2RpbmciKTsN
CiAgICBTdHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUiKTsN
Cg0KICAgIE9iamVjdCBvdXRwdXQgPSBPYmplY3RIZWxwZXIuY29udmVydChCeXRlc0hlbHBlci5i
YXNlNjRFbmNvZGUoQnl0ZXNIZWxwZXIubm9ybWFsaXplKGlucHV0LCBjaGFyc2V0KSksIGNoYXJz
ZXQsIG1vZGUpOw0KDQogICAgaWYgKG91dHB1dCAhPSBudWxsKSBJRGF0YVV0aWwucHV0KGN1cnNv
ciwgIiRiYXNlNjQiLCBvdXRwdXQpOw0KfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgew0KICAgIEV4
Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95
KCk7DQp9</value>
</Values>
