<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGlucHV0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjb250ZW50Iik7DQogICAg
Q2hhcnNldCBjaGFyc2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRlbmNvZGluZyIsIENo
YXJzZXQuY2xhc3MpOwogICAgT2JqZWN0Q29udmVydE1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdl
dChjdXJzb3IsICIkbW9kZSIsIE9iamVjdENvbnZlcnRNb2RlLmNsYXNzKTsNCg0KICAgIE9iamVj
dCBvdXRwdXQgPSBPYmplY3RIZWxwZXIuY29udmVydChCeXRlc0hlbHBlci5iYXNlNjRFbmNvZGUo
Qnl0ZXNIZWxwZXIubm9ybWFsaXplKGlucHV0LCBjaGFyc2V0KSksIGNoYXJzZXQsIG1vZGUpOw0K
DQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRiYXNlNjQiLCBvdXRwdXQsIGZhbHNlKTsN
Cn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgp
Ow0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
