<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCiAgICBpbnQgaW5kZXggPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29y
LCAiJGluZGV4IiwgSW50ZWdlci5jbGFzcywgSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNv
ciwgIiRpdGVyYXRpb24iLCBJbnRlZ2VyLmNsYXNzLCAxKSAtIDEpOw0KICAgIGlmIChsaXN0ICE9
IG51bGwgJiYgbGlzdC5sZW5ndGggPiAwKSBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGl0ZW0i
LCBBcnJheUhlbHBlci5nZXQobGlzdCwgaW5kZXgpKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29y
LmRlc3Ryb3koKTsNCn0=</value>
</Values>
