<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIGludCBpbmRleCA9IEludGVnZXJIZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmlu
ZyhjdXJzb3IsICIkaW5kZXgiKSwgSW50ZWdlckhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3Ry
aW5nKGN1cnNvciwgIiRpdGVyYXRpb24iKSwgMSkpOw0KICAgIGlmIChsaXN0ICE9IG51bGwgJiYg
bGlzdC5sZW5ndGggPiAwKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRpdGVtIiwgQXJyYXlIZWxw
ZXIuZ2V0KGxpc3QsIGluZGV4KSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
