<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KICAgIFN0cmluZyBpblBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRw
YXR0ZXJuLmlucHV0Iik7DQogICAgU3RyaW5nIG91dFBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKGN1cnNvciwgIiRwYXR0ZXJuLm91dHB1dCIpOw0KDQogICAgSURhdGFVdGlsLnB1dChjdXJz
b3IsICIkZHVyYXRpb24iLCBEdXJhdGlvbkhlbHBlci5lbWl0KER1cmF0aW9uSGVscGVyLmFkZChE
dXJhdGlvbkhlbHBlci5wYXJzZShsaXN0LCBpblBhdHRlcm4pKSwgb3V0UGF0dGVybikpOw0KfSBm
aW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
