<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIFN0cmluZ1td
LmNsYXNzKTsNCiAgICBTdHJpbmcgaW5QYXR0ZXJuID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwg
IiRwYXR0ZXJuLmlucHV0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgb3V0UGF0dGVybiA9
IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiLCBTdHJpbmcuY2xhc3Mp
Ow0KDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkdXJhdGlvbiIsIER1cmF0aW9uSGVs
cGVyLmVtaXQoRHVyYXRpb25IZWxwZXIuYWRkKER1cmF0aW9uSGVscGVyLnBhcnNlKGxpc3QsIGlu
UGF0dGVybikpLCBvdXRQYXR0ZXJuKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95
KCk7DQp9</value>
</Values>
