<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZSIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGRhdGV0aW1lUGF0dGVybiA9IElEYXRhSGVscGVyLmZp
cnN0KGN1cnNvciwgU3RyaW5nLmNsYXNzLCAiJGRhdGV0aW1lLnBhdHRlcm4iLCAiJHBhdHRlcm4i
KTsNDQogICAgU3RyaW5nIGR1cmF0aW9uID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJh
dGlvbiIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGR1cmF0aW9uUGF0dGVybiA9IElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkZHVyYXRpb24ucGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQoK
ICAgIFN0cmluZyByZXN1bHQgPSBEYXRlVGltZUhlbHBlci5hZGQoZGF0ZXRpbWUsIGRhdGV0aW1l
UGF0dGVybiwgZHVyYXRpb24sIGR1cmF0aW9uUGF0dGVybik7Cg0KICAgIElEYXRhSGVscGVyLnB1
dChjdXJzb3IsICIkZGF0ZXRpbWUiLCByZXN1bHQsIGZhbHNlKTsNCn0gZmluYWxseSB7DQogICAg
Y3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
