<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">trim</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHRyaW0ub3BlcmFuZHMiLCBJ
RGF0YS5jbGFzcyk7CiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkgewogICAgICAgIC8vIHN1cHBv
cnQgJHN0cmluZyBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkKICAgICAgICBTdHJpbmcgc3Ry
aW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcuY2xhc3MpOwog
ICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5nSGVscGVyLnRy
aW0oc3RyaW5nKSwgZmFsc2UpOwogICAgfSBlbHNlIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJHRyaW0ucmVzdWx0cyIsIFRyYW5zZm9ybWVyLnRyYW5zZm9ybShvcGVyYW5kcywg
bmV3IFRyaW1tZXIoVHJhbnNmb3JtZXJNb2RlLlZBTFVFUywgdHJ1ZSkpLCBmYWxzZSk7CiAgICB9
Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
