<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIFN0cmluZyBrZXkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGtl
eSIsIFN0cmluZy5jbGFzcyk7DQogICAgT2JqZWN0IGRlZmF1bHRWYWx1ZSA9IElEYXRhSGVscGVy
LmdldChjdXJzb3IsICIkdmFsdWUuZGVmYXVsdCIsICIkdmFsdWUubGlzdC5kZWZhdWx0IiwgIiRk
ZWZhdWx0Lm9iamVjdCIsICIkZGVmYXVsdC5zdHJpbmciKTsNCiAgICBib29sZWFuIGxpdGVyYWwg
PSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJGtleS5saXRlcmFsPyIsIEJvb2xl
YW4uY2xhc3MsIGZhbHNlKTsNCg0KICAgIE9iamVjdCB2YWx1ZSA9IElEYXRhSGVscGVyLmdldChw
aXBlbGluZSwgZG9jdW1lbnQsIGtleSwgZGVmYXVsdFZhbHVlLCBsaXRlcmFsKTsNCg0KICAgIElE
YXRhSGVscGVyLnB1dChjdXJzb3IsICIkdmFsdWUiLCB2YWx1ZSwgZmFsc2UpOw0KICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkdmFsdWUubGlzdCIsIHZhbHVlLCBPYmplY3RbXS5jbGFzcywg
ZmFsc2UpOwp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
