<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGRvY3VtZW50Iik7
DQogICAgU3RyaW5nIGtleSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleSIpOw0K
ICAgIE9iamVjdCBkZWZhdWx0T2JqZWN0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkZGVmYXVs
dC5vYmplY3QiKTsNCiAgICBpZiAoZGVmYXVsdE9iamVjdCA9PSBudWxsKSBkZWZhdWx0T2JqZWN0
ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVmYXVsdC5zdHJpbmciKTsNCiAgICBi
b29sZWFuIGxpdGVyYWwgPSBCb29sZWFuSGVscGVyLnBhcnNlKElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJGtleS5saXRlcmFsPyIpKTsNCg0KICAgIE9iamVjdCB2YWx1ZSA9IElEYXRhSGVs
cGVyLmdldChwaXBlbGluZSwgZG9jdW1lbnQsIGtleSwgZGVmYXVsdE9iamVjdCwgbGl0ZXJhbCk7
DQoNCiAgICBpZiAodmFsdWUgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkdmFsdWUi
LCB2YWx1ZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
