<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
Ly8gcmVtb3ZlIGlucHV0IGFyZ3VtZW50cyBzbyB0aGF0IHRoZXkgYXJlIG5vdCBpbmNsdWRlZCBp
biBzZXJpYWxpemF0aW9uIG9mIHRoZSBwaXBlbGluZQogICAgQ2hhcnNldCBjaGFyc2V0ID0gSURh
dGFIZWxwZXIucmVtb3ZlKGN1cnNvciwgIiRlbmNvZGluZyIsIENoYXJzZXQuY2xhc3MpOw0KICAg
IE9iamVjdENvbnZlcnRNb2RlIG1vZGUgPSBJRGF0YUhlbHBlci5yZW1vdmUoY3Vyc29yLCAiJG1v
ZGUiLCBPYmplY3RDb252ZXJ0TW9kZS5jbGFzcyk7Cg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJz
b3IsICIkY29udGVudCIsIE9iamVjdEhlbHBlci5jb252ZXJ0KElEYXRhWE1MUGFyc2VyLmdldElu
c3RhbmNlKCkuZW1pdChwaXBlbGluZSwgY2hhcnNldCksIGNoYXJzZXQsIG1vZGUpKTsNCn0gY2F0
Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBm
aW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
