<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGVuY29kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZW5jb2Rpbmci
KTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG1vZGUi
KTsNCiAgICBJRGF0YVV0aWwucmVtb3ZlKGN1cnNvciwgIiRlbmNvZGluZyIpOw0KICAgIElEYXRh
VXRpbC5yZW1vdmUoY3Vyc29yLCAiJG1vZGUiKTsNCg0KICAgIElEYXRhVXRpbC5wdXQoY3Vyc29y
LCAiJGNvbnRlbnQiLCBPYmplY3RIZWxwZXIuY29udmVydChJRGF0YVhNTFBhcnNlci5nZXRJbnN0
YW5jZSgpLmVtaXQocGlwZWxpbmUsIGVuY29kaW5nKSwgZW5jb2RpbmcsIG1vZGUpKTsNCn0gY2F0
Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBm
aW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
