<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiply</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nW10gbGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICIkZGVjaW1h
bHMiKTsNCiAgICBTdHJpbmcgZGVjaW1hbCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAi
JGRlY2ltYWwiKTsNCiAgICBTdHJpbmcgcHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhj
dXJzb3IsICIkcHJlY2lzaW9uIik7DQogICAgU3RyaW5nIHJvdW5kaW5nID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjdXJzb3IsICIkcm91bmRpbmciKTsNCg0KICAgIGlmIChsaXN0ICE9IG51bGwgJiYg
bGlzdC5sZW5ndGggPiAwKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkZWNpbWFsIiwgbXVsdGlw
bHkobGlzdCwgZGVjaW1hbCwgcHJlY2lzaW9uLCByb3VuZGluZykpOw0KfSBmaW5hbGx5IHsNCiAg
ICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
