<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">slice</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbGlzdCIsIE9iamVjdFtd
LmNsYXNzKTsNCgogICAgaWYgKGxpc3QgIT0gbnVsbCkgewogICAgICAgIGludCBpbmRleCA9IElE
YXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkaW5kZXgiLCBJbnRlZ2VyLmNsYXNzLCAw
KTsNCiAgICAgICAgaW50IGxlbmd0aCA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3Is
ICIkbGVuZ3RoIiwgSW50ZWdlci5jbGFzcywgbGlzdC5sZW5ndGgpOw0KDQogICAgICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkbGlzdCIsIEFycmF5SGVscGVyLnNsaWNlKGxpc3QsIGluZGV4
LCBsZW5ndGgpKTsNCiAgICB9Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=
</value>
</Values>
