<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">slice</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0W10gbGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheShjdXJzb3IsICIkbGlzdCIp
Ow0KCiAgICBpZiAobGlzdCAhPSBudWxsKSB7CiAgICAgICAgaW50IGluZGV4ID0gSW50ZWdlckhl
bHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRpbmRleCIpKTsNCiAgICAg
ICAgaW50IGxlbmd0aCA9IEludGVnZXJIZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmluZyhj
dXJzb3IsICIkbGVuZ3RoIiksIGxpc3QubGVuZ3RoKTsNCg0KICAgICAgICBJRGF0YVV0aWwucHV0
KGN1cnNvciwgIiRsaXN0IiwgQXJyYXlIZWxwZXIuc2xpY2UobGlzdCwgaW5kZXgsIGxlbmd0aCkp
Ow0KICAgIH0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
