<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgpib29sZWFuIHJhaXNl
ID0gZmFsc2U7Cgp0cnkgewogICAgU3RyaW5nIGRpcmVjdG9yeSA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkZGlyZWN0b3J5IiwgU3RyaW5nLmNsYXNzKTsKICAgIGJvb2xlYW4gZGVsZXRlU2Vs
ZiA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkZGVsZXRlPyIsIEJvb2xlYW4u
Y2xhc3MsIGZhbHNlKTsKICAgIHJhaXNlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNv
ciwgIiRyYWlzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7CgogICAgRGlyZWN0b3J5SGVscGVy
LmNvbXBhY3QoRmlsZUhlbHBlci5jb25zdHJ1Y3QoZGlyZWN0b3J5KSwgZGVsZXRlU2VsZik7Cn0g
Y2F0Y2goSU9FeGNlcHRpb24gZXgpIHsKICAgaWYgKHJhaXNlKSBFeGNlcHRpb25IZWxwZXIucmFp
c2UoZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
