<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgpib29sZWFuIHJhaXNl
ID0gZmFsc2U7Cgp0cnkgewogICAgRmlsZSBkaXJlY3RvcnkgPSBJRGF0YUhlbHBlci5nZXQoY3Vy
c29yLCAiJGRpcmVjdG9yeSIsIEZpbGUuY2xhc3MpOwogICAgYm9vbGVhbiBkZWxldGVTZWxmID0g
SURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRkZWxldGU/IiwgQm9vbGVhbi5jbGFz
cywgZmFsc2UpOwogICAgcmFpc2UgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAi
JHJhaXNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBEaXJlY3RvcnlIZWxwZXIuY29t
cGFjdChkaXJlY3RvcnksIGRlbGV0ZVNlbGYpOwp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7CiAg
IGlmIChyYWlzZSkgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICAgIGN1
cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
