<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compact</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgaW5wdXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOw0KICAgIGJvb2xlYW4gcmVjdXJzZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChj
dXJzb3IsICIkcmVjdXJzZT8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7DQoKICAgIGlmIChpbnB1
dCAhPSBudWxsKSB7CiAgICAgICAgSURhdGEgb3V0cHV0ID0gSURhdGFIZWxwZXIuY29tcGFjdChp
bnB1dCwgcmVjdXJzZSk7CiAgICAgICAgaWYgKG91dHB1dCA9PSBudWxsKSBvdXRwdXQgPSBJRGF0
YUZhY3RvcnkuY3JlYXRlKCk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1
bWVudCIsIG91dHB1dCk7DQogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7
DQp9</value>
</Values>
