<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBkYXRldGltZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRhdGV0aW1lIik7CiAg
U3RyaW5nIGluUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4u
aW5wdXQiKTsKICBTdHJpbmdbXSBpblBhdHRlcm5zID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5
KGN1cnNvciwgIiRwYXR0ZXJucy5pbnB1dCIpOwogIFN0cmluZyBvdXRQYXR0ZXJuID0gSURhdGFV
dGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGF0dGVybi5vdXRwdXQiKTsKCiAgaWYgKGRhdGV0aW1l
ICE9IG51bGwpIHsKICAgIGlmIChpblBhdHRlcm5zID09IG51bGwpIHsKICAgICAgZGF0ZXRpbWUg
PSBmb3JtYXQoZGF0ZXRpbWUsIGluUGF0dGVybiwgb3V0UGF0dGVybik7CiAgICB9IGVsc2Ugewog
ICAgICBkYXRldGltZSA9IGZvcm1hdChkYXRldGltZSwgaW5QYXR0ZXJucywgb3V0UGF0dGVybik7
CiAgICB9CiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRkYXRldGltZSIsIGRhdGV0aW1lKTsK
ICB9Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
