<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHBhcmVudCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhcmVudCIpOw0K
ICAgIFN0cmluZ1tdIGNoaWxkcmVuID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwg
IiRjaGlsZHJlbiIpOwoKICAgIGlmIChjaGlsZHJlbiA9PSBudWxsKSB7CiAgICAgICAgU3RyaW5n
IGNoaWxkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkY2hpbGQiKTsNCiAgICAgICAg
aWYgKGNoaWxkICE9IG51bGwpIHsKICAgICAgICAgICAgY2hpbGRyZW4gPSBuZXcgU3RyaW5nWzFd
OwogICAgICAgICAgICBjaGlsZHJlblswXSA9IGNoaWxkOwogICAgICAgIH0KICAgIH0KCiAgICBp
ZiAocGFyZW50ICE9IG51bGwpIHsKICAgICAgICBjaGlsZHJlbiA9IEFycmF5SGVscGVyLnByZXBl
bmQoY2hpbGRyZW4sIHBhcmVudCwgU3RyaW5nLmNsYXNzKTsKICAgIH0KCiAgICBTdHJpbmcgcGF0
aCA9IERpcmVjdG9yeUhlbHBlci5qb2luKGNoaWxkcmVuKTsKDQogICAgaWYgKHBhdGggIT0gbnVs
bCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkdXJpIiwgcGF0aCk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
