<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">join</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHBhcmVudCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcGFyZW50IiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmdbXSBjaGlsZHJlbiA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkY2hpbGRyZW4iLCBTdHJpbmdbXS5jbGFzcyk7CgogICAgaWYgKGNoaWxkcmVuID09IG51bGwp
IHsKICAgICAgICBTdHJpbmcgY2hpbGQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNoaWxk
IiwgU3RyaW5nLmNsYXNzKTsNCiAgICAgICAgaWYgKGNoaWxkICE9IG51bGwpIHsKICAgICAgICAg
ICAgY2hpbGRyZW4gPSBuZXcgU3RyaW5nWzFdOwogICAgICAgICAgICBjaGlsZHJlblswXSA9IGNo
aWxkOwogICAgICAgIH0KICAgIH0KCiAgICBpZiAocGFyZW50ICE9IG51bGwpIHsKICAgICAgICBj
aGlsZHJlbiA9IEFycmF5SGVscGVyLnByZXBlbmQoY2hpbGRyZW4sIHBhcmVudCwgU3RyaW5nLmNs
YXNzKTsKICAgIH0KCiAgICBTdHJpbmcgcGF0aCA9IERpcmVjdG9yeUhlbHBlci5qb2luKGNoaWxk
cmVuKTsKCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHVyaSIsIHBhdGgsIGZhbHNlKTsN
Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
