<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">coalesce</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHggPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0cmluZy54IiwgU3RyaW5nLmNs
YXNzKTsNCiAgICBTdHJpbmcgeSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nLnki
LCBTdHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRtb2RlIiwgU3RyaW5nLmNsYXNzKTsNCg0KICAgIFN0cmluZyByZXN1bHQgPSB0dW5kcmEu
b2JqZWN0LmNvYWxlc2NlKHgsIHkpOw0KDQogICAgaWYgKHJlc3VsdCAhPSBudWxsIHx8IChtb2Rl
ICE9IG51bGwgJiYgbW9kZS5lcXVhbHMoIm51bGwiKSkpIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
ICIkc3RyaW5nIiwgcmVzdWx0KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0=</value>
</Values>
