<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">coalesce</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyB4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc3RyaW5nLngiKTsKICBTdHJpbmcg
eSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHN0cmluZy55Iik7CiAgU3RyaW5nIG1v
ZGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRtb2RlIik7CgogIFN0cmluZyByZXN1
bHQgPSB0dW5kcmEub2JqZWN0LmNvYWxlc2NlKHgsIHkpOwoKICBpZiAocmVzdWx0ICE9IG51bGwg
fHwgKG1vZGUgIT0gbnVsbCAmJiBtb2RlLmVxdWFscygibnVsbCIpKSkgSURhdGFVdGlsLnB1dChj
dXJzb3IsICIkc3RyaW5nIiwgcmVzdWx0KTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgp
Owp9</value>
</Values>
