<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmVuY29k
ZWQiLCBJRGF0YS5jbGFzcyk7CgogICAgaWYgKGRvY3VtZW50ID09IG51bGwpIHsKICAgICAgICBT
dHJpbmcgc3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJpbmcu
Y2xhc3MpOw0KICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIsIEhUTUxI
ZWxwZXIuZGVjb2RlKHN0cmluZyksIGZhbHNlKTsNCiAgICB9IGVsc2UgewogICAgICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQuZGVjb2RlZCIsIEhUTUxIZWxwZXIuZGVjb2Rl
KGRvY3VtZW50KSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95
KCk7DQp9</value>
</Values>
