<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">subtract</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyB4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVjaW1hbC54Iik7CiAgU3RyaW5n
IHkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWNpbWFsLnkiKTsKICBTdHJpbmcg
cHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcHJlY2lzaW9uIik7CiAg
U3RyaW5nIHJvdW5kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcm91bmRpbmci
KTsKCiAgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHN1YnRyYWN0KHgsIHksIHBy
ZWNpc2lvbiwgcm91bmRpbmcpKTsKfSBmaW5hbGx5IHsKICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
