<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGtleSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGtleSIpOw0KICAgIE9i
amVjdCBkZWZhdWx0T2JqZWN0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkZGVmYXVsdC5vYmpl
Y3QiKTsNCiAgICBpZiAoZGVmYXVsdE9iamVjdCA9PSBudWxsKSBkZWZhdWx0T2JqZWN0ID0gSURh
dGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVmYXVsdC5zdHJpbmciKTsNCiAgICBib29sZWFu
IGxpdGVyYWwgPSBCb29sZWFuSGVscGVyLnBhcnNlKElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJGtleS5saXRlcmFsPyIpKTsNCg0KICAgIE9iamVjdCB2YWx1ZSA9IElEYXRhSGVscGVyLmdl
dChwaXBlbGluZSwga2V5LCBkZWZhdWx0T2JqZWN0LCBsaXRlcmFsKTsNCiAgICANCiAgICBpZiAo
dmFsdWUgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkdmFsdWUiLCB2YWx1ZSk7DQp9
IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
