<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGtleSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIka2V5IiwgU3RyaW5nLmNsYXNz
KTsNCiAgICBPYmplY3QgZGVmYXVsdE9iamVjdCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
ZGVmYXVsdC5vYmplY3QiKTsNCiAgICBpZiAoZGVmYXVsdE9iamVjdCA9PSBudWxsKSBkZWZhdWx0
T2JqZWN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkZWZhdWx0LnN0cmluZyIsIFN0cmlu
Zy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0
KGN1cnNvciwgIiRrZXkubGl0ZXJhbD8iLCBCb29sZWFuLmNsYXNzLCBmYWxzZSk7DQoNCiAgICBP
YmplY3QgdmFsdWUgPSBJRGF0YUhlbHBlci5nZXQocGlwZWxpbmUsIGtleSwgZGVmYXVsdE9iamVj
dCwgbGl0ZXJhbCk7DQogICAgDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiR2YWx1ZSIs
IHZhbHVlLCBmYWxzZSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
