<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">instance</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoKdHJ5IHsNCiAgICBP
YmplY3Qgb2JqZWN0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRvYmplY3QiKTsNCiAgICBT
dHJpbmcgY2xhc3NOYW1lID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjbGFzcyIsIFN0cmlu
Zy5jbGFzcyk7DQoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkaW5zdGFuY2U/IiwgaW5z
dGFuY2Uob2JqZWN0LCBDbGFzcy5mb3JOYW1lKGNsYXNzTmFtZSkpLCBTdHJpbmcuY2xhc3MpOw0K
fSBjYXRjaChDbGFzc05vdEZvdW5kRXhjZXB0aW9uIGV4KSB7CiAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJGluc3RhbmNlPyIsICJmYWxzZSIpOwp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5k
ZXN0cm95KCk7DQp9</value>
</Values>
