<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">equal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZzEgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0cmluZy54IiwgU3Ry
aW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgc3RyaW5nMiA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkc3RyaW5nLnkiLCBTdHJpbmcuY2xhc3MpOw0KCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29y
LCAiJGVxdWFsPyIsIE1JTUVUeXBlSGVscGVyLmVxdWFsKHN0cmluZzEsIHN0cmluZzIpLCBTdHJp
bmcuY2xhc3MpOw0KfSBjYXRjaChNaW1lVHlwZVBhcnNlRXhjZXB0aW9uIGV4KSB7DQogICAgRXhj
ZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3ko
KTsNCn0=</value>
</Values>
