<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">negate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGR1cmF0aW9uID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJhdGlvbiIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIGluUGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJz
b3IsICIkcGF0dGVybi5pbnB1dCIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIG91dFBhdHRl
cm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHBhdHRlcm4ub3V0cHV0IiwgU3RyaW5nLmNs
YXNzKTsNCg0KICAgIGR1cmF0aW9uID0gRHVyYXRpb25IZWxwZXIuZW1pdChEdXJhdGlvbkhlbHBl
ci5uZWdhdGUoRHVyYXRpb25IZWxwZXIucGFyc2UoZHVyYXRpb24sIGluUGF0dGVybikpLCBvdXRQ
YXR0ZXJuKTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZHVyYXRpb24iLCBkdXJh
dGlvbiwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
