<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIG5hbWUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJG5hbWUiLCBTdHJpbmcuY2xh
c3MpOwogICAgU3RyaW5nIHNlcnZpY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNlcnZp
Y2UiLCBTdHJpbmcuY2xhc3MpOwogICAgU3RyaW5nIGZpbHRlciA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkZmlsdGVyIiwgU3RyaW5nLmNsYXNzKTsNCg0KICAgIElEYXRhSGVscGVyLnB1dChj
dXJzb3IsICIkc2NoZWR1bGVzIiwgU2NoZWR1bGVIZWxwZXIubGlzdChuYW1lLCBzZXJ2aWNlLCBm
aWx0ZXIsIHBpcGVsaW5lKSwgZmFsc2UsIGZhbHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29y
LmRlc3Ryb3koKTsNCn0=</value>
</Values>
