<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purge</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBkaXJlY3RvcnkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRpcmVjdG9yeSIsIEZpbGUu
Y2xhc3MpOwogICAgU3RyaW5nIGR1cmF0aW9uU3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkdXJhdGlvbiIsIFN0cmluZy5jbGFzcyk7CiAgICBTdHJpbmcgZHVyYXRpb25QYXR0ZXJu
ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJhdGlvbi5wYXR0ZXJuIiwgU3RyaW5nLmNs
YXNzKTsKCiAgICBEdXJhdGlvbiBkdXJhdGlvbiA9IER1cmF0aW9uSGVscGVyLnBhcnNlKGR1cmF0
aW9uU3RyaW5nLCBkdXJhdGlvblBhdHRlcm4pOwogICAgYm9vbGVhbiBzaG91bGRQdXJnZSA9IHNo
b3VsZFB1cmdlKGRpcmVjdG9yeSwgZHVyYXRpb24pOwoKICAgIGlmIChzaG91bGRQdXJnZSkgewog
ICAgICAgIGxvbmcgY291bnQgPSBEaXJlY3RvcnlIZWxwZXIucHVyZ2UoZGlyZWN0b3J5LCBkdXJh
dGlvbiwgbnVsbCwgZmFsc2UpOwogICAgICAgIGhhc1B1cmdlZChkaXJlY3RvcnkpOwogICAgICAg
IElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkY291bnQiLCBjb3VudCwgU3RyaW5nLmNsYXNzKTsK
ICAgIH0KCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHB1cmdlZD8iLCBzaG91bGRQdXJn
ZSwgU3RyaW5nLmNsYXNzKTsKfSBjYXRjaChGaWxlTm90Rm91bmRFeGNlcHRpb24gZXgpIHsKICAg
IEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJv
eSgpOwp9</value>
</Values>
