<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purge</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGRpcmVjdG9yeSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZGlyZWN0b3J5IiwgU3Ry
aW5nLmNsYXNzKTsKICAgIFN0cmluZyBkdXJhdGlvblN0cmluZyA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkZHVyYXRpb24iLCBTdHJpbmcuY2xhc3MpOwogICAgU3RyaW5nIGR1cmF0aW9uUGF0
dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZHVyYXRpb24ucGF0dGVybiIsIFN0cmlu
Zy5jbGFzcyk7CgogICAgRHVyYXRpb24gZHVyYXRpb24gPSBEdXJhdGlvbkhlbHBlci5wYXJzZShk
dXJhdGlvblN0cmluZywgZHVyYXRpb25QYXR0ZXJuKTsKICAgIGRpcmVjdG9yeSA9IEZpbGVIZWxw
ZXIubm9ybWFsaXplKGRpcmVjdG9yeSk7CiAgICBib29sZWFuIHNob3VsZFB1cmdlID0gc2hvdWxk
UHVyZ2UoZGlyZWN0b3J5LCBkdXJhdGlvbik7CgogICAgaWYgKHNob3VsZFB1cmdlKSB7CiAgICAg
ICAgbG9uZyBjb3VudCA9IERpcmVjdG9yeUhlbHBlci5wdXJnZShkaXJlY3RvcnksIGR1cmF0aW9u
LCBudWxsLCBmYWxzZSk7CiAgICAgICAgaGFzUHVyZ2VkKGRpcmVjdG9yeSk7CiAgICAgICAgSURh
dGFIZWxwZXIucHV0KGN1cnNvciwgIiRjb3VudCIsIGNvdW50LCBTdHJpbmcuY2xhc3MpOwogICAg
fQoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcHVyZ2VkPyIsIHNob3VsZFB1cmdlLCBT
dHJpbmcuY2xhc3MpOwp9IGNhdGNoKEZpbGVOb3RGb3VuZEV4Y2VwdGlvbiBleCkgewogICAgRXhj
ZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
