<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ensure</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHRyeVNlcnZpY2UgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzZXJ2aWNl
Iik7DQogICAgU3RyaW5nIGNhdGNoU2VydmljZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29y
LCAiJGNhdGNoIik7DQogICAgU3RyaW5nIGZpbmFsbHlTZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0
cmluZyhjdXJzb3IsICIkZmluYWxseSIpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFVdGlsLmdl
dElEYXRhKGN1cnNvciwgIiRwaXBlbGluZSIpOw0KICAgIGJvb2xlYW4gc2NvcGVkID0gc2NvcGUg
IT0gbnVsbDsNCg0KICAgIHNjb3BlID0gU2VydmljZUhlbHBlci5lbnN1cmUodHJ5U2VydmljZSwg
Y2F0Y2hTZXJ2aWNlLCBmaW5hbGx5U2VydmljZSwgc2NvcGVkID8gc2NvcGUgOiBwaXBlbGluZSk7
DQoNCiAgICBpZiAoc2NvcGVkKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRwaXBlbGluZSIsIHNj
b3BlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
