<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ensure</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHRyeVNlcnZpY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHNlcnZpY2UiLCBT
dHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyBjYXRjaFNlcnZpY2UgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJGNhdGNoIiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgZmluYWxseVNlcnZp
Y2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbmFsbHkiLCBTdHJpbmcuY2xhc3MpOw0K
ICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRwaXBlbGluZSIsIElE
YXRhLmNsYXNzKTsNCiAgICBib29sZWFuIHNjb3BlZCA9IHNjb3BlICE9IG51bGw7DQoNCiAgICBz
Y29wZSA9IFNlcnZpY2VIZWxwZXIuZW5zdXJlKHRyeVNlcnZpY2UsIGNhdGNoU2VydmljZSwgZmlu
YWxseVNlcnZpY2UsIHNjb3BlZCA/IHNjb3BlIDogcGlwZWxpbmUpOw0KDQogICAgaWYgKHNjb3Bl
ZCkgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRwaXBlbGluZSIsIHNjb3BlKTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
