<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ensure</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgc2NvcGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHBpcGVsaW5lIiwgSURhdGEuY2xh
c3MpOwogICAgYm9vbGVhbiBzY29wZWQgPSBzY29wZSAhPSBudWxsOwogICAgaWYgKCFzY29wZWQp
IHNjb3BlID0gSURhdGFIZWxwZXIuY2xvbmUocGlwZWxpbmUsICIkc2VydmljZSIsICIkY2F0Y2gi
LCAiJGZpbmFsbHkiKTsKCiAgICBTdHJpbmcgdHJ5U2VydmljZSA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkc2VydmljZSIsIFN0cmluZy5jbGFzcyk7CiAgICBTdHJpbmcgY2F0Y2hTZXJ2aWNl
ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjYXRjaCIsIFN0cmluZy5jbGFzcyk7CiAgICBT
dHJpbmcgZmluYWxseVNlcnZpY2UgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbmFsbHki
LCBTdHJpbmcuY2xhc3MpOwoKICAgIHNjb3BlID0gU2VydmljZUhlbHBlci5lbnN1cmUodHJ5U2Vy
dmljZSwgY2F0Y2hTZXJ2aWNlLCBmaW5hbGx5U2VydmljZSwgc2NvcGUpOwoKICAgIGlmIChzY29w
ZWQpIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHBpcGVsaW5lIiwgc2NvcGUp
OwogICAgfSBlbHNlIHsKICAgICAgICBJRGF0YUhlbHBlci5tZXJnZUludG8ocGlwZWxpbmUsIHNj
b3BlKTsKICAgIH0KfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
