<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">maximum</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJG9wZXJhbmRzIik7
CiAgICBTdHJpbmdbXSBsaXN0ID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGN1cnNvciwgIiRk
ZWNpbWFscyIpOw0KICAgIFN0cmluZyBwcmVjaXNpb24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRwcmVjaXNpb24iKTsNCiAgICBTdHJpbmcgcm91bmRpbmcgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKGN1cnNvciwgIiRyb3VuZGluZyIpOw0KCiAgICAvLyBzdXBwb3J0ICRkZWNpbWFscyBp
bnB1dCBmb3IgYmFja3dhcmRzLWNvbXBhdGliaWxpdHkKICAgIGlmIChvcGVyYW5kcyA9PSBudWxs
ICYmIGxpc3QgIT0gbnVsbCkgewogICAgICAgIElEYXRhTWFwIG1hcCA9IG5ldyBJRGF0YU1hcCgp
OwogICAgICAgIG1hcC5wdXQoIiRkZWNpbWFscyIsIGxpc3QpOwogICAgICAgIG9wZXJhbmRzID0g
bWFwOwogICAgfQoNCiAgICBTdHJpbmcgcmVzdWx0ID0gQmlnRGVjaW1hbEhlbHBlci5lbWl0KEJp
Z0RlY2ltYWxIZWxwZXIucm91bmQoQmlnRGVjaW1hbEhlbHBlci5tYXhpbXVtKEJpZ0RlY2ltYWxI
ZWxwZXIubm9ybWFsaXplKElEYXRhSGVscGVyLmdldExlYWZWYWx1ZXMob3BlcmFuZHMpKSksIHBy
ZWNpc2lvbiwgcm91bmRpbmcpKTsNCg0KICAgIGlmIChyZXN1bHQgIT0gbnVsbCkgSURhdGFVdGls
LnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHJlc3VsdCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNv
ci5kZXN0cm95KCk7DQp9</value>
</Values>
