<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">respond</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
aW50IGNvZGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvZGUiLCBJbnRlZ2VyLmNsYXNz
KTsNCiAgICBTdHJpbmcgbWVzc2FnZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbWVzc2Fn
ZSIsIFN0cmluZy5jbGFzcyk7DQogICAgSURhdGEgaGVhZGVycyA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkaGVhZGVycyIsIElEYXRhLmNsYXNzKTsNCiAgICBPYmplY3QgY29udGVudCA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkY29udGVudCIpOw0KICAgIFN0cmluZyBjb250ZW50VHlw
ZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkY29udGVudC50eXBlIiwgU3RyaW5nLmNsYXNz
KTsNCiAgICBDaGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIENoYXJz
ZXQuY2xhc3MsICIkY29udGVudC5lbmNvZGluZyIsICIkZW5jb2RpbmciKTsNCg0KICAgIFNlcnZp
Y2VIZWxwZXIucmVzcG9uZChjb2RlLCBtZXNzYWdlLCBoZWFkZXJzLCBJbnB1dFN0cmVhbUhlbHBl
ci5ub3JtYWxpemUoY29udGVudCwgY2hhcnNldCksIGNvbnRlbnRUeXBlLCBjaGFyc2V0KTsNCn0g
ZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
