<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIiRjb250ZW50Iik7DQogICAg
U3RyaW5nIGNoYXJzZXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNvZGluZyIp
Ow0KDQogICAgaWYgKGNvbnRlbnQgIT0gbnVsbCkgew0KICAgICAgICBJRGF0YVV0aWwucHV0KGN1
cnNvciwgIiRkb2N1bWVudCIsIElEYXRhSlNPTlBhcnNlci5nZXRJbnN0YW5jZSgpLnBhcnNlKElu
cHV0U3RyZWFtSGVscGVyLm5vcm1hbGl6ZShjb250ZW50LCBDaGFyc2V0SGVscGVyLm5vcm1hbGl6
ZShjaGFyc2V0KSksIENoYXJzZXRIZWxwZXIubm9ybWFsaXplKGNoYXJzZXQpKSk7DQogICAgfQ0K
fSBjYXRjaCAoSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgp
Ow0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
