<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parse</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsNCiAg
ICBDaGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGVuY29kaW5nIiwg
Q2hhcnNldC5jbGFzcyk7DQoNCiAgICBpZiAoY29udGVudCAhPSBudWxsKSB7DQogICAgICAgIElE
YXRhVXRpbC5wdXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGFKU09OUGFyc2VyLmdldEluc3Rh
bmNlKCkucGFyc2UoSW5wdXRTdHJlYW1IZWxwZXIubm9ybWFsaXplKGNvbnRlbnQsIGNoYXJzZXQp
LCBjaGFyc2V0KSk7DQogICAgfQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNl
cHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgp
Ow0KfQ==</value>
</Values>
