<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">create</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGtleUNsYXNzID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIka2V5LmNsYXNzIik7
CiAgICBTdHJpbmcgdmFsdWVDbGFzcyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHZh
bHVlLmNsYXNzIik7CiAgICBjcmVhdGUocGlwZWxpbmUsIGtleUNsYXNzID09IG51bGwgPyBPYmpl
Y3QuY2xhc3MgOiBDbGFzcy5mb3JOYW1lKGtleUNsYXNzKSwgdmFsdWVDbGFzcyA9PSBudWxsID8g
T2JqZWN0LmNsYXNzIDogQ2xhc3MuZm9yTmFtZSh2YWx1ZUNsYXNzKSk7Cn0gY2F0Y2ggKENsYXNz
Tm90Rm91bmRFeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7Cn0g
ZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
