<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7CiAg
ICBJRGF0YSBzY29wZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIkc2NvcGUiKTsKICAg
IElEYXRhW10gYXJndW1lbnRzID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoY3Vyc29yLCAiJGFy
Z3VtZW50cyIpOwogICAgSURhdGEgbG9jYWxlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwg
IiRsb2NhbGUiKTsKCiAgICBTdHJpbmcgcmVzdWx0ID0gU3RyaW5nSGVscGVyLmZvcm1hdChMb2Nh
bGVIZWxwZXIudG9Mb2NhbGUobG9jYWxlKSwgcGF0dGVybiwgc2NvcGUgPT0gbnVsbCA/IHBpcGVs
aW5lIDogc2NvcGUsIGFyZ3VtZW50cyk7CgogICAgaWYgKHJlc3VsdCAhPSBudWxsKSBJRGF0YVV0
aWwucHV0KGN1cnNvciwgIiRzdHJpbmciLCByZXN1bHQpOwp9IGZpbmFsbHkgewogICAgY3Vyc29y
LmRlc3Ryb3koKTsKfQ==</value>
</Values>
