<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">format</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHBhdHRlcm4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7CiAg
ICBJRGF0YVtdIGFyZ3VtZW50cyA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGN1cnNvciwgIiRh
cmd1bWVudHMiKTsKICAgIElEYXRhIGxvY2FsZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3Is
ICIkbG9jYWxlIik7CgogICAgU3RyaW5nIHJlc3VsdCA9IFN0cmluZ0hlbHBlci5mb3JtYXQoTG9j
YWxlSGVscGVyLnRvTG9jYWxlKGxvY2FsZSksIHBhdHRlcm4sIHBpcGVsaW5lLCBhcmd1bWVudHMp
OwoKICAgIGlmIChyZXN1bHQgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkc3RyaW5n
IiwgcmVzdWx0KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
