<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmJvb2xlYW4gdmFs
aWQgPSBmYWxzZSwgcmFpc2UgPSBmYWxzZTsNCnRyeSB7DQogICAgU3RyaW5nIGRhdGV0aW1lID0g
SURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUiKTsNCiAgICBTdHJpbmcgcGF0
dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHBhdHRlcm4iKTsNCiAgICByYWlz
ZSA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcmFp
c2U/IikpOw0KDQogICAgLy8gYXR0ZW1wdCB0byBwYXJzZSB0aGUgZGF0ZXRpbWUgc3RyaW5nLCBp
ZiBubyBleGNlcHRpb24gaXMgdGhyb3duIHRoZW4gdGhlIHN0cmluZyBpcyB2YWxpZA0KICAgIERh
dGVUaW1lSGVscGVyLnBhcnNlKGRhdGV0aW1lLCBwYXR0ZXJuKTsNCiAgICB2YWxpZCA9IHRydWU7
Cn0gY2F0Y2ggKElsbGVnYWxBcmd1bWVudEV4Y2VwdGlvbiBleCkgew0KICAgIGlmIChyYWlzZSkg
RXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxseSB7DQogICAgSURhdGFVdGlsLnB1
dChjdXJzb3IsICIkdmFsaWQ/IiwgIiIgKyB2YWxpZCk7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsN
Cn0=</value>
</Values>
