<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmJvb2xlYW4gdmFs
aWQgPSB0cnVlLCByYWlzZSA9IGZhbHNlOw0KdHJ5IHsNCiAgU3RyaW5nIGRhdGV0aW1lID0gSURh
dGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGF0ZXRpbWUiKTsNCiAgU3RyaW5nIHBhdHRlcm4g
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwYXR0ZXJuIik7DQogIHJhaXNlID0gQm9v
bGVhbkhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRyYWlzZT8iKSk7
DQoNCiAgLy8gYXR0ZW1wdCB0byBwYXJzZSB0aGUgZGF0ZXRpbWUgc3RyaW5nLCBpZiBubyBleGNl
cHRpb24gaXMgdGhyb3duIHRoZW4gdGhlIHN0cmluZyBpcyB2YWxpZA0KICBwYXJzZShkYXRldGlt
ZSwgcGF0dGVybik7DQp9IGNhdGNoIChJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24gZXgpIHsNCiAg
aWYgKHJhaXNlKSB0dW5kcmEuZXhjZXB0aW9uLnJhaXNlKGV4KTsNCiAgdmFsaWQgPSBmYWxzZTsN
Cn0gZmluYWxseSB7DQogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHZhbGlkPyIsICIiICsgdmFs
aWQpOw0KICBjdXJzb3IuZGVzdHJveSgpOw0KfQ0K</value>
</Values>
