<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">divide</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRpdmlkZW5kID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGl2aWRlbmQi
KTsKICAgIFN0cmluZyBkaXZpc29yID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGl2
aXNvciIpOwoKICAgIC8vIHN1cHBvcnQgJGRlY2ltYWwueCBhbmQgJGRlY2ltYWwueSBpbnB1dHMg
Zm9yIGJhY2t3YXJkcy1jb21wYXRpYmlsaXR5CiAgICBpZiAoZGl2aWRlbmQgPT0gbnVsbCAmJiBk
aXZpc29yID09IG51bGwpIHsKICAgICAgICBkaXZpZGVuZCA9IElEYXRhVXRpbC5nZXRTdHJpbmco
Y3Vyc29yLCAiJGRlY2ltYWwueCIpOwogICAgICAgIGRpdmlzb3IgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKGN1cnNvciwgIiRkZWNpbWFsLnkiKTsKICAgIH0KCiAgICBTdHJpbmcgcHJlY2lzaW9uID0g
SURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcHJlY2lzaW9uIik7DQogICAgU3RyaW5nIHJv
dW5kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcm91bmRpbmciKTsNCgogICAg
U3RyaW5nIHJlc3VsdCA9IEJpZ0RlY2ltYWxIZWxwZXIuZW1pdChCaWdEZWNpbWFsSGVscGVyLmRp
dmlkZShCaWdEZWNpbWFsSGVscGVyLnBhcnNlKGRpdmlkZW5kKSwgQmlnRGVjaW1hbEhlbHBlci5w
YXJzZShkaXZpc29yKSwgcHJlY2lzaW9uLCByb3VuZGluZykpOwoKICAgIGlmIChyZXN1bHQgIT0g
bnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkZGVjaW1hbCIsIHJlc3VsdCk7DQp9IGZpbmFs
bHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
