<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">divide</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyB4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZGVjaW1hbC54Iik7CiAgU3RyaW5n
IHkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWNpbWFsLnkiKTsKICBTdHJpbmcg
cHJlY2lzaW9uID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcHJlY2lzaW9uIik7CiAg
U3RyaW5nIHJvdW5kaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcm91bmRpbmci
KTsKCiAgaWYgKHggIT0gbnVsbCAmJiB5ICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAi
JGRlY2ltYWwiLCBkaXZpZGUoeCwgeSwgcHJlY2lzaW9uLCByb3VuZGluZykpOwp9IGZpbmFsbHkg
ewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
