<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">divide</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWNpbWFsLngiKTsNCiAg
ICBTdHJpbmcgeSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGRlY2ltYWwueSIpOw0K
ICAgIFN0cmluZyBwcmVjaXNpb24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRwcmVj
aXNpb24iKTsNCiAgICBTdHJpbmcgcm91bmRpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNv
ciwgIiRyb3VuZGluZyIpOw0KDQogICAgaWYgKHggIT0gbnVsbCAmJiB5ICE9IG51bGwpIElEYXRh
VXRpbC5wdXQoY3Vyc29yLCAiJGRlY2ltYWwiLCBkaXZpZGUoeCwgeSwgcHJlY2lzaW9uLCByb3Vu
ZGluZykpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
