<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">process</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBTdHJpbmcuY2xh
c3MpOw0KICAgIFN0cmluZyBtb2RlID0gSURhdGFIZWxwZXIuZmlyc3RPckRlZmF1bHQoY3Vyc29y
LCBTdHJpbmcuY2xhc3MsICJyZWFkIiwgIiRmaWxlLm1vZGUiLCAiJG1vZGUiKTsNCiAgICBTdHJp
bmcgc2VydmljZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc2VydmljZSIsIFN0cmluZy5j
bGFzcyk7DQogICAgU3RyaW5nIGlucHV0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRzZXJ2
aWNlLmlucHV0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBJRGF0YSBzY29wZSA9IElEYXRhSGVscGVy
LmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGlwZWxpbmUiLCBJRGF0YS5jbGFzcywgcGlwZWxpbmUp
Ow0KICAgIGJvb2xlYW4gcmFpc2UgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAi
JHJhaXNlPyIsIEJvb2xlYW4uY2xhc3MsIHRydWUpOwoNCiAgICBzY29wZSA9IEZpbGVIZWxwZXIu
cHJvY2VzcyhGaWxlSGVscGVyLmNvbnN0cnVjdChmaWxlKSwgbW9kZSwgc2VydmljZSwgaW5wdXQs
IHNjb3BlLCByYWlzZSwgdHJ1ZSk7DQoNCiAgICBpZiAoc2NvcGUgIT0gcGlwZWxpbmUpIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkcGlwZWxpbmUiLCBzY29wZSk7DQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
