<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">process</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBmaWxlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkZmlsZSIpOwogIFN0cmluZyBt
b2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9kZSIpOwogIFN0cmluZyBzZXJ2
aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkc2VydmljZSIpOwogIElEYXRhIHNj
b3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGluZSIpOwogIGJvb2xlYW4g
c2NvcGVkID0gc2NvcGUgIT0gbnVsbDsKCiAgc2NvcGUgPSBwcm9jZXNzKGZpbGUsIG1vZGUsIHNl
cnZpY2UsIHNjb3BlZD8gc2NvcGUgOiBwaXBlbGluZSk7CgogIGlmIChzY29wZWQpIElEYXRhVXRp
bC5wdXQoY3Vyc29yLCAiJHBpcGVsaW5lIiwgc2NvcGUpOwp9IGZpbmFsbHkgewogIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
