<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">uppercase</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgb3BlcmFuZHMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHVwcGVyY2FzZS5vcGVy
YW5kcyIsIElEYXRhLmNsYXNzKTsKICAgIExvY2FsZSBsb2NhbGUgPSBJRGF0YUhlbHBlci5maXJz
dE9yRGVmYXVsdChjdXJzb3IsIExvY2FsZS5jbGFzcywgTG9jYWxlLmdldERlZmF1bHQoKSwgIiR1
cHBlcmNhc2UubG9jYWxlIiwgIiRsb2NhbGUiKTsNCiAgICBpZiAob3BlcmFuZHMgPT0gbnVsbCkg
ewogICAgICAgIFN0cmluZyBzdHJpbmcgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJHN0cmlu
ZyIsIFN0cmluZy5jbGFzcyk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzdHJp
bmciLCBTdHJpbmdIZWxwZXIudXBwZXJjYXNlKHN0cmluZywgbG9jYWxlKSwgZmFsc2UpOw0NCiAg
ICB9IGVsc2UgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkdXBwZXJjYXNlLnJl
c3VsdHMiLCBUcmFuc2Zvcm1lci50cmFuc2Zvcm0ob3BlcmFuZHMsIG5ldyBVcHBlcmNhc2VyKFRy
YW5zZm9ybWVyTW9kZS5WQUxVRVMsIGxvY2FsZSwgdHJ1ZSkpLCBmYWxzZSk7CiAgICB9Cn0gZmlu
YWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
