<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkaWQiKTsNCiAgICBTdHJp
bmcgbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG5hbWUiKTsKCiAgICBpZiAo
aWQgIT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc2NoZWR1bGUi
LCBTY2hlZHVsZUhlbHBlci5nZXQoaWQpLCB0cnVlKTsNCiAgICB9IGVsc2UgaWYgKG5hbWUgIT0g
bnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkc2NoZWR1bGUiLCBTY2hl
ZHVsZUhlbHBlci5nZXRCeU5hbWUobmFtZSksIHRydWUpOwogICAgfQp9IGZpbmFsbHkgew0KICAg
IGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
