<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkaWQiKTsNCiAgICBTdHJp
bmcgbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJG5hbWUiKTsKCiAgICBpZiAo
aWQgIT0gbnVsbCkgewogICAgICAgIElEYXRhIHNjaGVkdWxlID0gZ2V0KGlkKTsNCiAgICAgICAg
aWYgKHNjaGVkdWxlICE9IG51bGwpIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHNjaGVkdWxlIiwg
c2NoZWR1bGUpOw0KICAgIH0gZWxzZSBpZiAobmFtZSAhPSBudWxsKSB7CiAgICAgICAgSURhdGEg
c2NoZWR1bGUgPSBnZXRCeU5hbWUobmFtZSk7CiAgICAgICAgaWYgKHNjaGVkdWxlICE9IG51bGwp
IElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHNjaGVkdWxlIiwgc2NoZWR1bGUpOwogICAgfQp9IGZp
bmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
