<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nW10gZGlyZWN0b3JpZXMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRpcmVjdG9yaWVz
IiwgU3RyaW5nW10uY2xhc3MpOwogICAgYm9vbGVhbiByZWN1cnNlID0gSURhdGFIZWxwZXIuZ2V0
T3JEZWZhdWx0KGN1cnNvciwgIiRyZWN1cnNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAg
ICBMaXN0PFRocm93YWJsZT4gZXhjZXB0aW9ucyA9IG5ldyBBcnJheUxpc3Q8VGhyb3dhYmxlPigp
OwoKICAgIGZvciAoU3RyaW5nIGRpcmVjdG9yeSA6IGRpcmVjdG9yaWVzKSB7CiAgICAgICAgdHJ5
IHsKICAgICAgICAgICAgRGlyZWN0b3J5SGVscGVyLnJlbW92ZShGaWxlSGVscGVyLmNvbnN0cnVj
dChkaXJlY3RvcnkpLCByZWN1cnNlKTsKICAgICAgICB9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7
CiAgICAgICAgICAgIGV4Y2VwdGlvbnMuYWRkKGV4KTsKICAgICAgICB9CiAgICB9CgogICAgaWYg
KGV4Y2VwdGlvbnMuc2l6ZSgpID4gMCkgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4Y2VwdGlvbnMp
Owp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
