<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGRhdGV0aW1lID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkYXRldGltZSIsIFN0
cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIHBhdHRlcm4gPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJGRhdGV0aW1lLnBhdHRlcm4iLCBTdHJpbmcuY2xhc3MpOw0KDQogICAgSURhdGFbXSB0aW1l
em9uZXMgPSBUaW1lWm9uZUhlbHBlci50b0lEYXRhQXJyYXkoVGltZVpvbmVIZWxwZXIubGlzdCgp
LCBkYXRldGltZSwgcGF0dGVybik7DQoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHRp
bWV6b25lcyIsIHRpbWV6b25lcywgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVz
dHJveSgpOw0KfQ==</value>
</Values>
