<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">read</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIGZpbGUgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGZpbGUiLCBTdHJpbmcuY2xh
c3MpOw0KICAgIENoYXJzZXQgY2hhcnNldCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZW5j
b2RpbmciLCBDaGFyc2V0LmNsYXNzKTsNCg0gICAgT2JqZWN0Q29udmVydE1vZGUgbW9kZSA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIE9iamVjdENvbnZlcnRNb2RlLmNsYXNzKTsK
CiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGNvbnRlbnQiLCBPYmplY3RIZWxwZXIuY29u
dmVydChGaWxlSGVscGVyLnJlYWRUb0J5dGVzKGZpbGUpLCBjaGFyc2V0LCBtb2RlKSk7DQp9IGNh
dGNoKElPRXhjZXB0aW9uIGV4KSB7DQogICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsNCn0g
ZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
