<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">read</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
RmlsZSBmaWxlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRmaWxlIiwgRmlsZS5jbGFzcyk7
DQogICAgT2JqZWN0Q29udmVydE1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNvciwg
T2JqZWN0Q29udmVydE1vZGUuY2xhc3MsICIkY29udGVudC5tb2RlIiwgIiRtb2RlIik7CiAgICBD
aGFyc2V0IGNoYXJzZXQgPSBJRGF0YUhlbHBlci5maXJzdChjdXJzb3IsIENoYXJzZXQuY2xhc3Ms
ICIkY29udGVudC5lbmNvZGluZyIsICIkZW5jb2RpbmciKTsNCgogICAgSURhdGFIZWxwZXIucHV0
KGN1cnNvciwgIiRjb250ZW50IiwgT2JqZWN0SGVscGVyLmNvbnZlcnQoRmlsZUhlbHBlci5yZWFk
VG9CeXRlcyhmaWxlKSwgY2hhcnNldCwgbW9kZSkpOw0KfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkg
ew0KICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNv
ci5kZXN0cm95KCk7DQp9</value>
</Values>
