<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">equal</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZXhwZWN0ZWQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGV4cGVjdGVkIiwgSURh
dGEuY2xhc3MpOw0KICAgIElEYXRhIGFjdHVhbCA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
YWN0dWFsIiwgSURhdGEuY2xhc3MpOw0KICAgIFN0cmluZyBtZXNzYWdlID0gSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgIiRtZXNzYWdlIiwgU3RyaW5nLmNsYXNzKTsNCiAgICBib29sZWFuIHN0cmlj
dCA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkc3RyaWN0PyIsIEJvb2xlYW4u
Y2xhc3MsIGZhbHNlKTsKDQogICAgZXF1YWwoZXhwZWN0ZWQsIGFjdHVhbCwgbWVzc2FnZSwgc3Ry
aWN0KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
