<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmVuY29k
ZWQiLCBJRGF0YS5jbGFzcyk7CiAgICBDaGFyc2V0IGVuY29kaW5nID0gSURhdGFIZWxwZXIuZ2V0
KGN1cnNvciwgIiRlbmNvZGluZyIsIENoYXJzZXQuY2xhc3MpOw0KCiAgICBpZiAoZG9jdW1lbnQg
IT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQuZGVj
b2RlZCIsIFVSSUhlbHBlci5kZWNvZGUoZG9jdW1lbnQsIGVuY29kaW5nKSwgZmFsc2UpOwogICAg
fSBlbHNlIHsNCiAgICAgICAgU3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3Is
ICIkc3RyaW5nIiwgU3RyaW5nLmNsYXNzKTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29y
LCAiJHN0cmluZyIsIFVSSUhlbHBlci5kZWNvZGUoc3RyaW5nLCBlbmNvZGluZyksIGZhbHNlKTsN
CiAgICB9Cn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
