<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmVuY29k
ZWQiLCBJRGF0YS5jbGFzcyk7CiAgICBDaGFyc2V0IGVuY29kaW5nID0gSURhdGFIZWxwZXIuZ2V0
KGN1cnNvciwgIiRlbmNvZGluZyIsIENoYXJzZXQuY2xhc3MpOw0KCiAgICBpZiAoZG9jdW1lbnQg
PT0gbnVsbCkgewogICAgICAgIFN0cmluZyBzdHJpbmcgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJHN0cmluZyIsIFN0cmluZy5jbGFzcyk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNv
ciwgIiRzdHJpbmciLCBVUklIZWxwZXIuZGVjb2RlKHN0cmluZywgZW5jb2RpbmcpLCBmYWxzZSk7
CiAgICB9IGVsc2UgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQu
ZGVjb2RlZCIsIFVSSUhlbHBlci5kZWNvZGUoZG9jdW1lbnQsIGVuY29kaW5nKSwgZmFsc2UpOwog
ICAgfQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
