<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decompress</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogIE9i
amVjdCBpbnB1dCA9IElEYXRhVXRpbC5nZXQoY3Vyc29yLCAiJGNvbnRlbnRzLnppcCIpOw0KICBT
dHJpbmcgY2hhcnNldCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGVuY29kaW5nIik7
DQogIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9kZSIpOw0K
DQogIFppcEVudHJ5V2l0aERhdGFbXSBlbnRyaWVzID0gWmlwSGVscGVyLmRlY29tcHJlc3MoU3Ry
ZWFtSGVscGVyLm5vcm1hbGl6ZShpbnB1dCwgY2hhcnNldCkpOw0KICANCiAgaWYgKGVudHJpZXMg
IT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkY29udGVudHMiLCBaaXBFbnRyeVdpdGhE
YXRhLnRvSURhdGFBcnJheShlbnRyaWVzLCBjaGFyc2V0LCBtb2RlKSk7CQkgIA0KfSBjYXRjaChJ
T0V4Y2VwdGlvbiBleCkgew0KICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5
IHsNCiAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
