<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decompress</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
T2JqZWN0IGlucHV0ID0gSURhdGFVdGlsLmdldChjdXJzb3IsICIkY29udGVudHMuemlwIik7DQog
ICAgU3RyaW5nIGNoYXJzZXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRlbmNvZGlu
ZyIpOw0KICAgIFN0cmluZyBtb2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbW9k
ZSIpOw0KDQogICAgWmlwRW50cnlXaXRoRGF0YVtdIGVudHJpZXMgPSBaaXBIZWxwZXIuZGVjb21w
cmVzcyhJbnB1dFN0cmVhbUhlbHBlci5ub3JtYWxpemUoaW5wdXQsIENoYXJzZXRIZWxwZXIubm9y
bWFsaXplKGNoYXJzZXQpKSk7DQoNCiAgICBpZiAoZW50cmllcyAhPSBudWxsKSBJRGF0YVV0aWwu
cHV0KGN1cnNvciwgIiRjb250ZW50cyIsIFppcEVudHJ5V2l0aERhdGEudG9JRGF0YUFycmF5KGVu
dHJpZXMsIENoYXJzZXRIZWxwZXIubm9ybWFsaXplKGNoYXJzZXQpLCBPYmplY3RDb252ZXJ0TW9k
ZS5ub3JtYWxpemUobW9kZSkpKTsNCn0gY2F0Y2goSU9FeGNlcHRpb24gZXgpIHsNCiAgICBFeGNl
cHRpb25IZWxwZXIucmFpc2UoZXgpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgp
Ow0KfQ==</value>
</Values>
