<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIElEYXRhIHNjb3BlID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1
cnNvciwgIiRwaXBlbGluZSIsIElEYXRhLmNsYXNzLCBwaXBlbGluZSk7DQogICAgU3RyaW5nIGRl
ZmF1bHRWYWx1ZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZGVmYXVsdCIsIFN0cmluZy5j
bGFzcyk7DQogICAgRW51bVNldDxTdWJzdGl0dXRpb25UeXBlPiBtb2RlID0gU3Vic3RpdHV0aW9u
VHlwZS5ub3JtYWxpemUoSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRtb2RlIiwgU3RyaW5nLmNs
YXNzKSk7Cg0KICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkZG9jdW1lbnQiLCBTdWJzdGl0
dXRpb25IZWxwZXIuc3Vic3RpdHV0ZShkb2N1bWVudCwgZGVmYXVsdFZhbHVlLCB0cnVlLCBtb2Rl
LCBzY29wZSksIGZhbHNlKTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=
</value>
</Values>
