<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGRvY3VtZW50ID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRkb2N1bWVudCIpOwogIElE
YXRhIHNjb3BlID0gSURhdGFVdGlsLmdldElEYXRhKGN1cnNvciwgIiRwaXBlbGluZSIpOwogIFN0
cmluZyBkZWZhdWx0VmFsdWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRkZWZhdWx0
Iik7CgogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGFIZWxwZXIuc3Vi
c3RpdHV0ZShkb2N1bWVudCwgZGVmYXVsdFZhbHVlLCBzY29wZSA9PSBudWxsID8gcGlwZWxpbmUg
OiBzY29wZSwgdHJ1ZSkpOwp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
