<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substitute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
SURhdGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURh
dGEuY2xhc3MpOw0KICAgIFN0cmluZyBkZWZhdWx0VmFsdWUgPSBJRGF0YUhlbHBlci5maXJzdChj
dXJzb3IsIFN0cmluZy5jbGFzcywgIiRzdWJzdGl0dXRpb24uZGVmYXVsdCIsICIkZGVmYXVsdCIp
Ow0KICAgIFN1YnN0aXR1dGlvblR5cGUgbW9kZSA9IElEYXRhSGVscGVyLmZpcnN0KGN1cnNvciwg
U3Vic3RpdHV0aW9uVHlwZS5jbGFzcywgIiRzdWJzdGl0dXRpb24ubW9kZSIsICIkbW9kZSIpOwog
ICAgSURhdGEgc2NvcGUgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJHBpcGVs
aW5lIiwgSURhdGEuY2xhc3MsIHBpcGVsaW5lKTsKDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNv
ciwgIiRkb2N1bWVudCIsIFN1YnN0aXR1dGlvbkhlbHBlci5zdWJzdGl0dXRlKGRvY3VtZW50LCBk
ZWZhdWx0VmFsdWUsIHRydWUsIGZhbHNlLCBtb2RlLCBzY29wZSksIGZhbHNlKTsNCn0gZmluYWxs
eSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=</value>
</Values>
