<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purgable</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRmls
ZSBkaXJlY3RvcnkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRpcmVjdG9yeSIsIEZpbGUu
Y2xhc3MpOwogICAgU3RyaW5nIGR1cmF0aW9uU3RyaW5nID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNv
ciwgIiRkdXJhdGlvbiIsIFN0cmluZy5jbGFzcyk7CiAgICBTdHJpbmcgZHVyYXRpb25QYXR0ZXJu
ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRkdXJhdGlvbi5wYXR0ZXJuIiwgU3RyaW5nLmNs
YXNzKTsKCiAgICBEdXJhdGlvbiBkdXJhdGlvbiA9IER1cmF0aW9uSGVscGVyLnBhcnNlKGR1cmF0
aW9uU3RyaW5nLCBkdXJhdGlvblBhdHRlcm4pOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
ICIkcHVyZ2FibGU/Iiwgc2hvdWxkUHVyZ2UoZGlyZWN0b3J5LCBkdXJhdGlvbiksIFN0cmluZy5j
bGFzcyk7CiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHB1cmdlLmxhc3QiLCBESVJFQ1RP
UllfUFVSR0VTLmdldChkaXJlY3RvcnkpLCBTdHJpbmcuY2xhc3MsIGZhbHNlKTsKICAgIElEYXRh
SGVscGVyLnB1dChjdXJzb3IsICIkcHVyZ2UubmV4dCIsIG5leHRQdXJnZShkaXJlY3RvcnksIGR1
cmF0aW9uKSwgU3RyaW5nLmNsYXNzKTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
