<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">purgable</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGRpcmVjdG9yeSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZGlyZWN0b3J5IiwgU3Ry
aW5nLmNsYXNzKTsKICAgIFN0cmluZyBkdXJhdGlvblN0cmluZyA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICIkZHVyYXRpb24iLCBTdHJpbmcuY2xhc3MpOwogICAgU3RyaW5nIGR1cmF0aW9uUGF0
dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZHVyYXRpb24ucGF0dGVybiIsIFN0cmlu
Zy5jbGFzcyk7CgogICAgZGlyZWN0b3J5ID0gRmlsZUhlbHBlci5ub3JtYWxpemUoZGlyZWN0b3J5
KTsKICAgIER1cmF0aW9uIGR1cmF0aW9uID0gRHVyYXRpb25IZWxwZXIucGFyc2UoZHVyYXRpb25T
dHJpbmcsIGR1cmF0aW9uUGF0dGVybik7CgogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRw
dXJnYWJsZT8iLCBzaG91bGRQdXJnZShkaXJlY3RvcnksIGR1cmF0aW9uKSwgU3RyaW5nLmNsYXNz
KTsKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcHVyZ2UubGFzdCIsIERJUkVDVE9SWV9Q
VVJHRVMuZ2V0KGRpcmVjdG9yeSksIFN0cmluZy5jbGFzcywgZmFsc2UpOwogICAgSURhdGFIZWxw
ZXIucHV0KGN1cnNvciwgIiRwdXJnZS5uZXh0IiwgbmV4dFB1cmdlKGRpcmVjdG9yeSwgZHVyYXRp
b24pLCBTdHJpbmcuY2xhc3MpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==
</value>
</Values>
