<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSW5w
dXRPdXRwdXRTaWduYXR1cmUgZGlyZWN0aW9uID0gSURhdGFIZWxwZXIucmVtb3ZlKGN1cnNvciwg
IiRzZXJ2aWNlLnNpZ25hdHVyZS5kaXJlY3Rpb24iLCBJbnB1dE91dHB1dFNpZ25hdHVyZS5jbGFz
cyk7CiAgICBib29sZWFuIHJhaXNlID0gSURhdGFIZWxwZXIucmVtb3ZlT3JEZWZhdWx0KGN1cnNv
ciwgIiR2YWxpZGF0aW9uLnJhaXNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBWYWxp
ZGF0aW9uUmVzdWx0IHJlc3VsdCA9IFBpcGVsaW5lSGVscGVyLnZhbGlkYXRlKHBpcGVsaW5lLCBk
aXJlY3Rpb24pOwoKICAgIHJlc3VsdC5yYWlzZUlmSW52YWxpZChyYWlzZSk7CgogICAgSURhdGFI
ZWxwZXIucHV0KGN1cnNvciwgIiR2YWxpZGF0aW9uLnJlc3VsdD8iLCByZXN1bHQuaXNWYWxpZCgp
LCBTdHJpbmcuY2xhc3MpOwogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiR2YWxpZGF0aW9u
Lm1lc3NhZ2UiLCByZXN1bHQuZ2V0TWVzc2FnZSgpLCBmYWxzZSk7CiAgICBJRGF0YUhlbHBlci5w
dXQoY3Vyc29yLCAiJHZhbGlkYXRpb24uZXJyb3JzIiwgcmVzdWx0LmdldEVycm9ycygpLCBmYWxz
ZSk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
