<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgQ2hhcnNldCBjaGFyc2V0ID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRl
bmNvZGluZyIsIENoYXJzZXQuY2xhc3MpOwogICAgT2JqZWN0Q29udmVydE1vZGUgbW9kZSA9IElE
YXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIE9iamVjdENvbnZlcnRNb2RlLmNsYXNzKTsK
ICAgIGJvb2xlYW4gbWluaWZ5ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRt
aW5pZnk/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwoKICAgIGlmIChkb2N1bWVudCAhPSBudWxs
KSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRjb250ZW50IiwgT2JqZWN0SGVs
cGVyLmNvbnZlcnQobmV3IElEYXRhSlNPTlBhcnNlcighbWluaWZ5KS5lbWl0KGRvY3VtZW50LCBj
aGFyc2V0KSwgY2hhcnNldCwgbW9kZSkpOwogICAgfQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBleCkg
ewogICAgRXhjZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBmaW5hbGx5IHsKICAgIGN1cnNvci5k
ZXN0cm95KCk7Cn0=</value>
</Values>
