<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">emit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50IiwgSURhdGEu
Y2xhc3MpOwogICAgU3RyaW5nIGV4dGVuc2lvbiA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChj
dXJzb3IsICIkZXh0ZW5zaW9uIiwgU3RyaW5nLmNsYXNzLCAieGxzeCIpOwogICAgT2JqZWN0Q29u
dmVydE1vZGUgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIE9iamVjdENv
bnZlcnRNb2RlLmNsYXNzKTsKCiAgICBpZiAoZG9jdW1lbnQgIT0gbnVsbCkgewogICAgICAgIElE
YXRhRXhjZWxQYXJzZXIgcGFyc2VyID0gbmV3IElEYXRhRXhjZWxQYXJzZXIoZXh0ZW5zaW9uLmVx
dWFscygieGxzeCIpKTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGNvbnRlbnQi
LCBPYmplY3RIZWxwZXIuY29udmVydChwYXJzZXIuZW1pdChkb2N1bWVudCksIG1vZGUpKTsKICAg
IH0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBlci5yYWlzZShl
eCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
