<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgZG9jdW1lbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGRvY3VtZW50LmRlY29kZWQi
LCBJRGF0YS5jbGFzcyk7CiAgICBTdHJpbmcgYXR0cmlidXRlUHJlZml4ID0gSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgIiRhdHRyaWJ1dGUucHJlZml4IiwgU3RyaW5nLmNsYXNzKTsKCiAgICBpZiAo
ZG9jdW1lbnQgPT0gbnVsbCkgewogICAgICAgIFN0cmluZyBzdHJpbmcgPSBJRGF0YUhlbHBlci5n
ZXQoY3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZy5jbGFzcyk7CiAgICAgICAgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiRzdHJpbmciLCBYTUxIZWxwZXIuZW5jb2RlKHN0cmluZyksIGZhbHNlKTsK
ICAgIH0gZWxzZSB7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRkb2N1bWVudC5l
bmNvZGVkIiwgWE1MSGVscGVyLmVuY29kZShkb2N1bWVudCwgYXR0cmlidXRlUHJlZml4KSwgZmFs
c2UpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
