<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsID0gSURhdGFIZWxw
ZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRsaXRlcmFsPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNl
KTsKICAgIFN0cmluZyBtb2RlID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRtb2RlIiwgU3Ry
aW5nLmNsYXNzKTsKDQogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRzdHJpbmciLCBTdHJp
bmdIZWxwZXIucmVtb3ZlKHN0cmluZywgcGF0dGVybiwgbGl0ZXJhbCwgKCEobW9kZSA9PSBudWxs
IHx8IG1vZGUuZXF1YWxzKCJhbGwiKSkpKSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJz
b3IuZGVzdHJveSgpOw0KfQ==</value>
</Values>
