<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgYm9vbGVhbiBsaXRlcmFsUGF0dGVybiA9IElE
YXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcGF0dGVybi5saXRlcmFsPyIsIEJvb2xl
YW4uY2xhc3MsIElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkbGl0ZXJhbD8iLCBC
b29sZWFuLmNsYXNzLCBmYWxzZSkpOwogICAgQm9vbGVhbiBmaXJzdE9jY3VycmVuY2UgPSBJRGF0
YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJG9jY3VycmVuY2UuZmlyc3Q/IiwgQm9vbGVh
bi5jbGFzcywgZmFsc2UpOwoKICAgIGlmIChmaXJzdE9jY3VycmVuY2UgPT0gbnVsbCkgewogICAg
ICAgIC8vIHN1cHBvcnQgbW9kZSBmb3IgYmFja3dhcmRzIGNvbXBhdGliaWxpdHkKICAgICAgICBT
dHJpbmcgbW9kZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbW9kZSIsIFN0cmluZy5jbGFz
cyk7CiAgICAgICAgZmlyc3RPY2N1cnJlbmNlID0gbW9kZSAhPSBudWxsICYmIG1vZGUuZXF1YWxz
KCJmaXJzdCIpOwogICAgfQoNCiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHN0cmluZyIs
IFN0cmluZ0hlbHBlci5yZW1vdmUoc3RyaW5nLCBwYXR0ZXJuLCBsaXRlcmFsUGF0dGVybiwgZmly
c3RPY2N1cnJlbmNlKSwgZmFsc2UpOw0KfSBmaW5hbGx5IHsNCiAgICBjdXJzb3IuZGVzdHJveSgp
Ow0KfQ==</value>
</Values>
