<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHN0cmluZyA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkc3RyaW5nIiwgU3RyaW5n
LmNsYXNzKTsNCiAgICBTdHJpbmcgcGF0dGVybiA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIk
cGF0dGVybiIsIFN0cmluZy5jbGFzcyk7DQogICAgU3RyaW5nIG1vZGUgPSBJRGF0YUhlbHBlci5n
ZXQoY3Vyc29yLCAiJG1vZGUiLCBTdHJpbmcuY2xhc3MpOwoNCiAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJHN0cmluZyIsIFN0cmluZ0hlbHBlci5yZW1vdmUoc3RyaW5nLCBwYXR0ZXJuLCAo
IShtb2RlID09IG51bGwgfHwgbW9kZS5lcXVhbHMoImFsbCIpKSkpLCBmYWxzZSk7DQp9IGZpbmFs
bHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9</value>
</Values>
